### ISSUE TITLE
a demo on iphone by using turn.js

### ISSUE THREAD

**Issue by zhangchunsheng** [blasten/turn.js#10]
this a demo on iphone by using turn.js.http://zreader.sinaapp.com/beijixing/demo/reader.html

**Comment by blasten** [comment]
Looks nice!  Let me know if you have a problem.

**Comment by zhangchunsheng** [comment]
I hope turn.js can support single flip.

**Comment by blasten** [comment]
It's possible to do that now, take a look at this demo: https://www.youtube.com/watch?v=m9D-nD5v83c.  You can create a wrapper for the book and set the same width you use for the pages within the book, then you have to change the 'left' or 'margin-left' property of the book depending on the page you want to show.
