### ISSUE TITLE
Print support

### ISSUE THREAD

**Issue by devolved** [blasten/turn.js#100]
**Is there an included method to "un-turn" the page and return it to a plain html state?**

I'd like to be able to offer users option to print out the book/magazine in it's entirety rather than as a div/page ...

as well as offer different reading options, such as linearizing the page.

Is there  way/method of "un-initialising" the entire turn.js so I can display it like so?

I'm mindful of diving in to the turn.js itself as I need to keep functional extensions maintainable in a separate file.

**Comment by blasten** [comment]
Yes the 4th release includes a method called `destroy,` but it removes all the pages. However you can read the entire text from all the pages using the object  `$('selector').data().pageObjs`. This object contains all the pages stored in your flipbook and you can read its text or HTML content.

**Comment by devolved** [comment]
Cool, I did make a small cloning function but obv this could become unweildy quickly. Much happier using native functions.

Good job on v4, v much a product now rather than a handy script.

**Comment by ghost** [comment]
I wanted to know the solution of doing this any help would be great :)
