### ISSUE TITLE
Pages are not running,

### ISSUE THREAD

**Issue by asimkhaliq** [blasten/turn.js#104]
I bought the turnjs4 and i was trying to run the sample files steve job one, and its not running on firefox and chrome. Page 5 and onward is empty and just showing me loading image. I am using FF ver13

**Comment by blasten** [comment]
@asimkhaliq the only problem with Chrome is the hardware acceleration feature, that can be solved by adding: {acceleration:false} to turn.js. I tested it on FF 13 and it's working, I didn't see any problem. The only problem is that isn't loading the pages?

**Comment by asimkhaliq** [comment]
It is just showing me the empty pages , I cannot see images inside the pages. The sample folder docs working fine b/c they are not html pages but just the images.  and I need to use html pages for this as I need to use  area map on images.

**Comment by blasten** [comment]
Does that happen with all the pages or only few of them?

**Comment by asimkhaliq** [comment]
i cannot see anything after steve job office image, beyond that point its all empty. If you want i can share my screen

**Comment by blasten** [comment]
That is so rare, please send me a screenshot to my email. How about the samples on turnjs.com?

**Comment by asimkhaliq** [comment]
ok let me send you screen shot

**Comment by asimkhaliq** [comment]
Please check this

**Comment by asimkhaliq** [comment]
on your website its running fine, I am checking on local machines

**Comment by mikebonds** [comment]
I am having the same issue as asimkhaliq.

**Comment by blasten** [comment]
I saw a problem when opening on a browser with no test server.  Are you using a test web server or just opening the index.html in the browser?  This sample uses Ajax and browsers prevent Ajax requests because of security reasons but I believe it's possible to change in the settings.

**Comment by asimkhaliq** [comment]
yes i figure that out already thru server it is running fine. But on IE there are other issues, when I open  the pages runs here and there etc

**Comment by blasten** [comment]
Sorry, what kind of issues? Is it IE 9?

**Comment by asimkhaliq** [comment]
yes it is IE 9, when I open the first page it goes to left of my screen and then on next page it starts jumping left right center.

**Comment by blasten** [comment]
Fixed!
