### ISSUE TITLE
Tiny Pages smaller than 300px in height

### ISSUE THREAD

**Issue by ubernaut** [blasten/turn.js#105]
I'm trying to use the turn.js effect for a mobile pull tab game.   When I pass in a value smaller than 300px for the height it won't work. 

$(".PullTabGroup").turn({
                width: 200,
                height: 75,
                autoCenter: true
            });

<div class="PullTabGroup">  
    <div class="PullTab PullTabCover"> <---- Pull Tab </div>  
    <div class="PlaceHolder PullTabBackCover PullTab">You Won!</div>
    <div class="PullTab GameTab" > :) :) :)</div>
</div>

I can only get the pages to the correct height by initially setting the height value to 300px in the turn function and then changing the css height value using chrome developer tools.  This only works for the pages though, the actual turning animation remains 300px in height. 

Is it possible to use this for height values smaller than 300px? I would be satisfied with a horizontal page turning effect from the edge instead of the diagonal effect from the corner as well. if you can help me get this working I'll gladly pay the $100 developer fee.

**Comment by blasten** [comment]
Sure, let me work on that this week

**Comment by blasten** [comment]
@ubernaut turn.js 4th release supports height values smaller than 300px. Even 50px, if you reduce the size of each corner.
