### ISSUE TITLE
rtl direction

### ISSUE THREAD

**Issue by mohamedali** [blasten/turn.js#106]
hi i was just wondering how to make this work in RTL direction
Thank you.

**Comment by blasten** [comment]
It doesn't work yet. I hope to include it in new releases of turn.js

**Comment by blasten** [comment]
@mohamedali now turn.js 4 supports RTL direction. check that out on turnjs.com

**Comment by mohamedali** [comment]
please he is not working help please

**Comment by blasten** [comment]
@mohamedali What problem do you have?  Can you send me the HTML file?

**Comment by mohamedali** [comment]
<!doctype html>
<html>
<head>

<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>

<script type="text/javascript" src="../../turn.min.js"></script>


<style type="text/css">
body{
    background:#ccc;
}
#magazine{
    width:1152px;
    height:752px;
}
#magazine .turn-page{
    background-color:#ccc;
    background-size:100% 100%;
}
#magazine {
    direction:rtl;
}
</style>

</head>
<body>

<div id="magazine" dir="rtl">
<div style="background-image:url(pages/cover.fbk);"></div>
<div style="background-image:url(pages/Quran_Page_001.fbk);"></div>
<div style="background-image:url(pages/Quran_Page_002.fbk);"></div>
<div style="background-image:url(pages/Quran_Page_003.fbk);"></div>
<div style="background-image:url(pages/Quran_Page_004.fbk);"></div>

</div>


<script type="text/javascript">

    $(window).ready(function() {
        $('#magazine').turn({
                            
                        });
    });
    
        
    </script>


</body>
</html>
