### ISSUE TITLE
Magazine Demo Error in IE8 - Object doesn't support this property or method

### ISSUE THREAD

**Issue by vagabondcreative** [blasten/turn.js#107]
Hello,

I am looking at purchasing and implementing V4 with zoom for a client as it is exampled on this page:

http://turnjs.com/samples/magazine/

However I'm noticing that this example does not work in IE8 which is a priority for my client.

```
Webpage error details

Message: Object doesn't support this property or method
Line: 38
Char: 416
Code: 0
URI: http://turnjs.com/lib/turn.html4.min.js
```

It appears V4 is supposed to support IE8 : http://turnjs.com/features.pdf

Discussed here: https://github.com/blasten/turn.js/issues/64

Can you please tell me if there is anything that can be done? My client is looking to move on this as soon as possible so I look forward to your response.

Thanks!

**Comment by blasten** [comment]
@vagabondcreative It's fixed http://turnjs.com/samples/magazine/

**Comment by carloscoletti** [comment]
this sample http://turnjs.com/samples/magazine/ does not work in the IE8 ?
What's happening ?
