### ISSUE TITLE
3d acceleration causes error in rendering on chrome

### ISSUE THREAD

**Issue by maxabrahamsson** [blasten/turn.js#110]
When use3d variable is set true , on folding page nonsense gray rectangles appearing on page in the background.

**Comment by maxabrahamsson** [comment]
line 1537 : 
that.css(v).transform(rotate(a) + translate(tr.x + aliasingFk, tr.y, ac), x);
i replaced with following line to fix.
 that.css(v).transform(rotate(a) + translate(tr.x + aliasingFk, tr.y, false), x);

i dont know if there is anyway to set ac variable to false without changing this line.

**Comment by blasten** [comment]
Yes, it's a problem of composition in Chrome 19 - 20.0.1  http://code.google.com/p/chromium/issues/detail?id=128488. So for now, you have to set acceleration: false in Chrome browsers.
