### ISSUE TITLE
turnjs v4 dev is a lot harder to follow

### ISSUE THREAD

**Issue by jedahan** [blasten/turn.js#114]
Before I could look at the commits on github, know what was changed, understand those changes easily, and update my code to integrate those changes.

Now I get an email with a new url to a manual download of a zip file with a changelog that is not updated frequently, and does not contain the git tree in it. 

I can do a manual diff but it is still a pain to use emails and zips to update the code instead of submodules and github.

How difficult would it be to just make a separate private repository for turnjs v4, and add whoever has paid as a contributor?

**Comment by blasten** [comment]
@jedahan Yes that's one option. I hope to upload the private repository as soon as possible.

**Comment by jedahan** [comment]
cool!
