### ISSUE TITLE
Version:4.0.7 When turning a page, it turns twice

### ISSUE THREAD

**Issue by dannyvandijck** [blasten/turn.js#115]
Reproducible at turnjs4/samples/basic/index.html.

When you turn the first page with your mouse starting from a corner and you then let the page go at the left side, it jumps back and then turns instead of just dropping to the right.

We have this behavior also in our flipbook:

Events called in this order: (no start since we simulate a peel), turning, end (pageObject=false) , start, end (pageObject=true) , end (pageObject=false), turned.

Normal behavior: start, turning , end (pageObject=true) , end (pageObject=false), turned.

This behavior wasn't present in the version 3. The bug was already present in version 4.0.0

**Comment by blasten** [comment]
@dannyvandijck I have tried in several ways and I couldn't replicate the problem. when you say (pageObject=true) what you mean? you get a boolean instead of an object?  or true means that you get the page object?   Also, can you tell me the browser and version?

**Comment by dannyvandijck** [comment]
In your pdf documentation at end event:

end:
This event is triggered after ending the motion of a page.
Parameter Type Description
event Event Event object.
page Number The page number
pageObject Object The page data --> third parameter

So idd that Object gives me a boolean, which is true or false

Latest FF, Chrome, IE 7->9, Safari

  end : function(e, page, pageObj) {
                    *******(page);
                    alert('end')
                }

**Comment by dannyvandijck** [comment]
Firebug:

this
    div#book

arguments
    [Object { type="end", timeStamp=1342188263173, jQuery17208173651955587974=true, meer...}, Object { acceleration=true, cornerSize=100, duration=600, meer...}, false]

e
    Object { type="end", timeStamp=1342188263173, jQuery17208173651955587974=true, meer...}

page
    Object { acceleration=true, cornerSize=100, duration=600, meer...}

pageObj
    false

toString
    function()

**Comment by blasten** [comment]
I apologize there's a mistake in the PDF, please check: turnjs.com/docs

**Comment by dannyvandijck** [comment]
Do you have some more information about the behavior itself? (double flipping)

It only happens the first time, if you go back to that page it flips normal. (behavior is done by using the mouse and dragging it to the other side)

**Comment by blasten** [comment]
@dannyvandijck Could you share the complete code?

**Comment by dannyvandijck** [comment]
Dear,

I found the mistake.

When i was integrating html4 for IE8 and IE7. The "turning" event wasn't triggered, where my function calls where to update my book (prefetching,...).
So i copied the "turning" event and put "turned" next to it. So at that point I had a "turning" and a "turned" event in the constructor, doing both the same thing."

Now i just removed the "turning" event and do everything in the "turned" event.

Note: you could check the "turning" event in IE 7 and 8. I had problems with that.

**Comment by blasten** [comment]
@dannyvandijck Thanks! let me check turning in IE 7/8
