### ISSUE TITLE
turnCorners doesn't work

### ISSUE THREAD

**Issue by tunix** [blasten/turn.js#116]
I tried both single and double displays. I define:

{
...
turnCorners: 'bl,br',
...
}

still i see a curl effect on the top left and top right. Seems like I can't control this behaviour yet. Using 4.0.7 btw.

**Comment by blasten** [comment]
`turnCorners` are the corners to be used when turning the page if the user dind't click any corner. Therefore, it doesn't disable any corner.   To disable the corner you have to use the `start` event.  In the docs, there's a sample: http://turnjs.com/docs/Event:_start
