### ISSUE TITLE
Prevent flip book from turning to back cover

### ISSUE THREAD

**Issue by emangarcia** [blasten/turn.js#117]
Is there a way to disable corners when your on the second to last page so that it doesnt flip to the back cover? I tried using this code snippet but second to last page still flips.

<code>if (page===1 || page===7) {
       e.preventDefault();
       return;
}</code>

**Comment by blasten** [comment]
Which event did you use?  it seems to be turning.  `turning` doesn't disable the corners.   turning will just prevent to turn the page.   To disable the corner make sure that you are using the start event.  http://turnjs.com/docs/Event:_start

**Comment by emangarcia** [comment]
Yes I am using both turning and start events to prevent animation and page flip. Realized I used the wrong page number for the turning event, issue has been resolved.
