### ISSUE TITLE
4.0.8 Cannot disable book during turn

### ISSUE THREAD

**Issue by nordyke** [blasten/turn.js#119]
When the 'turning' event fires, I want to disable the page turn for a set amount of time, so I can throttle how often the user turns the pages.  Unfortunately, somewhere between the initial release of 4.0 and 4.0.8, I lost the ability to do this, because turn.js re-enables the book automatically during the turn.

**Comment by blasten** [comment]
@nordyke Let me check that out.

**Comment by blasten** [comment]
@nordyke I have tested, here's the snippet:

``` javascript
$("#flipbook").turn({
    when: {
        turning: function(event, page, view) {
            $(this).turn('disable', true);
            setTimeout("$(\"#flipbook\").turn(\"disable\", false);", 10000);
        }
});
```

My test is working fine, the book is disabled and I cannot turn any page, then enabled after 10s.  Is that what you attempted to achieve?

**Comment by nordyke** [comment]
Closing this old issue. I'm sorry about never responding.
