### ISSUE TITLE
Multiple books on a single webpage

### ISSUE THREAD

**Issue by MattRoop** [blasten/turn.js#12]
Hello, 

I have utilized your code found for turn.js and have a small question. Using JQuery UI tabs, I have a book on each tab on a single webpage. The issue comes when I load the page (which loads tab1), and I flip through book 1 on tab 1 from back to front, it starts to flip the other books on the other tabs forward. Is there a small programmatic change I could make to have the flipping of book 1 "forward" AND "backwards", NOT alter the page view of any other book?

TIA,
Mathias9999

**Comment by blasten** [comment]
Yes, there was a bug, but It's fixed. You have to re-download turn.js from 
http://turnjs.com/turn.js or http://turnjs.com/turn.min.js

**Comment by MattRoop** [comment]
Thank you blasten. I am still editing a bunch of code but as soon as I can get the site up and running, I will send you a link. :)

thanks!
Mathias9999
