### ISSUE TITLE
HTML 4 Flip in Single Mode

### ISSUE THREAD

**Issue by Annodyne** [blasten/turn.js#121]
When I click the sides in single view using the html 4 version, the page flip is unidirectional.  It only moves forward through the book regardless of which side I click.  I've also had problems (in single view) with entering the page numbers manually with the query string.  Sometimes it doesn't not flip to the right page specified.

Double view seems to be working though.

**Comment by blasten** [comment]
I'll check that out today

**Comment by nordyke** [comment]
Any update on this issue?  I'm also also experiencing it for single-page view.

**Comment by blasten** [comment]
I'd like to know if you both are using 4.0.8, because this issue was solved in that release.

**Comment by Annodyne** [comment]
Looks like I'm on 4.0.6.  I've updated to 4.0.8 and everything appears to be working now.  Thanks!
