### ISSUE TITLE
Zoom not working in IE8

### ISSUE THREAD

**Issue by zoee** [blasten/turn.js#122]
Hi there, I can't get the Zoom to work on your samples http://www.turnjs.com/#samples/magazine1 or on the version I have installed at ***

Your websites says you support IE8... is there a way to fix this issue?

Thanks,

Zoe

**Comment by blasten** [comment]
@zoe, it's working. but instead of one click or tap you have to double click or double tap.  If you want to change that, please replace `doubleTap` by `tap` in your code.

**Comment by zoee** [comment]
Hi. I re-tested and your sample now seems to zoom when double clicking, however mine still doesn't - I used the magazine code included in the zip, are you able to tell why zoom isn't working in IE8 please?

**Comment by blasten** [comment]
@zoee  could you send me an email?

**Comment by zoee** [comment]
Have emailed your to your gmail address :)
