### ISSUE TITLE
TurnJsError: disabled is not a method

### ISSUE THREAD

**Issue by nordyke** [blasten/turn.js#123]
When I try to access `disabled` property, I get the console error 'TurnJsError: disabled is not a method'.

`$('#pages').turn('disabled');`

I'm using 4.0.8, and I was not able to find `disabled` in the code.

**Comment by blasten** [comment]
@nordyke It was my mistake. Sorry, I will fixed in 4.0.9

**Comment by blasten** [comment]
@nordyke this is the code, it could be added after the `disable` method in line 914

``` javascript

// Disables and enables the effect

    disabled: function(disable) {

        if (disable===undefined) {
            return this.data().disabled;
        } else {
            return this.turn('disable', disable);
        }

    }
```

**Comment by blasten** [comment]
This problem was solved in the last update of turn.js you should receive an email shortly.
