### ISSUE TITLE
Thumbnails not appearing on initial load

### ISSUE THREAD

**Issue by KarahJane** [blasten/turn.js#124]
Hi there. Using turn.js 4. Have copied the magazine sample and for some reason the thumbnails are not appearing below the flipbook on load. They only appear when I resize the window or after I've zoomed in and then zoomed back out again. Only seems to happen on firefox 14.0.1 and Chrome 20. Any ideas? Thanks.

**Comment by blasten** [comment]
It might be because they are hidden. The thumbnails are hidden when the size of the window isn't big enough to show them on the screen.  But it's possible to change.

**Comment by KarahJane** [comment]
Thanks so much for your response, but I am still getting this issue and there is definitely enough room on the screen for the thumbnails. I would appreciate any further thoughts you had on this. Thanks.

**Comment by blasten** [comment]
@KarahJane could you send me an email?
