### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by samuelresua** [blasten/turn.js#128]
Hi Guys - I'm trying to add links which will take you straight to a specific page. i have to admit i'm very new to all this so im struggling to get to grips with it. 

i have come across this bit of code but i need to know how to use it as a link.

$("#flipbook").turn("page", 10);

**Comment by samuelresua** [comment]
Thank you! :)

**Comment by samuelresua** [comment]
Sorry one last thing! - Is it possible to assign a particular page an ID to link to ?  Instead of going to the page number? 

Thanks again! :)

**Comment by blasten** [comment]
Yes.  But you must have to add the "fixed" class to all the pages, otherwise some pages will not be available.

HTML:

``` html
<div id="flipbook">
 <div id="page1" class="fixed"> </div>
 <div id="page2" class="fixed"> </div>
</div>  
```

JavaScript:

``` javascript
function goToPage(id) {

   var currentPage;

   if ((currentPage = /\bp([0-9]+)\b/.exec($(id).attr('class')))) {
      $("#flipbook").turn("page", parseInt(currentPage[1], 10));
   }

}
```

**Comment by samuelresua** [comment]
So if I give one of my pages the ID 'Home' and want my link to always go to this particular page even if the page number changes? Sorry if this is annoying for you but it would be a grey help!

**Comment by blasten** [comment]
Yes, it'll work. I recently change the code I wrote above.

**Comment by samuelresua** [comment]
Sorry for being an idiot Emmanuel! I love this plug-in but like i said i'm pretty new to all of this web stuff!

As a very basic example - What do i need to change in my code for it to take me to ID Home?

<a href="#" id="home">Home</a>
<a href="#" id="home">About</a>

<div id="flipbook">
     <div id="Home" class="fixed"> </div>
     <div id="About" class="fixed"> </div>
</div> 


<script type="text/javascript"> 

function goToPage() {

   var currentPage;

   if ((currentPage = /\bp([0-9]+)\b/.exec($(id).attr('class')))) {
      $("#flipbook").turn("page", parseInt(currentPage[1], 10));
   }

}
</script>


Sorrrryy! :(

**Comment by samuelresua** [comment]
Could somebody give me an example of how to link to a page ID of #Home for example?  An example of the a, div (page) and JavaScript would be fantastic!

**Comment by blasten** [comment]
@samuelresua 

``` html
<a id="link-page-1">Home</a>
<a id="link-page-5">About</a>
```

JavaScript:

``` javascript
$("link-page-1").click(function() {
    $("#flipbook").turn("page", 1);
});

$("link-page-5").click(function() {
    $("#flipbook").turn("page", 5);
});
```

**Comment by samuelresua** [comment]
Okay but the page numbers of the pages I'm wanting to link to will change in future, so how can I like directly to the page Id and  ignore the page number?

**Comment by samuelresua** [comment]
I want to avoid using a counter if possible.
