### ISSUE TITLE
Thumbnail images position

### ISSUE THREAD

**Issue by ChadCH** [blasten/turn.js#129]
I want the thumbnails to be present when a viewer views the page on  1344 x 756 resolution screen.
I cannot get it to remain there.  It always hides on me.  My page images are 800 x 400.
Any Ideas / suggestions?

**Comment by blasten** [comment]
Yes, it's because there's not enough space on the screen for the thumbnails.

**Comment by ChadCH** [comment]
So, I just have to make my page images smaller to allow the thumbnails to fit?
OK, I will give that a shot.
Thank you for your response :)

**Comment by blasten** [comment]
yes or make some changes to the code.
