### ISSUE TITLE
Single page flip

### ISSUE THREAD

**Issue by SripadRaj** [blasten/turn.js#13]
Hey there,
Is there single page flip available in the plugin just like the jflip plugin?

Thank you
Sripad

**Comment by blasten** [comment]
Sorry, that is not possible with turn.js yet.  It will be possible in the next version.

**Comment by agx9** [comment]
so  is it now available that single page flip ?

**Comment by blasten** [comment]
@xm-anurag  Yes, it's now possible.

**Comment by leopersaud** [comment]
I put my ebook online with page flipping with Responsive Flip. The double page viewing sucks on the ipad. Would turn js solve this problem. Make it single page viewing/flipping?

Heeelp

Newbee
