### ISSUE TITLE
Turnjs 4 - Regions not working in Chrome for Mac

### ISSUE THREAD

**Issue by tiarc** [blasten/turn.js#130]
I have regions working in all browsers apart from Chrome..?

**Comment by blasten** [comment]
Can you send me the link?

**Comment by tiarc** [comment]
You can replicate this issue using the magazine demo that you supply in the v4 package. I have tested on all browsers for Windows & Mac. The only browser where the regions don't show up is Chrome for Mac.

**Comment by tiarc** [comment]
Fixed - had to add some mime settings
