### ISSUE TITLE
own-size seams to break the book after 5 pages

### ISSUE THREAD

**Issue by mikebonds** [blasten/turn.js#133]
Not sure if it is gotcha with the own-size needs to be implemented, or if I am doing something wrong. Either way, using own size seams to prevent the book from showing more than 5 pages.

**Comment by blasten** [comment]
@mikebonds this issue was fixed in 4.0.9. You should receive an email shortly

**Comment by shipleyr** [comment]
I am using version 4.1.0 and am experiencing this issue. The changelog says the issue of pages being sized to 0x0px was fixed in 4.0.9 but I'm experiencing this. I'm using IE8. The book works in every other browser. The pages that get dynamically added to the DOM are sized to 0x0. Please help me!

**Comment by shipleyr** [comment]
@blasten Just to add to this I'm using the html4 version of the library. Also if I load the html4 version into say the most recent version of Chrome I get the same behaviour. It's definately a bug in the html4 version of the library.

**Comment by shipleyr** [comment]
@blasten Even more update... it works if you put the styles directly on the "own-size" classed page but it doesn't work when they are defined in CSS. That makes it very horrible to have to put sizes of elements in both CSS and the inline style attribute. Hopefully this will give you enough to fix the problem and provide an update.
