### ISSUE TITLE
Zooming out of the picture blocks the turning of page

### ISSUE THREAD

**Issue by michalhudecek** [blasten/turn.js#134]
Open SteveJobs sample and follow these steps in any browser (FF, IE9 or Opera) except Chrome.

1) Turn pages until you find a picture you can click on
2) Click on it (zoom in)
3) Click somewhere else to zoom out
4) Now you cannot turn the pages either with arrow keys or by clicking on the corners or any other links you might have on the web page itself

Any ideas how to fix it?

**Comment by closdesign** [comment]
Tested on FF 14.0.1 - Zoom worked.  Slightly jittery but worked.
Tested Page 11 on IE9  - Confirmed issue. Zooms into image but does not turn page after zoom out.  Seems that the turn functionality stops working.  

Seems to be the picture block functionality. Fix would be awesome.

**Comment by blasten** [comment]
I'll take a look at this issue today. I guess something was recently changed and it caused the problem.

**Comment by blasten** [comment]
This issue is confirmed. You should receive an email shortly

**Comment by blasten** [comment]
This issue was solved it. Please download the last update.

**Comment by closdesign** [comment]
You solved the zoom issue but it looks like it created another issue. 

If you use IE9 and zoom an image on a page that zooms in and out fine. But if you click the bottom corners to turn the pages, the pages have started turning 90 degrees and are starting to go out of order, and acting somewhat erratically. Very odd bug.
