### ISSUE TITLE
How to change the width of a clickable area on hard pages

### ISSUE THREAD

**Issue by michalhudecek** [blasten/turn.js#135]
Hard pages have a clickable area that is used to open or close the book. When I hover above the are, it shows a short animation of the hard page as if it was being opened a little bit. The question is how can I change the width of this area? I want to make it larger as my users are confused where exactly to click.

Thanks

**Comment by blasten** [comment]
@michalhudecek  Please find the line `103` of turn.js. 

``` javascript
  cornerSize: 100,
```

The **100** is the number of pixels from the edge of the page

**Comment by michalhudecek** [comment]
Thanks. But this influences all the pages, not only the hard ones. Can I set it separately?

**Comment by blasten** [comment]
Yes, it influences all the pages. Give me time and I'll separate it

**Comment by rctneil** [comment]
What can I use to make the width of the clickable area wider on hard pages without affecting inner pages?

**Comment by rctneil** [comment]
@blasten Any help with this? I really need to find a way to make the front cover of my book have a wider click target.
