### ISSUE TITLE
Steve Jobs sample and magazine sample 

### ISSUE THREAD

**Issue by closdesign** [blasten/turn.js#136]
Hello,

We just purchased and downloaded files from our purchase and were testing out the Steve Jobs example.  The example is loading the cover and the first 2 pages (which are images) but seems to not be loading the HTML pages.  I am testing it locally on my computer just running the HTML file directly in my Chrome browser. Tested in Firefox too, same issue.  Is there an issue with something I am doing?  I have had it up for about 5 minutes now and would have expected at least some of the pages to load.  I am just getting the loading graphics on all of the HTML pages.  Looks like it is loading Thumbnail views in the slider, but it is not loading in the main flipbook view.

Also on the Magazine sample on my local version, does not seem like the regions are working either like your example on your website.  Is there a reason for this?

Any suggestions?

**Comment by blasten** [comment]
Yes, you cannot see the samples if you open the files directly with a browser. Please put them in a webserver and access to the URL. Browsers have different restrictions when openning local files, one of them is that ajax requests are disabled.

**Comment by closdesign** [comment]
That was something I was not aware of or had slipped my mind. Thank you for the feedback.
