### ISSUE TITLE
double page on load?

### ISSUE THREAD

**Issue by jekelly90** [blasten/turn.js#140]
Hi Blasten!

Great plugin I must say!! Definitely going to use it in my latest project.

Just a quick question. I have the display set to double but on page load the book is closed therefore displaying just one page. Is there a way to display two pages on a page load so it gives the impression the book is already open? A bit like when you click on the books on the website and it automatically opens up both pages?

Thanks

**Comment by blasten** [comment]
@jekelly90  Yes, there's a way, these are the step to follow:
1. Set the page option to 2.

``` javascript
$("#flipbook").turn({page:2});
```
1. (Optional) Disable the action to turn to page 1.

``` javascript
 $("#flipbook").bind("turning", function(event, page) {
    if (page==1)
      event.preventDefault();
});
```

And 

``` javascript
 $("#flipbook").bind("start", function(event, pageObject) {
    if (pageObject.page==1)
      event.preventDefault();
});
```

**Comment by jekelly90** [comment]
cant seem to get it working. html is 

```
<div id="magazine">
<div style="background-image:url(pages/01.jpg);"></div>
<div style="background-image:url(pages/02.jpg);"></div>
<div style="background-image:url(pages/03.jpg);"></div>
<div style="background-image:url(pages/04.jpg);"></div>
<div style="background-image:url(pages/05.jpg);"></div>
<div style="background-image:url(pages/06.jpg);"></div>
```

</div>

javascript is 

$(window).ready(function() {
        $('#magazine').turn({page:2,  
                            display: 'double',
                            acceleration: true,
                            duration:2000,
                            autoCenter: true,
                            gradients: !$.isTouch,
                            elevation:1,
                            when: {
                                turned: function(e, page) {
                                    /_console.log('Current view: ', $(this).turn('view'));_/
                                }
                            }
                        });

```
$('#magazine').bind("turning", function(event, page) {
```

if (page==1)
  event.preventDefault();
});

 $("#magazine").bind("start", function(event, pageObject) {
    if (pageObject.page==1)
      event.preventDefault();
});

```
$(window).bind('keydown', function(e){

    if (e.keyCode==37)
        $('#magazine').turn('previous');
    else if (e.keyCode==39)
        $('#magazine').turn('next');

}); });
```

**Comment by jekelly90** [comment]
my mistake it does work. i was updating the wrong file lol. thank you so much for this plugin blasten! it is superb!!

**Comment by jekelly90** [comment]
sorry to bother again...the magazine displays two pages on page load which is great but if i cycle back to the first page it displays the front cover....how can i get it to always "stay open" and display two pages all the time? thanks

**Comment by lightmar** [comment]
I also join this question. Did you get and answer? "how can i get it to always "stay open" and display two pages all the time?"

**Comment by blasten** [comment]
@lightmar Please check out #138

**Comment by jdlx** [comment]
@blasten ..while your above code works around the problem, it's kind of clunky for a fairly simple and everyday task:

**Presenting something which is not a _book_ aka "has no covers" .. 
.. out of the box, doublepaged, without jumping hoops.**

( _the page logic awkwardness goes even further once one has a numbered pager.._)
So if i may suggest: how about a flag - something like `hasCovers: BOOL // default: true`  - which _internally_ switches turn's logic from "book with covers" to "some kind of presentation without"?

**Comment by Mrinmay-wgt** [comment]
@blasten you are awesome ....
