### ISSUE TITLE
animate autoCenter

### ISSUE THREAD

**Issue by rrrus** [blasten/turn.js#141]
Perhaps add an option/property for animating the autoCenter feature that specifies a jQuery animation time, or hell, if the autoCenter option is a string or number, treat it as a jQuery animation time.

**Comment by michalhudecek** [comment]
Voting for this feature too.

**Comment by blasten** [comment]
Please check this out: http://turnjs.com/docs/Option:_autoCenter

**Comment by michalhudecek** [comment]
No it's something different. When you use option autoCenter it animates nicely when you open or close the book.

But the animation doesn't work when using:

``` javascript
$('.sj-book').turn('center');
```

**Comment by blasten** [comment]
@michalhudecek  That sample has the transition added to a class named .animated that is added and removed from the flipbook in certain occasions. That might be the issue, if the animated class isn't added to flipbook, it won't have transition.
