### ISSUE TITLE
Peel corner animation blocks clicks

### ISSUE THREAD

**Issue by michalhudecek** [blasten/turn.js#142]
Whenever I hover over the corner I need to wait until the animation finishes  to be able to click anywhere inside the page.

**Comment by blasten** [comment]
What browser are you using?  It shouldn't as this was an issue a long time ago and was already fixed.

**Comment by michalhudecek** [comment]
In Chrome, FF and IE. Try it on table of contents. Whenever you hover over the corner you need to wait until the animation finishes to be able to click on a link.

**Comment by blasten** [comment]
I cannot reproduce the issue you had. It works fine to me.  The peeling corner runs in a layer that has `pointer-events:none`

**Comment by michalhudecek** [comment]
You are right. It is working in your original code. Sorry to bother you. I have probably mess it up with this fix: https://github.com/blasten/turn.js/issues/37

Any ideas for a better fix?

**Comment by michalhudecek** [comment]
You can close this issue. This is just a bug due my changes to the code.

**Comment by blasten** [comment]
@michalhudecek Great!
