### ISSUE TITLE
Zoom Scrolling Work in Browser != Firefox?

### ISSUE THREAD

**Issue by ryHollingsworth** [blasten/turn.js#144]
I'm using the zoom feature out of the box as it's used in the steve-jobs example and if i zoom an image that's say the size of a 11x17 print piece of paper i can scroll up/down with Firefox, but not any other browser. 

Just curious if anyone else has used the zoom feature at all, and if so have maybe had the ability to move around the zoomed image. My execution goal: have a thumbnail and zoom into the full image and then be able to pan up and down to view the entire image. (currently it scales to fit width of the window and centers the image vertically.)

I'm going to jump back into the js for a bit, but i'm not as experienced with js as I hope to soon be :) 

Thanks guys!

**Comment by blasten** [comment]
The intention was to zoom in and see the image instead of the whole book. That's why the scroll is disabled.  Let me think how would fit what you pointed out.

**Comment by ryHollingsworth** [comment]
Thanks, today i'll tinker with the js used there. It's been way down on my to-do list and i'm finally getting to it haha. I may swap the zoom feature for a lightbox. Thanks again for such an awesome product!

**Comment by ryHollingsworth** [comment]
I'm not using the zoom feature that comes with turnjs as it was designed to be used so I have incorporated a lightbox overlay with scrolling. Therefore, I'll close this as it's not really an issue with the turnjs library. Thanks blasten, you rock!
