### ISSUE TITLE
Class of .hard randomly added, causing blank pages

### ISSUE THREAD

**Issue by devolved** [blasten/turn.js#146]
I've created a sizeable book (100 pages) and I've noticed that occasionally a blank page is created instead of appending the desired content.

On further inspection I've found that these blank pages have had a class of .hard added to them, which isn't part of my markup/scripts.

A refresh usually sorts it, but it could then re-occur to another page.

My loading function is only a temp one with no error checking, I've not looked in to a fix yet and as it's randomly occurring with consistent markup I have no idea as to the cause [he said helpfully],

but I thought I'd flag it up to see if anyone else has had this issue or you might know how I'm inducing it myself.

loader code below, 
- .section is the name of my "pages"
- my index file contains empty sections marked withpage numbers

HTML
e.g.
    <div id="flipbook">
        <div class="section hard p1"></div>
        <div class="section hard p2"></div>
        <div class="section p3"></div>
        <div class="section p4"></div>
        <div class="section p5"></div>
etc.

JS
/\* load pages */

```
var pageToAdd = 1;
var maxPages = 97; // * IMPORTANT * must set length of book here

// create empty book of [maxPages] length
$('#flipbook').turn({pages: maxPages});

$('body').append('<div id="loader"></div>');
var loader = $('#loader');

while(pageToAdd <= maxPages)
{
    loader.load(pageToAdd + '.html .section', function() {
        element = $('#loader').html();
        $('.p' + pageToAdd).replaceWith(element);
        $('#flipbook').turn('addPage', element, pageToAdd);
        loader.empty();     
    });
pageToAdd++;            
}
```

**Comment by devolved** [comment]
HTML 
div class="section p3"></div

**Comment by blasten** [comment]
Turn.js never adds the class **hard** to any page. It would be helpful if you can attach the entire HTML, including #flipbook

**Comment by devolved** [comment]
I'll email it to you if that's ok?

Have tried removing any hard covers but it didn't seem to help, still have a few pages created blank though no .hard was added in these cases.

**Comment by blasten** [comment]
please do it

**Comment by blasten** [comment]
I've looked in detail at the JS snippet you attached above and the first thing coming out is that you are calling an Ajax that isn't immediately returned and then reading `pageToAdd`, meaning that `pageToAdd` will always have the same value.  So you are replacing the same page all the time, which is the last page **97** and according to the HTML that page has a `.hard` class. In conclusion, If the pages are already in the HTML, you don't have to use `addPage`.  Please use `addPage` when your flipbook is empty or does not have that particular page.

**Comment by devolved** [comment]
Ah cool, thanks for that. I figured my shoddy load would be at least partly to blame but I thought as the "class addition" was a bit odd, it was bringing to your attention.
