### ISSUE TITLE
Try sj & Html5

### ISSUE THREAD

**Issue by grHand** [blasten/turn.js#147]
Hello!I tried to test the same effects as steve jobs sample but the first page(.hard) and second page(.hard)  disappeared when the third page started .I set own-size for pages without p1,p2. How to do? 
The code:

<div id="content">
        <div id="flipbook">
                <div class="hard"></div> 
            <div class="hard fixed"></div>
            <div class="own-size"></div>
                <div class="own-size"></div>
                <div class="own-size"></div>
                <div class="own-size"></div>
                <div class="own-size"></div>
                <div class="own-size"></div>
                <div class="own-size"></div>
                <div class="own-size"></div>
                <div class="hard fixed"></div> 
            <div class="hard"></div>
            </div>
</div>

The page 2 is fixed but it always show when the page loaded!
The page 11 has the same problem!

**Comment by blasten** [comment]
@grHand What does the HTML code look like?

**Comment by grHand** [comment]
```
    <div id="content">
    <div id="flipbook">
            <div class="hard"></div> 
        <div class="hard fixed"></div>
                        <div class="own-size"></div>
                            <div class="own-size"></div>
                            <div class="own-size"></div>
                             <div class="own-size"></div>
                              <div class="own-size"></div>
                             <div class="own-size"></div>
                             <div class="own-size"></div>
                             <div class="own-size"></div>
            <div class="hard fixed"></div> 
        <div class="hard"></div>
        </div>
   </div>
    <script src="../jquery.js"></script>
    <script src="turn.min.js"></script>
    <script>
        $(function(){
            $("#flipbook").turn({
                width:1000,
                height:600,
                autoCenter:true
            });
        })
    </script>
```

I just want to realise the same effects as the demos Steve Jobs.

**Comment by blasten** [comment]
The `.fixed` class should be used only to keep the cover visible if the pages with `.own-size` are smaller, otherwise it will disappear because turn.js will think that it's not visible for the user. Therefore, `.fixed` should be dynamically assigned when the following condition is true, `2 < $("#flipbook").turn("page") < $("#flipbook").turn("pages") -1` This behavior should be defined within the `turning` event.

**Comment by grHand** [comment]
Can you show me a  completed example?

**Comment by blasten** [comment]
``` javascript

$('#flipbook').bind('turning', function(event, page, view) { 

if (page>=2)
  $('#flipbook .p2').addClass('fixed');
else
  $('#flipbook .p2').removeClass('fixed');

if (page<$(this).turn('pages'))
  $('#flipbook .p11').addClass('fixed');
else
  $('#flipbook .p11').removeClass('fixed');

});
```
