### ISSUE TITLE
Turns on display odd pages

### ISSUE THREAD

**Issue by postonoh** [blasten/turn.js#150]
My next button only show odd pages and if I click the previous button it go back one page:

Example: starting page 1 click next 3, 5 go to previous page 4 appears then next 6, 8 back 7 next 9

How do I fixed this.

**Comment by blasten** [comment]
Please make use of the `next` and `previous` methods. These methods handle everything for you.

**Comment by postonoh** [comment]
I am using them.

$("#prvPg").click(function () {
                $("#mybook").turn('previous');
            });
            $("#nextPg").click(function () {
                $("#mybook").turn('next');
            });
Everything I am doing is dynamic. I am loading images base on clientId and bookId.

**Comment by blasten** [comment]
There shouldn't be any problem. The `next` method turns the page to the next view instead of the next page. `previous` works in the exact same way.

**Comment by postonoh** [comment]
The swipe work perfectly. 

http://www.agflipbooks.com/books/tabletbook.aspx?bookid=96

I have < for previous and > for next at the top of the window. 
This is where my number are starting page 1 click next 3, 5 go to previous page 4 appears then next 6, 8 back 7 next 9.

this is in single display.

Awesome product by the way.

**Comment by postonoh** [comment]
Ok, I see a difference in the code for swipe I have this.   

```
 $(document).bind("zoom.swipeleft", function (e) {
        $("#mybook").turn('next');
    });
    $(document).bind("zoom.swiperight", function (e) {
        $("#mybook").turn('previous');
    });
```

Which give me the desired what I want. 

But with the next> <previous I have this.

```
      $("#nextPg").click(function () {
             $("#mybook").turn('next');
        });

        $("#prvPg").click(function () {
            $("#mybook").turn('previous');
        });
```

I need the same effect as the swipe

**Comment by postonoh** [comment]
Problem is resolved.

**Comment by blasten** [comment]
Great!
