### ISSUE TITLE
Table Of content and pagination?

### ISSUE THREAD

**Issue by ghost** [blasten/turn.js#156]
Is it possible to create a table of content using this plugin? If so how would I go about doing that?

Are their options to create a pagination to flip the pages base from the dots pagination?

Thanks,

**Comment by closdesign** [comment]
I would assume all are possible but not built in.  The dot's pagination would be a simple look at the code thumbnails and replacing the thumbnails with the dots using jQuery.  Are you using the purchased 4.0 version?  or 3.0.  Conversion to the dots would be relatively easy.

**Comment by ryHollingsworth** [comment]
the version i'm using has multiple tables of contents using php and ajax to dynamically create all the pages and contents pages on the fly so yes it's possible if you make it work. (using v4)

**Comment by ghost** [comment]
How would I do the linking to that specific page? I am using the purchased 4.0

**Comment by blasten** [comment]
@CodeMan You just have to add a regular link, providing there's another part taking care of the URI hash once changed.  Turn.js includes Hash.

HTML within the page:

``` html
<a href="#pages/2">Go to page 2</a>
```

JavaScript within a script tag

``` javascript
Hash.on('^page\/([0-9]*)$', {
  yep: function(path, parts) {
    var page = parts[1];

    if (page!==undefined) {
      if ($('#flipbook').turn('is'))
        $('#flipbook').turn('page', page);
    }
  },
   nop: function(path) {
     if ($('#flipbook').turn('is'))
       $('#flipbook').turn('page', 1);
     }
});

```

**Comment by ghost** [comment]
Awesome thanks :)

**Comment by kadimi** [comment]
Hello, 

@blasten, I have the 4th release as well.. I get an error "Hash is not defined", where does the code you provided go exactly?

Thank you
- Edit: Nevermind, Hash was not included...
