### ISSUE TITLE
Last page flip issue.

### ISSUE THREAD

**Issue by ghost** [blasten/turn.js#160]
In the turn js demo present @ http://www.turnjs.com/#samples/magazine2/12

If i remove the last page i.e page number 10. And then, try it running with 9 pages. When you will reach to the last page, flip once and after that flip wont work.

**Comment by blasten** [comment]
I saw something going on, it might be because a recent change.

**Comment by blasten** [comment]
@durgeshp The problem was solved. Please send me an email so I can send you the link to update.
