### ISSUE TITLE
How to stop turn from right to left.

### ISSUE THREAD

**Issue by vadherdhaval** [blasten/turn.js#162]
When I reach at the end of the document and last page is on right side. After that there is no more page so I want to disable turn on right side to left side. Currently when I mouse over on the br corner on the last page after that I can't turn page from left to right.

**Comment by blasten** [comment]
How many pages does your magazine have?

**Comment by vadherdhaval** [comment]
I have 3 pages in my magazine.

**Comment by blasten** [comment]
@vadherdhaval The problem was solved. Please send me an email so I can send you the link to update.

**Comment by vadherdhaval** [comment]
Hi Blasten, 

vadher.dhaval@gmail.com is my email id. So if you find out the solution than please mail me on this id.

Thanks
Dhaval

**Comment by andrewmartin** [comment]
@blasten I was wondering, is it possible to disable the next/previous page click effect altogether? I've done quite a bit of research and am coming up empty. We are using next/previous buttons to move the page from left to right.

**Comment by vadherdhaval** [comment]
@blasten I have another problem for fliping the page. When I click continuously on the corner of the page it flip the pages very fast. And my content is loaded base on current viewed page so when I click continuously then data is not coming from the server because when sending the server request for next page the data is going blank or undefined so I didn't get anything in response and all the pages are blank with spinner. So is there anyway to stop clicking on corners?
