### ISSUE TITLE
Not a real issue a question

### ISSUE THREAD

**Issue by postonoh** [blasten/turn.js#164]
In your samples the magazine. I don't see the path to your images.

I am doing a demo using Turnsjs to show my boss.

Right now we are using built by will jquery Booklet

http://builtbywill.com/code/booklet/

this is my site.
www.agflipbooks.com/books/book.aspx?bookid=149

I am using asp.net C# and jquery css/

Working to convert to turnjs.

My code behind is dynamically loading images.

**Comment by blasten** [comment]
Here it's http://www.turnjs.com/samples/magazine2/pages/10.jpg
