### ISSUE TITLE
Flipbook on load shows up in wrong location?

### ISSUE THREAD

**Issue by ryHollingsworth** [blasten/turn.js#169]
This isn't a huge huge deal, and I don't know how to reproduce the problem, but since I just watched someone load my flipbook on a computer that had never loaded it before I figured I'd ask the question. 

Occasionally the flipbook will not load where it's position to load, but in the top right corner showing you only the bottom half of the flipbook. Has anyone else encountered this? I thought it was simply due to cache issues, but since it happened on first load on a coworkers computer it gave me a little pause. 

If no one else has this problem i'll write it off as my execution as it's a little obnoxious. I'm linked to a database, using ajax and php to dynamically create the pages and handle content.. here's my test link if you wanna see it. http://magnus.linuxboxes.net/~djl001/  if you hit refresh over and over it will eventually load incorrectly. 

Thanks guys, and thanks blasten for such an awesome tool!

**Comment by blasten** [comment]
This problem was solved in 4.0.9. You are using 4.0.8. If you don't know how to update to the last version, please send me an email.

**Comment by ryHollingsworth** [comment]
Thanks. I'll update it!
