### ISSUE TITLE
Page Transitioning

### ISSUE THREAD

**Issue by postonoh** [blasten/turn.js#173]
I am using this on a iPad Demo. With swipe next method after 5 swipes it  skip a page 6 and go to 7. I  swipe back to two previous pages and swipe again then page 6 show up.

**Comment by blasten** [comment]
What version of turn.js are you using?

**Comment by ryHollingsworth** [comment]
I'll link you to my swipe JavaScript tomorrow when I get back to the office. Maybe it'll help. How's your responsive layout for iPad coming? I've been forced to put mine on hold :( good luck!

**Comment by postonoh** [comment]
I believe I download a copy of version 3 and 4

**Comment by blasten** [comment]
There was recently fixed an issue that might be related to this one. Please send me an email, so I can resend you the download link.
