### ISSUE TITLE
Resize bug while turning page on Safari / iPad2 with the Steve Jobs Demo

### ISSUE THREAD

**Issue by haywoood** [blasten/turn.js#174]
Hello, I purchased a license and with that came a samples repo. I am creating a book  based off the Steve Jobs project, and when I turn a page the whole book scales down while animating and then when it's complete it scales back to the desired size. I tested this on the sample that came with the files and it happens there as well.

If I go to the turn.js website and view the book there nothing odd happens. Any idea what could be causing this?

Thanks,
-haywood

**Comment by blasten** [comment]
I checked it, but I didn't see any issue. What version of turn.js are you using? is it 4.0.9?

**Comment by haywoood** [comment]
Yea, 4.0.9. I have the samples folder hosted on a personal server that I was using it to test -- do you want me to link you to that? It happens in landscape mode.

**Comment by blasten** [comment]
@lsdafjklsd  please.

**Comment by haywoood** [comment]
@blasten here you go: http://mreach-art.com/ThermoFisher/test/samples/steve-jobs/

**Comment by haywoood** [comment]
Solved, it. After adding this bit of code to the head of the page
`<meta name="viewport" content="width=device-width, initial-scale=1">` 
the jumping stopped.
