### ISSUE TITLE
Using TurnJS with FileAPI -- causes TurnJS not to work very well

### ISSUE THREAD

**Issue by simkimsia** [blasten/turn.js#175]
I have two examples here:

1) using turnjs with FileAPI

the code is listed in this gist.

https://gist.github.com/3754199
The youtube video example of how I used it is here http://www.youtube.com/watch?v=R9jUWrayEtI

You will notice that the flip effect did not work well in Firefox or does not work at all in Chrome.

2) using turnjs without File API

the code is listed in this gist.

https://gist.github.com/3754209
The youtube video example of how I used it is here http://www.youtube.com/watch?v=dqD4u5ECaaE

You will notice that the flip effect works very well when I used prepared images instead of the dataurl from html5 File API.

My question is how do I make TurnJS play nice with FileAPI?

**Comment by blasten** [comment]
@simkimsia Can you please send me the link that uses the FileAPI?

**Comment by simkimsia** [comment]
Hi Emmanuel, 

I am not sure what do you mean by the link that uses the FileAPI?

I think you meant the code I did:

the code is listed in this gist.

https://gist.github.com/3754199
The youtube video example of how I used it is here http://www.youtube.com/watch?v=R9jUWrayEtI

You will notice that the flip effect did not work well in Firefox or does not work at all in Chrome.

If you mean the tutorial I found online, I think you meant this

http://www.html5rocks.com/en/tutorials/dnd/basics/

**Comment by blasten** [comment]
@simkimsia  Sorry, I meant your app.

**Comment by simkimsia** [comment]
It is on a private repo.

http://turnjswithfileapi.storyzer.cloudcontrolled.com/page1and2.php

**Comment by blasten** [comment]
I've prepared this fiddle: http://jsfiddle.net/blasten/KL9PF/  

To accomplish I had to insert a temporary page, because the current version of turn.js requires at least one page within the book.

**Comment by simkimsia** [comment]
Thank you for your response Emmanuel.

The fiddle helped me to get some basic functions working, but there are 2 issues that are turnjs related.

1) When I dropped just 1 image, the flipbook does not reflect the single image

2) when I dropped an odd number of images, eg 3 when I attempt to flip the last page, I get this error.
Uncaught TurnJsError: "4" is not a page for range

if i dropped 5 i get
Uncaught TurnJsError: "6" is not a page for range

this is my gist
https://gist.github.com/3768823

it requires the followng javascript and no css

<script type="text/javascript" src="../../extras/jquery.min.1.7.js"></script>

```
    <script type="text/javascript" src="../../extras/jquery-ui-1.8.20.custom.min.js"></script>
    <script type="text/javascript" src="../../extras/jquery.mousewheel.min.js"></script>
    <script type="text/javascript" src="../../extras/modernizr.2.5.3.min.js"></script>
```

yep: ['../../lib/turn.min.js'],
            nope: ['../../lib/turn.html4.min.js'],

**Comment by simkimsia** [comment]
Hi Emmanuel, 

we have come up with a workaround on our end. Not perfect, but good enough for us.

We will restrict users not to use turnjs when less than 2 pages and when the pages are odd numbered.

Basically something like 

```
          function previewBook() {
        var book = $("#flipbook");
        var pages = book.turn("pages"); 

        var pagesEvenNumber = (pages % 2 == 0);
        var pagesMin2 = (pages >= 2);
        var showBook = pagesEvenNumber && pagesMin2;

        if (showBook) {
            book.show();
        }
        if (pagesMin2 == false) {
            book.hide();
            alert("You do not have at least 2 pages");
        }
        else if (pagesEvenNumber == false) {
            book.hide();
            alert("You do not have even number of pages");
        }

    }
```

I am not sure whether you want to close this issue, but for us, we need to quickly move onto other important issues in our own development.

**Comment by blasten** [comment]
@simkimsia I think you right, that is how it should be. Because I cannot think about a magazine with no backside. Indeed, Every page must have a backside. Another option can be to fill up the book with temporary pages which can have a watermark.
