### ISSUE TITLE
Slideshow conflicting with turn js

### ISSUE THREAD

**Issue by ghost** [blasten/turn.js#177]
I am using a slideshow flexslider by wootheme for this book I am working on, and the buttons controls are being intercepted by turn.js. How can I have turnjs not conflict with the flexslider? I tried the not() in the turn function but that didn't work.

CodeMan

**Comment by blasten** [comment]
Does it turn the page when clicking the buttons?

**Comment by ghost** [comment]
yeah it does change the page. The link of those arrows and pagination is set to href="#".

**Comment by blasten** [comment]
That might be going on. if turn.js is listening to changes of the hash, an empty hash is assumed as the first page/.  Does it always turn to the first page?

**Comment by ghost** [comment]
Yeah and at some pointer i can't even click on the pagination itself, not clickable.

**Comment by blasten** [comment]
What about if you remove the href="#"?

**Comment by ghost** [comment]
That is all generated on the fly from the js plugin.

**Comment by ghost** [comment]
Any idea on how I can overcome this? 

I am using the v4 of turnjs

**Comment by ghost** [comment]
So I put this flexslider in the turned callback and had it turn on once and everything started to work.

CodeMan
