### ISSUE TITLE
how to write code to get you to last page.

### ISSUE THREAD

**Issue by postonoh** [blasten/turn.js#178]
I now to get the first page is 
$(".mag').turn('page' , 1);

how do you write the code how to reach that last page if the book pages that are being loaded is dynamic.

**Comment by blasten** [comment]
``` javascript
$(".mag").turn("page" , $(".mag").turn("pages"));
```

**Comment by postonoh** [comment]
I am not using release four testing with release 3

**Comment by blasten** [comment]
You can use it in both versions.
