### ISSUE TITLE
set rigidity effect page

### ISSUE THREAD

**Issue by totilapi** [blasten/turn.js#18]
Is possible set rigidity effect page?

**Comment by blasten** [comment]
Not yet, but very soon.

**Comment by jedahan** [comment]
It would be great to have a rigid page turn like in http://tympanus.net/codrops/2012/05/07/experimental-page-layout-inspired-by-flipboard/ .

**Comment by blasten** [comment]
@jedahan The new version is coming and it is already done, it includes a rigid or hard page turn, allows pages of different sizes, native center option, and more...   By using only rigid pages, you get the effect as in flipboard.
