### ISSUE TITLE
Custom links being overriden 

### ISSUE THREAD

**Issue by ghost** [blasten/turn.js#180]
Hello,

I have some links that are being use for prettyPhoto (http://www.no-margin-for-errors.com/projects/prettyphoto-jquery-lightbox-clone/) and the issue I am coming across is that when I click on that link it automatically shows the prettyPhoto(Overlay with content) but then sends the pages to the cover page. How can I stop that from going to that cover page?

CodeMan

**Comment by blasten** [comment]
Is it possible to see it?

**Comment by ghost** [comment]
I sent you the email with the files.

Thanks
