### ISSUE TITLE
Strange Transitions when deployed to Andriod via PhoneGap

### ISSUE THREAD

**Issue by Cleanshooter** [blasten/turn.js#183]
I have recently used your open source version (version 3 I think) to test out a page turning app.  It works fie on my iOS simulator but when I deploy it to my Android Phone (in USB debug mode) the page transitions look very strange.  

It looks like it quick shows the next image the one the new one jumps over the new one.  (If that makes any sense).  Since I don't have another project that are really pressing right now I think I just see what I can do to fix it.  I'll post any code ideas/fixes that help here.

**Comment by blasten** [comment]
Ok, I recently figured out what was going on in the default browser, so the next update of turn.js will support android's default browser. I believe I should also update 3rd release ;)

**Comment by tkempf** [comment]
Hi Emmanuel,
did you already fix the Android default Browser issues? If so, when will you release the update for v4.0.9?
Kind regards
Tom

**Comment by blasten** [comment]
@tkempf It's already available. http://turnjs.com/docs/Changelog

**Comment by tkempf** [comment]
Ah,
i haven't seen that. 
Thankyou
Tom
