### ISSUE TITLE
removePage does not work.

### ISSUE THREAD

**Issue by hallikdog** [blasten/turn.js#188]
I'm trying to dynamically remove a single page from my flipbook but get a error in the process.

$("#pages").turn("removePage", 1);
TypeError: Cannot read property '1' of undefined

I've also tried it at the steve jobs example which gives the same error.

At last i added some console.log functions to the turn.js and it appears the this.data() returns undefined.

Does anyone know what might be wrong?

**Comment by blasten** [comment]
@hallikdog this problem was recently solved. What version are you using?

**Comment by hallikdog** [comment]
@Blasten I've only bought and downloaded it today so i think it was the latest. Let me check. It is 4.0.9.

**Comment by blasten** [comment]
`$(".sj-book").turn("removePage", 1);`

I have tried it on turnjs.com with the steve jobs book opened and no problem.
Could you please redownload turn.js?

**Comment by hallikdog** [comment]
I appears to be working now, although it does screw up some positioning. nothing i can't fix. thanks
