### ISSUE TITLE
Each div of my book is two pages. Is it possible to modify TurnJS like this?

### ISSUE THREAD

**Issue by lightmar** [blasten/turn.js#189]
Hello,

Thank you for this great script.
I have a book app working currently with no Flip effect. 
My book is designed that way that it starts opened, and each div actually displays two pages. Each div has it's own background that looks like opened book... Etc.

My question is - it is possible to modify the script and use TurnJS this way? Somehow tell the script where is the middle point and that it will consider the left part as one page, and the right as another?

Thanks.

**Comment by blasten** [comment]
Yes, using either 3rd or 4th release.  Have you checked out issue #138?
