### ISSUE TITLE
Trigger for the start and the end of the slide

### ISSUE THREAD

**Issue by cipnt** [blasten/turn.js#19]
Great script!
The hardware acceleration works wonderful on the iOS.
Maybe others will find useful a trigger for the start and the end of the slide/book/whatever to disable/hide the previous and next buttons if used. 
The single page flip is great new future and can't wait for the new version.
Thanks

**Comment by anherdene** [comment]
+1

**Comment by obsergiu** [comment]
me tooo +1

**Comment by blasten** [comment]
I agree, I think it's a cool idea!

**Comment by blasten** [comment]
@cipnt Turn.js now has the `first` and `last` event.
