### ISSUE TITLE
Page Images Not Loading After Page Turned x Amount of Times.

### ISSUE THREAD

**Issue by MeyrickJones** [blasten/turn.js#190]
I’ve just started using Turn.js version 4 using code based on your magazine sample but I am populating the page image source from a DB, unfortunately the image load fails consistently when I reach page 23 (when I start from page one and turn the pages).

If this is releated to the size of the data retained, your documentation mentions the ability to reduce the cache to release memory but I don't think it actually covers how to do this.

Hope you can help.

**Comment by blasten** [comment]
@MeyrickJones  I'd strongly recommend to use `addPage` to populate pages, instead of putting a bunch of HTML in the container of the flipbook. is this the case?

**Comment by MeyrickJones** [comment]
I am using addPage (as in the magazine sample you provide in the download) which holds the 6 pages in the DOM but also retains all the pages in the pageObjs, how do I destroy these as I think it is getting too large and preventing the pages from loading once there are too many i.e 23 page turns.

**Comment by blasten** [comment]
How many pages is it suppose to load? Are you using mobile Safari?

**Comment by MeyrickJones** [comment]
I have done a quick check and this is only happening when using IE9, it is loading in firefox, opera, chrome and safari, I have not tried it on a mobile platform yet.
This is currently only a prototype and has 32 pages, though I will be wanting it to work with books potentially with 10000 pages. Thusas well as this issue I would like to know how to reduce the cache to ensure it remains performant for larger books.

**Comment by MeyrickJones** [comment]
Clearing down the pageObjs has prevented the issue from occurring.
