### ISSUE TITLE
Last page flip does not work

### ISSUE THREAD

**Issue by lmak** [blasten/turn.js#191]
I have just downloaded the latest version 4.0.9. I created a book (display: single) with no covers. Everything works OK but when I reach the final page the flip does not show and I cannot return back.

**Comment by blasten** [comment]
@lmak are you using the option `pages` ?  Notice that most samples of turn.js use `pages`

**Comment by lmak** [comment]
I didn't but it does not make a difference. The flip does not work even when I am using the option `pages`.

If it helps, I implemented a slider similar to the "docs" example. If I use the slider to go back when I reach the last page, then if I return to the last page the flip works sometimes, not always.

**Comment by blasten** [comment]
@imak This issue was confirmed and it's already solved. Could you please download the update? You can use the same download link.

**Comment by lmak** [comment]
I confirm that the problem is solved. Thank you.
