### ISSUE TITLE
Three questions

### ISSUE THREAD

**Issue by entio** [blasten/turn.js#194]
Hi Blasten,
first of all congrats for such an amazing library; I've got couple of questions here;
1. Can You explain to me how the script does handle "depth" of currently turned page?
   Is it css's z-index or css3 transform-z? All i like to do here is to keep the regions at the top of the stack all the time (put them at the top immediately after releasing corner). What should i do?
2. Playing around with demos at your site with IE8 & IE9 does not showing regions (demo: magazine1) This is a little bit strange but running the magazine1 demo locally, from disk it works well. Regions and visible and clickable. The only error thrown by online version in ie is: error: CSS3114: @font-face failed OpenType embedding permission check. Permission must be Installable. DistTh___.ttf
   I believe it does have nothing to do with an issue.
3. Next question is somehow connected to previous both, It takes place at every browser at the zoom view. I move cursor up on the region and begin dragging. Afrer drag i release mouse button and page does stops but also it runs the actinon binded to the region. Is there any way to disable it? I mean to disable region action after dragging while it still would work on click or tap?

I am not posting a JSfiddle, cuz it's nothing to post

**Comment by blasten** [comment]
Hi!  Thanks.
1. If you are using the .hard class, yes it's using CSS transform and perspective.
2. That's weird, I saw a problem with regions on IE8.  This week should be fixed.
3. The first idea was to use CSS to hide the regions, but it turned out that a better idea would have been to keep the regions and ignore clicks or tap on them when dragging/dropping the page.  So you should expect this change in the next update.

**Comment by entio** [comment]
1) Actually, I am not using .hard cover.. But its no longer necessary for me;
2) It would be great, ie8 users are still quite a large part of the market. Luckily in Poland its only about 9 percent, anad i personally wouldn't give a damn about them..
3) That's nice, ill try to hide the regions at my own, thanks a loud!
