### ISSUE TITLE
How to load the book already opened?

### ISSUE THREAD

**Issue by lightmar** [blasten/turn.js#195]
Hi,

I would like to display a book in a way that it will look like it is already open.
Meaning, instead of displaying the pages like:
1
2-3
4-5

I would like to display it like:
1-2
3-4
5-6

I have tried to start the book in page 2, but the problem is that I am able to turn back to page 1 and I don't see any option to disable it.

Any help will be appreciated.

**Comment by entio** [comment]
How can that be? I've never seen a book with no cover in my life!

Only solution comes to my mind is to disable controls on your second page simply making the first one inaccesbile..

Searching through issues i found something You may be interested in
https://github.com/blasten/turn.js/issues/45

**Comment by blasten** [comment]
Yes, and also issue #138

**Comment by lightmar** [comment]
Of course it can be, in digital book everything is possible...
Adding the following did the job:

$("#content").bind("turning", function (event, page) {
                    if (page == 2)
                        event.preventDefault();
                });
                $("#content").bind("start", function (event, pageObject) {
                    if (pageObject.page == 2)
                        event.preventDefault();
                });

**Comment by blasten** [comment]
Great.
