### ISSUE TITLE
how to disable the flip function on the book itself? 

### ISSUE THREAD

**Issue by kat007** [blasten/turn.js#197]
I have a next/prev link above the book, and want to disable the flip function on the book itself. How can I do it?

**Comment by beckiechoi** [comment]
From what I know, easy way is just putting e.preventDefault() inside of the start function when setting the option, like here
when : {start : function(e) {e.preventDefault()} }

**Comment by blasten** [comment]
@kat007 absolutely. Another option can be `$("#flipbook").turn("disable", true);`
