### ISSUE TITLE
Cannot return to page 1

### ISSUE THREAD

**Issue by hallikdog** [blasten/turn.js#198]
I've originally used the non commercial version of turn js and have recently switched to the commercial (latest) version.
Every since however I've been expieriencing some problems.

We start at page 1, once turned forward it becomes impossible to return to page 1.
The turning event is triggered but the page never actually turns.
When pulling the page from the corner it is possible to see the first page but upon releasing it it quickly shoots back.

there are no javascript errors.

Please help.

**Comment by blasten** [comment]
@hallikdog That shouldn't happen. Are you using the single display? Do you have any preventDefault() in the turning event?

**Comment by hallikdog** [comment]
It appears that was the problem.
Thank you! =D
