### ISSUE TITLE
Not Working On Android

### ISSUE THREAD

**Issue by matthewrobertson** [blasten/turn.js#2]
I see you mentioned it works on mobile platforms, but the demo does not seem to be working on my Android phone:

Samsung Nexus S - Android v 2.3.6

Other than that, Nice work!

**Comment by blasten** [comment]
Hey, I'm going to check it out.
Thank you for let me know.

**Comment by cjb** [comment]
I just tried on a Motorola Xoom running ICS/Chrome, and it works (a bit slowly) for tap-to-advance, but not for touching and dragging the page.

**Comment by blasten** [comment]
It's good to know that. Removing the shadows {shadows:false} from the initial configuration would make the effect a lot faster. Are you testing with your own code or the example on turnjs.com?

**Comment by matthewrobertson** [comment]
I was testing the example on turnjs.com. But it wasn't a simple lagging issue the page turning animation was totally wrong. I spent some time messing around with it today, and there is no way to know for sure (I can't pop open an inspector on my phone) but from what I can see some of the css3 transformations were not having any effect. Anyone know what is the support for this on android?

**Comment by matthewrobertson** [comment]
I think [this might explain it](http://caniuse.com/#feat=transforms3d). Looks like 3d transforms are not supported on Android v <= 2.3 (this would agree with @cjb's observation that it is working on Ice Cream Sandwich).

I guess this means that you have all the tablets, but are missing most of the phones (I believe the large majority of android phones are ~2.2)

**Comment by sr-nu** [comment]
This is not working on Android ICS chrome browser as well, in the sense page turn is broken. Pages are randomly appearing outside the book.  (tried the example apps)

**Comment by blasten** [comment]
@srikanthNutigattu  I believe there should be an update to fix all the problem on android devices very soon.

**Comment by janebabra** [comment]
I have tested on tablet with Android 4.03 NOT WORKING

**Comment by blasten** [comment]
@janebabra  Is it using the default browser? The next update will extend the support to all android devices.

**Comment by bangyogesh** [comment]
I tried testing the sample on Android 2.3.3 within a PhoneGap based (WebView) application. I observed that EVENpages were loading before the ODD pages, the animation effect was messy (the content for odd page used to first come below the even page and then moved to odd page and the delay was noticeable).
