### ISSUE TITLE
Dynamic page generation

### ISSUE THREAD

**Issue by omsoft** [blasten/turn.js#200]
Hi there,
I have a CMS where users can upload images that will be displayed inside your FlipBook. These pages can be ordered dynamically. I see that pages are named by a number... but this cause a problem in my case... I want to name file differently and map them through their relative thumbs... How can I do?

Many thanks

**Comment by omsoft** [comment]
Problem solved by overwriting addPage() method with a custom logic!

**Comment by yovdesign** [comment]
please share!!
