### ISSUE TITLE
Problem with page order in IE8

### ISSUE THREAD

**Issue by kschwerdtfeger** [blasten/turn.js#202]
My page is located at http://lightsonthelake.org The user is supposed to be presented with our old logo with a little page curl teaser in the corner. Then they should be able to peel back the page to reveal our new logo.

This works beautifully in most browsers (Mozilla, Chrome, Safari), and it works well enough in IE9, but I have no idea what's going on in IE8. It appears to not be loading my pages in order. If anyone can take a gander and offer up any suggestions, I'd greatly appreciate it!

**Comment by blasten** [comment]
You haven't added the IE8 support yet.  Please look at the magazine sample to see how to handle the HTML4 support.

**Comment by kschwerdtfeger** [comment]
Ah, yes, it would help if I added HTML4 support. Thanks so much!
