### ISSUE TITLE
Classes

### ISSUE THREAD

**Issue by entio** [blasten/turn.js#205]
Hi there, i wonder i there's any way to add some classes to divs containing rotating pages and all the nodes which are unidentified for css styling by now.

I wanted to add 1px border around magazine and there's no way to do thar. It dissapears on corner hover; when started playing around with jq to select children of magazine with no class assigned there was a mess and resulted unpredictable effects.

**Comment by blasten** [comment]
@entio. One possibility is to insert a div inside a page with the following CSS:

``` css
box-sizing: border-box;
-webkit-box-sizing: border-box;
-moz-box-sizing: border-box;
-ms-box-sizing: border-box;
-o-box-sizing: border-box;
width:100%;
height:100%;
border:2px solid red;
```

and everything else should be inside this element.
