### ISSUE TITLE
All clicks stop working after page turn.

### ISSUE THREAD

**Issue by technica-creative** [blasten/turn.js#207]
I have a book with several pages of products. The problem I am having, and cannot solve, is that the clicks work on the first page, but, as soon as I turn more than 1 page, all links stops working.

Any items on pages after the first page will not work once the page has been turned. 

To check if this was an error on my end, I deleted everything in the book (including the FancyBox pop up) and put a few pages with a link on each page. If I only use a tags with a href then everything is working fine. But as soon as I try to capture the click events using jQuery, everything breaks.

I was able to catch the first page's click event using $(".navigation li a").click(function(){});..... and if i turn to page 2 and back, it still works. But if I turned the page to page 3 and then go back to the 1st page, all links on pages no longer work. jQuery no longer is able to catch the click events.

The strange thing is all hover effects and CSS is working fine on the links. Its just the click event that does not get tracked after the page turn in jQuery.

I have tried everything possible and went through all the issues here to try and find a solution but cannot. 

Can someone please make a suggestion or if anyone has ran into this issue, please provide a fix. I am using turn.js version 4.

Thanks

**Comment by entio** [comment]
I am just finishing an e-zine with modal windows (neither fancy nor 
lightbox one, my own) but have never came to such an issue. Maybe You 
can send or post some url, it would be easier to find a solution. What 
kindd of an error does it throw? Does the active regions (or do you have 
just anchor links?) show itself and do not run an action or they just 
stay hidden?

**Comment by entio** [comment]
Or provide jsfiddle working (not working actually) example ;-)

**Comment by technica-creative** [comment]
I stripped down the book I was working on to a horrible skeleton looking version. But it still has the same issues. Here is a link:

_removed link - issue solved_

You will notice that the links work when you open the book on Page 1 and Page 2 only. Then, after navigating through the book by either peeling pages back, or by using the navigation, all links stop working except on Page 2.

I was digging through the turn.js file in the project (turn.js version 4) and commented out the following methods:
_removePageFromDOM : function(page)
removePage : function(page)

After doing this, Page 1 and Page 2 will work, but I still cannot capture jQuery events on any other pages. I have no idea how to fix this. The book will eventually have 10-15 pages with products on all pages so all clickable items have to work.

In the link that I provided above, the methods in turn.js are not commented out. I put everything back to its original state.

I hope someone can help me figure this out. 

Thank you

**Comment by entio** [comment]
I have only checked provided link and... Flipbook is constructed to 
display contents of only six pages in dom (it have to display 3 if it's 
in single mode). Your problem lies in binding events to the links. You 
do it once and only at the beginning, so that contents of pages after 
2nd aren't in the DOM yet. Either You haveto use
$(".table_of_contents_navigation li a").live('click',function() instead 
of $(".table_of_contents_navigation li a").click(function()
or always bind the click to the content on turned event of magazine.

**Comment by technica-creative** [comment]
That worked perfectly and everything immediately started working when I changed the jQuery to use .live! I have been on this for 2 days straight. 

Thank you for the quick reply and fix!

**Comment by SdeGeata** [comment]
Any way to accomplish this with the Steve Jobs template? My clicks aren't registering either.

**Comment by TimOgilvy** [comment]
there are issues with the way events are bound - as turn.js rips pages out of the DOM when they are more than 6 pages out of scope. The previous answer using jQuery's Live event is now out of date...  the correct solution uses the jquery .on method 

http://api.jquery.com/on/

http://stackoverflow.com/questions/19032597/javascript-event-binding-persistence

**Comment by ramjamx** [comment]
Same problem here! 
I already tried to delegate the click event to a specific class, but it doesn't work al all.

``` javascript
$("#bxPortafolioPortada").on('click','div', function(event){
        var targetPage = $(this).attr("rel");
        console.log("go to: "+ targetPage);
        $("#flipbook").turn('page', targetPage);
});
```

If i Comment the $("flipbook") line the console log remains working, it's something about the .turn('page') function that stops the cuntionality.

My not-working example is here: http://dinamo.mx/D14B/#portafolio

**Comment by SdeGeata** [comment]
Actually, I have problems with the dead links on page 2 even, not pages more than 6 out of the dom. They only begin to work correctly after I go more than 6 pages out, then come back. Very odd.

}=={======>
From the Desk of Stiofán of the de Geata Clan.

Sword Swallower • Fire Eater • Deck Hand • Roustabout • Carpenter • Sculptor • Green Man • Mushroom Hunter • Brewer • Baker • Camel Whisperer • Psychonaut • Student of Life • Roaming Gnome

Montréal, Québec.
Stiofan.deGeata@gmail.com

This e-mail message (including attachments, if any) is intended for the use
of the individual or entity to which it is addressed and may contain
information that is privileged, proprietary , confidential and exempt from
disclosure. If you are not the intended recipient, you are notified that
any dissemination, distribution or copying of this communication is
strictly prohibited. If you have received this communication in error,

## please notify the sender and erase this e-mail message immediately.

Le présent message électronique (y compris les pièces qui y sont annexées,
le cas échéant) s'adresse au destinataire indiqué et peut contenir des
renseignements de caractère privé ou confidentiel. Si vous n'êtes pas le
destinataire de ce document, nous vous signalons qu'il est strictement
interdit de le diffuser, de le distribuer ou de le reproduire. Si ce
message vous a été transmis par erreur, veuillez en informer l'expéditeur
et le supprimer immédiatement.

**Comment by ramjamx** [comment]
Some other ways I tried to solve this is:

1 inline javascript
Adding inline javascript like <a href="javascript:$('#flipbook').turn('page',8)">link</a>
but that is not semantic and even worst doesn't works on firefox.

2 jquery id 
I just add some ids to listen to the click on them like

$("#btnBang").on("click", function(e){e.preventDefault();$("#flipbook").turn("page", 2);})

It works just the first time, but after that when i return to the index that behaviour stop working.

Hope to find the way to solve this some day, meanwhile I think I just going to use a simple less cool script to show my portfolio. What a shame :(

**Comment by 4t145** [comment]
It is because when you turn to other page, turn.js will remove some element. So you lost eventlisteners of them. So I reset the listeners after I flip the book, and problem was solved.
每次翻页turnjs都会去除一些元素,所以监听也跟着丢失了,当这些元素再被创建的时候,监听已经不在了.
我解决的思路是每次翻页都重新获得监听.似乎解决了问题
只是一个初学者,因为坑爹的比赛学了js!
