### ISSUE TITLE
how to adjust the speed when i programmatically call the turnjs to flip to next page?

### ISSUE THREAD

**Issue by simkimsia** [blasten/turn.js#208]
I have a code that is this

$("#flipbook").turn('next');

Is there a way to adjust the speed of the turn of the book when it is called programmatically?

**Comment by entio** [comment]
Isn't there a property called duration, huh?
You set it creating a flipbook, just like that:
flipbook.turn({ duration: 1000 })

**Comment by simkimsia** [comment]
thank you, you are right. Didn't realize that I had missed it.
