### ISSUE TITLE
Jump to specific page without the turn effect?

### ISSUE THREAD

**Issue by lightmar** [blasten/turn.js#213]
Hi,

I would like to allow the user to navigate pages in the book, but when jumping to another page which is not the next or previous one, I would like to navigate to that page without the turning effect - only hide the current page and display the page navigated to. After the "jump" the user will be able to continue turning the pages as usual with the effect.

Is this possible?

Thanks.

**Comment by alvarodt** [comment]
You should be able to accomplish that by using:

$('ID_BOOK').turn('page', page_you_want_to_go).turn('stop');

**Comment by blasten** [comment]
Yep. Or using 

``` javascript
$("#flipbook").turn("options", {duration:0});
```

The `options` method isn't documented yet, but it changes the options passed to the constructor.  Sorry for that.
:)

**Comment by lightmar** [comment]
$('ID_BOOK').turn('page', page_you_want_to_go).turn('stop');
Is not working for me but
$("#flipbook").turn("options", {duration:0});
works perfectly, thanks.

**Comment by blasten** [comment]
@lightmar 

``` javascript
$('#flipbook').turn('page', 5).turn('stop');
```

it should also work.
