### ISSUE TITLE
hard cover + IE9

### ISSUE THREAD

**Issue by rkjdid** [blasten/turn.js#220]
Not sure this has been spotted yet : hard cover animation isn't working on IE9.
It flips in 1 step at the end of the supposed animation length

**Comment by skreiker** [comment]
I also encountered same problem. it just jumps to the opened/closed state and the shadow and the in-between animation looks really really buggy.

Using turn.js version 4

**Comment by beckiechoi** [comment]
same thing also happens in older firefox. tested with version 3.6.27.
I'm guessing it happens when there's no 3d css transforms.
would really like a fallback that would look like it's somewhat animating

**Comment by blasten** [comment]
Confirmed! I'll check it out. That shouldn't be happening because from the beginning hard pages were tested in IE9. Something has changed since then.

**Comment by ltolani** [comment]
Yes please and thanks for your response.

On Tue, Nov 6, 2012 at 10:57 AM, Emmanuel Garcia
notifications@github.comwrote:

> I'll check it out. That shouldn't be happening because from the beginning
> hard pages were tested in IE9. Something might have changed since then.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/blasten/turn.js/issues/220#issuecomment-10099703.

## 

Regards,

Lata Tolani | Software Engineer

Systematix Infotech Pvt. Ltd.

Bhopal | Indore | Gurgaon | Houston

T: 91.755.4003988 | Skype: lata.sipl

Disclaimer:This email and any attachments are sent in strictest confidence
for the sole use of the addressee and may contain legally privileged,
confidential, and proprietary data. If you are not the intended recipient,
please advise the sender by replying promptly to this email and then delete
and destroy this email and any attachments without any further use, copying
or forwarding.

**Comment by blasten** [comment]
Hello there!  This issue was fixed: http://turnjs.com/docs/Changelog  You should receive a new copy soon. if not, please send me an email.
- IE9 does not support hard covers because IE9 does not support the features that make this effect possible. The update substitues hard covers for the classic effect.
