### ISSUE TITLE
Bug with hard class

### ISSUE THREAD

**Issue by iammattq** [blasten/turn.js#229]
I downloaded the turn.js files from github to play around and noticed something strange. I'm not sure if its just me but the basic demo you have in the docs wasn't working. I was putting class="hard" on a page just didn't want to work, it was always a "soft" page.

Was investigating my noob-ness and decided to copy your jsFiddle example (http://jsfiddle.net/blasten/A9a7E/) exactly using the turn.js file from git hub rather than the files on your server and the result is this: http://jsfiddle.net/re2uc/

When I change the the managed resource to your demo url (http://www.turnjs.com/lib/turn.min.js) everything works as it should.

Is there something off in the github version?

Cheers
Matt

**Comment by blasten** [comment]
Hard pages are only available in turn.js 4th release. The version on GitHub is 3rd release.
