### ISSUE TITLE
Show legend

### ISSUE THREAD

**Issue by elenssen** [blasten/turn.js#23]
do you have plans to make a legend like a regular flippingbook; like http://flippingbook.com/demo/
- pagination
- go to certain page
- search
- show thumbnails
- etc.

On what time frame would this be possible?

**Comment by vool** [comment]
@elenssen go to a certain page is currently possible

`$('selector').turn('page', 2);`

**Comment by blasten** [comment]
turn.js provides you with everything you need to achieve the same thing.  Probably a different kind of version should include that demo.
