### ISSUE TITLE
turn js corners state

### ISSUE THREAD

**Issue by andreeasuba** [blasten/turn.js#230]
Hi,  is it possible to load the flipbook pages having the corners already  flipped ?

So it can easily suggest to the user that he can flip the page...? i'm talking about turn.js version 3

Thanks

**Comment by blasten** [comment]
@andreeasuba Are you looking at using the `peel`?  http://turnjs.com/docs/Method:_peel

**Comment by andreeasuba** [comment]
yes, but as far as I saw, peel it's available only for turn js 4. I'm working for a demo site, therefore I'm currently using turn 3.  thanks anyway

**Comment by andreeasuba** [comment]
also, when using turn 4, is it possible in double display to have the corners for both pages peeled? for right page to peel corner tr and for left page to peel the tl corner?

**Comment by blasten** [comment]
@andreeasuba Both versions include the peel method, but only one corner at time.

**Comment by tyssen** [comment]
Would that be like:

```
$('.flipbook').turn({
    elevation: 50,
    gradients: true,
    autoCenter: true,
    peel: "tr"
});
```

because I'm not seeing any change by adding peel.
