### ISSUE TITLE
Skip 6 Pages = undefined value, index out of range

### ISSUE THREAD

**Issue by preich1** [blasten/turn.js#232]
We're getting an error accessing an undefined object due to an array out of bounds error in version 4 when trying to skip over more than 6 pages in a double page layout with hard pages.   This occurs in the else statement of the _foldingpage function (line 2064).  Opts.next contains an index that's not in data.pageObjs.

To reproduce the problem, in the start event, set pageObject.next to a large value in order to skip over more than 6 pages.

Any suggestions?  We need to skip over some pages of the book, depending on how the user answers quiz questions.

Thank you!

**Comment by blasten** [comment]
@preich1 Oh yeah, I believe it's related to the size of the cache of turn.js. How many pages does your book have?  If you increase the value of pagesInDOM, the problem will be fixed.  Please send me an email and I will send you a new copy.
