### ISSUE TITLE
Unpeel method?

### ISSUE THREAD

**Issue by cato** [blasten/turn.js#234]
Is there a way to reverse the peel method. 

So: 

if a user hovers over an element: .turn('peel', 'tr')
then when they hover off .turn.('unpeel', 'tr')

The stop method works but it isn't animated.

Thanks

**Comment by raulabel** [comment]
Hi, all you need is this: .turn("peel", false);

;)

**Comment by blasten** [comment]
@cato Absolutely.

``` javascript
$('#flipbook').turn('peel', false);
```

**Comment by ballaneypranav** [comment]
Hi, I also wanted to do the same.. But it doesn't work.
Code: 

$('#flipbook').turn({
    width:720, 
    height:525,
});

$('#flipbook').turn('peel', false);

**Comment by blasten** [comment]
@ballaneypranav  It works perfectly!

``` javascript
$('#flipbook').turn('peel', 'br');
setTimeout(function(){ $('#flipbook').turn('peel', false); }, 1000);
```

**Comment by ballaneypranav** [comment]
Nope.  I want to disable the hover effect. Check out the demo: http://jsfiddle.net/ballaneypranav/SdUwg/
