### ISSUE TITLE
Turn flipbook on iPad - turning issue

### ISSUE THREAD

**Issue by andreeasuba** [blasten/turn.js#237]
Hello again,

I notice the following, on iPad, while turning the page if you "accidentally" tap with a second finger on the screen the turning page remains frozen in that position , let's say half turned. 

Is it be possible to do something to turn the page back in the initial state if the device detects two taps on the screen?

Thanks

**Comment by blasten** [comment]
@andreeasuba This bug was fixed!  Could you please send me an email to send you a new copy of turn.js?
