### ISSUE TITLE
set borders to pages

### ISSUE THREAD

**Issue by elenssen** [blasten/turn.js#24]
how to set borders to the pages
especially for first and last page.....

**Comment by vool** [comment]
Hey @elenssen,

to add styles to the pages you can target the turn-page class

`````` .turn-page{
        border:2px red solid;
}```

for just the front and back pages, you can target the page numbers:

```.p1, .p5{
    border:2px red solid;
}```

or you could add a class to the front and back pages  ``` eg .cover``` and style that,

Hope this helps

.k
``````

**Comment by elenssen** [comment]
The border of box-shadow won't work on the .turn-page class. This class has a necessary overflow:hidden which hides the generated "folded" page on drag with the mouse.
Because borders and box-shadow are generated on the outside of the <div> they won't show.

I need an no-overflow-hidden span or div higher in hierarchy then the .turn-page div. This is already available as the .pages or #magazine div, but this won't change the inline style width (2 times the page width) on the forst and last page. Ergo the border or box-shadow will extend out the page flow with an invisible page.

How to dynamically change the #magazine of .pages div on the first or last page.

**Comment by vool** [comment]
Ah ok, 
Then maybe it's best to add an inner div set to 100% ?

```
 .turn-page div{ 
border: 1px solid red;
width:100%;
height:100%;
}
```

on the box shadow, an inset shadow should work:

```
 .turn-page{
        -moz-box-shadow: inset 0 0 1px red;
        -webkit-box-shadow: inset 0 0 1px red;
        box-shadow: inset 0 0 1px red;  
}
```
