### ISSUE TITLE
How can I insert a page dynamically?

### ISSUE THREAD

**Issue by mytharcher** [blasten/turn.js#241]
I initialize turn with exist DOM for front and back hard covers, so I got 4 existing pages.

And then I want to insert other pages from my data between front cover and back cover, I used `addPage` method like this:

``` javascript
book.turn('addPage',
    newPage, // element created from data
    book.turn('pages') - 1 // I want to insert before last 2 hard covers
);
```

But this just **overwrote** last 2 hard covers! If I watching the total pages I would get `4`, never increased.

I noticed in the source code [line 331](https://github.com/blasten/turn.js/blob/master/turn.js#L331), whether the judgement is necessary? Why insert a page without increasing the total page count?

Maybe I missed something or is this a bug?

**Comment by blasten** [comment]
@mytharcher That was the design I though was OK. I now believe that I have missed a condition to detect whether the page was inserted or not. As you probably know, a magazine can have N pages, but without necessarily having N pages loaded. Therefore, if we want to insert a page to populate the magazine (behavior expected when using dynamic pages and the `missing` event), the total pages should not be increased. What I missed was to actually check if that page exists or not.  If it already exists, then you code should work.  Do you have a license of 4th release?  I will do include this little change pretty soon.

**Comment by mytharcher** [comment]
I now realize that your original meaning of `addPage` should be `replace` some page which content would be loaded later.

Now I am working on transform a blog list into a book and show by `turn.js`, and it will be done in a few days. I mean I just use it for my blog and not for any commercial use. Should I buy the license or can I just use it under your non-commercial BSD license?

**Comment by blasten** [comment]
@mytharcher Yes, you can use 3rd release for noncommercial projects.
