### ISSUE TITLE
autoplay ?

### ISSUE THREAD

**Issue by Panda77** [blasten/turn.js#244]
possible autoplay flip in loop?

**Comment by blasten** [comment]
Yes, using the following JavaScript:

``` javascript
setInterval(function() {
 $('#flipbook').turn('next');
}, 1000);
```

The 1000 means 1 second.

**Comment by Panda77** [comment]
and at the end of book, reopen page 1 with a loop?

**Comment by blasten** [comment]
``` javascript
setInterval(function() {
 if ( $('#flipbook').turn('page')==$('#flipbook').turn('pages') ) {
    $('#flipbook').turn('page', 1);
 } else {
    $('#flipbook').turn('next');
 }
}, 1000);
```

**Comment by rohit0511** [comment]
I have implemented above solution and its working great but if i click some corner to turn page then i want that autoplay should be stopped after turning a single page. how to do it???

**Comment by WillHarrisWip** [comment]
I just implemented this solution so many years later and I also have the same problem as rohit0511.
Except my flipbook goes to the last page. Any attempt to turn to the previous page just snapback to auto turn. I only want to reveal the first page turn. How do I make this thing stop after the first flip?
