### ISSUE TITLE
Configurable Flip in Single mode

### ISSUE THREAD

**Issue by pchowdhry** [blasten/turn.js#248]
I'm using turn.js in single page mode on an Ipad and was wondering if there was a way to commit to the turn once the swipe has passed the center of the page. It doesn't seem intuitive to have to go all the way to the edle of the page. In double mode the flip commits once the halfway mark is met. Is this configurable?

Thanks in advance

-pankaj

**Comment by blasten** [comment]
What version of turn.js are you using?  turn.js 4th release works like that, it turns the page once the curl page has passed the center of the page. Yes, this should be an option soon, more friendly to configurate.
