### ISSUE TITLE
only flips pages to left

### ISSUE THREAD

**Issue by Amack34** [blasten/turn.js#25]
Im using chrome,
it works kinda but,
i can only flip through the pages backwards, 
not forward...
im using turn.min.jsp

and

example
JavaScript code:

$('#magazine').turn({width:800, height: 400, page: 1, shadows: true, acceleration: true});

**Comment by blasten** [comment]
is it for an arabic page?

**Comment by Amack34** [comment]
oh no, sorry for the misunderstanding...
But the only way i can turn the pages-- is if I use
$('#magazine').turn({width:800, height: 400, page: 1, shadows: true, acceleration: true}); and the page number is not at 1, and i can only flip backwards to the first page...
And when Im back on the fist page I cant flip forward....
It grabs the pages, but only when not on the first page, and i can only flip pages backwards..
Again sorry for the misunderstanding, and your help is greatly appreciated...

**Comment by blasten** [comment]
You want to start in a different page because you want to have two pages at the beginning?

**Comment by Amack34** [comment]
Oh no, I just want to start from the beginning, but it wont grab the first page...
the only way it grabs the pages is if the first page isnt set to 1 in the javascript code--and it only lets me go backwards to the start of the first page...
Thanks for responding, again your help is greatly appreciated...

**Comment by Amack34** [comment]
is there a certain size the page has to be?

**Comment by Amack34** [comment]
Any height and width under 219, you are going to have problems turning pages...

I found out what the problem was...
it works like a charm...

**Comment by blasten** [comment]
You can choose the size you want!

**Comment by samples490** [comment]
How can this be used to to flip from left to right?, i mean for  for an arabic page
