### ISSUE TITLE
Can Download turn.js 4th release

### ISSUE THREAD

**Issue by ptcorp** [blasten/turn.js#252]
I recently purchased a licence for turn.js, but when i try to download the server keeps timing out.  
I though this was  a lightweight plugin? 
I've tried several attempts, and the download size has gone up to 18.8mb before connections slows to the point the network drops the connection.
chrome console give the following warning on download

Resource interpreted as Document but transferred with MIME type application/x-zip-compressed:

**Comment by blasten** [comment]
Have you recently sent me an email?  Please send an email to support@turnjs.com
