### ISSUE TITLE
Facebook/Social

### ISSUE THREAD

**Issue by JLMedia** [blasten/turn.js#255]
Hi three questions. 
1. Do you have any documentation on adding social links? 
2. How can I make the side navigation bars stay visible?
3. How do I add thumbnails for a large book of 24 pages?

**Comment by blasten** [comment]
@JLMedia  
1. The social links are simple HTML from Facebook or Twitter. However, I do think that turn.js should have something that is not turn.js. Meaning that it should be something where people sign up and add their content in few steps. 
2. The navigation bar is only visible if there's space available to show it.  The next generation of turn.js is fully responsive, and it includes a full stack of controls. ( the slider and navigation bars)
3. HTML

``` HTML
<li class="d">
  <img src="pages/6-thumb.jpg" width="76" height="100" class="page-6">
  <img src="pages/7-thumb.jpg" width="76" height="100" class="page-7">
  <span>6-7</span>
</li>
```
