### ISSUE TITLE
Disable Corner Click Event

### ISSUE THREAD

**Issue by iammattq** [blasten/turn.js#256]
Hi there, I followed your guide on disabling the top corner peels by using the start event (doc example: 
http://turnjs.com/docs/Event:_start ). However the click events are still active on those top corners. Is there a way to remove the click events on the top corners?

thanks

**Comment by blasten** [comment]
Sorry, the `turning` event does not report the corner. Meanwhile, one workaround is to remove the corners in the turn.js file:

``` javascript
corners = {
  backward: ['bl'],
  forward: ['br'],
  all: [ 'bl', 'br', 'l', 'r']
},
```
