### ISSUE TITLE
Regions simply not working

### ISSUE THREAD

**Issue by Guppi** [blasten/turn.js#257]
Magazine demo: 
Regions don't seem to work at all on Chrome 23 and IE 9.
The magazine.js file is dated 12.09.2012 12:42
The turn.js file is dated 26.11.2012 01:57
What am I missing? Any tips on how to debug?

**Comment by blasten** [comment]
@Guppi could you please send me a link to the website?

**Comment by francescbozzo** [comment]
Hi guys,
I've encountred the same problem on Google Chrome. Did you solve it finally?

Regards

**Comment by blasten** [comment]
@francescbozzo did you upload the files to a webserver?  For security reasons, Chrome doesn't load external resources such as the regions if you just "Open the index.html" with Chrome.
