### ISSUE TITLE
book page depth on the edge - Steve Jobs example

### ISSUE THREAD

**Issue by relipse** [blasten/turn.js#260]
I love the steve jobs book example because it is so realistic.

How can I easily add the book page depth on the left and right edges so that they decrease on the right side while turning to the right, and likewise decrease on the left side when turning left?

Jim

**Comment by blasten** [comment]
@relipse Thanks!  It's just a div element in the inner cover and inner back cover . The width gets updated as the user moves through the book.  The covers have the `.own-size` class, so they are a little wider than the inner pages.

**Comment by roots-ai** [comment]
Hi blasten! I tried to do the same by keeping the .own-size class on the covers, but the "display" gets set to "none" for the 'cover pages' on navigating through the book. Why is it happening like this?
