### ISSUE TITLE
Starting page numbers after table of contents while using hash.js

### ISSUE THREAD

**Issue by Caroline-Elisa** [blasten/turn.js#261]
Hi there,

I would like the displayed page numbers to start after the table of contents. I have it almost working here: www.professorleonidas.com/livro/offset (see script here: http://www.professorleonidas.com/livro/wp-content/themes/professorleonidas/script-offset.js)

Using the arrow keys you can see the hash changing to reflect the page numbers displayed on each page. This comes from adding a simple offset to the turning function:

`var pageoffset = page - 7;
Hash.go('page/' + pageoffset).update();`

However this is obviously flawed as when you go to www.professorleonidas.com/livro/offset/#page/7 it jumps to page 0 and not page 7.

Any tips for a better solution?

Thanks!

**Comment by blasten** [comment]
@Caroline-Elisa You would also have to change the procedure that takes care of the URL:

``` javascript

Hash.on('^page\/([0-9]*)$', {
  yep: function(path, parts) {
    var page = parts[1];
    var tableOfContentsPage = 7;
    if (page!==undefined) {
      if ($('.magazine').turn('is'))
          $('.magazine').turn('page', page + tableOfContentsPage);
      }
  },
  nop: function(path) {
  if ($('.magazine').turn('is'))
    $('.magazine').turn('page', 1);
  }
});
```

This obviously asumes that your table of contents is on page 7.

**Comment by Caroline-Elisa** [comment]
Thanks blasten!

But I'm afraid that doesn't quite work for me.

When I go to (or refresh) http://www.professorleonidas.com/livro/#page/1 for example, it goes to http://www.professorleonidas.com/livro/#page/10 while http://www.professorleonidas.com/livro/#page/2 goes to http://www.professorleonidas.com/livro/#page/20.

Here are the two bits of code:

`var pageoffset = page - 8;
Hash.go('page/' + pageoffset).update();`

And your

`Hash.on('^page\/([0-9]*)$', {
        yep: function(path, parts) {
            var page = parts[1];
            var tableOfContentsPage = 8;
            if (page!==undefined) {
                if ($('.book').turn('is'))
                    $('.book').turn('page', page + tableOfContentsPage);
            }
        },
        nop: function(path) {
            if ($('.book').turn('is'))
                $('.book').turn('page', 1);
        }
    });`

The site: http://www.professorleonidas.com/livro/
The script: http://www.professorleonidas.com/livro/wp-content/themes/professorleonidas/script.js

Thanks again!
