### ISSUE TITLE
Swiping to navigate

### ISSUE THREAD

**Issue by Caroline-Elisa** [blasten/turn.js#262]
Hi again,

I'm afraid I haven't managed to get the flipbook turning on the iPhone. 

I have included `zoom.min.js` and am using the following script:

`$(".flipbook-viewport").bind("zoom.swipeRight", function(event) {
    $(".book").turn("previous");
});
$(".flipbook-viewport").bind("zoom.swipeLeft", function(event) {
    $(".book").turn("next");
});
`
What am I missing? If there is documentation I haven't come across please feel free to point me in the right direction...

**Comment by blasten** [comment]
It's looks OK.  There might be something else going on. Can you please send me a link?

**Comment by Caroline-Elisa** [comment]
Hi blasten,

Here is the site: http://www.professorleonidas.com/livro

I removed the script I mentioned above, as it didn't seem to do anything.

Using the plugin I can swipe the corners to turn pages but what I was really after was the expected swipe functionality - where the user can swipe anywhere to turn the pages. At the moment if you swipe outside of the small corners the whole page scrolls.

Thanks for taking a look!

**Comment by luisadancabrera** [comment]
Hola amigo, que codigo usaste para los botones superiores e inferiores? para q

**Comment by luisadancabrera** [comment]
Hola amigo, que codigo usaste para tus botones superiores e inferiores? para que avancen al hacer click. Agradeceria mucho tu ayuda

**Comment by alQemist** [comment]
I have a similar problem with swiping page turning - getting the following error

zoom.js:1014 TurnJsError: flipbook is not a method

**Comment by blasten** [comment]
@alQemist flipbook can't be called in that way.  Could you paste the code that causes this error?

**Comment by alQemist** [comment]
I found the source of the problem. The original lines were  - 

   $(this).zoom('flipbook').turn('next');
   $(this).zoom('flipbook').turn('previous');

changed them to

  $('.magazine').turn('next');
  $('.magazine').turn('previous');

Here are the lines in the original code....

// Zoom.js 

```
$('.magazine-viewport').zoom({
    flipbook: $('.magazine'),

    max: function() { 

        return largeMagazineWidth()/$('.magazine').width();

    }, 

    when: {

        swipeLeft: function() {

            $('.magazine').turn('next');  // originally  - $(this).zoom('flipbook').turn('next');

        },

        swipeRight: function() {

            $('.magazine').turn('previous');  // originally: $(this).zoom('flipbook').turn('previous');

        },
```

**Comment by blasten** [comment]
How did you initialize the zoom part? The problem should be there.

**Comment by alQemist** [comment]
How should it be initialized ? I am using the code out of the box with some minor changes but none related to zoom.

**Comment by blasten** [comment]
``` javascript
$("#zoom-viewport").zoom({
    flipbook: $(".magazine"),
    max: 3
});
```

**Comment by rondiege** [comment]
Hey there! any solutions to this? I am also having a problem with swipeLeft and swipeRight, it seems as though they are not getting triggered. Even the examples right out of the box are not swiping for me... maybe I set them up wrong?

Anyways here is my zoom being initialized w/ debugging alerts - 

```
        $('.magazine-viewport').zoom({
        flipbook: $('.magazine'),

        max: function() { 
            return largeMagazineWidth()/$('.magazine').width();
        }, 
        when: {
            swipeLeft: function() {
alert('hereleft'); // is NOT triggered
            $(this).zoom('flipbook').turn('next');

            },
            swipeRight: function() {
alert('hereright'); // is NOT triggered
                $(this).zoom('flipbook').turn('previous');
            },
            resize: function(event, scale, page, pageElement) {
alert('resize'); // It is triggered 
                if (scale==1)
                    loadSmallPage(page, pageElement);
                else
                    loadLargePage(page, pageElement);
            },
            zoomIn: function () {
alert('zoomin'); // It is triggered 
                $('#slider-bar').hide();
                $('.made').hide();
                $('.magazine').removeClass('animated').addClass('zoom-in');
                $('.zoom-icon').removeClass('zoom-icon-in').addClass('zoom-icon-out');  
                if (!window.escTip && !$.isTouch) {
                    escTip = true;
                    $('<div />', {'class': 'exit-message'}).
                        html('<div>Press ESC to exit</div>').
                            appendTo($('body')).
                            delay(2000).
                            animate({opacity:0}, 500, function() {
                                $(this).remove();
                            });
                }
            },
            zoomOut: function () {
alert('zoomout'); // It is triggered 
                $('#slider-bar').fadeIn();
                $('.exit-message').hide();
                $('.made').fadeIn();
                $('.zoom-icon').removeClass('zoom-icon-out').addClass('zoom-icon-in');
                setTimeout(function(){
                    $('.magazine').addClass('animated').removeClass('zoom-in');
                    resizeViewport();
                }, 0);
            }
        }
    });
```

**Comment by rondiege** [comment]
I got it to work... I added an id to the div my flipbook is so now that div reads - 

```
<div class="magazine" id="flipbook">
.... more stuff ....
</div>
```

and my swipe functions now look like this:

```
swipeLeft: function() {
    $('#flipbook').turn('next');
},
swipeRight: function() {
    $('#flipbook').turn('previous');    
},
```

Thanks for a cool product!

**Comment by blasten** [comment]
Thanks

**Comment by konceptdesignstudio** [comment]
I am also not able to get my script to register swipe events -- I believe I am initializing zoom correctly and I can't see any differences between my code and what's been written above. Has anything changed with the library?

My site is http://kdsdeveloper.com/century/parkside and I am running it on a Samsung Tab 10.1 with Chrome for Android.
