### ISSUE TITLE
Integrating with Nextgen Gallery on wordpress

### ISSUE THREAD

**Issue by yovdesign** [blasten/turn.js#263]
hey,

i'm trying to integrate the turn.js 4 via the nextgen gallery plugin for wordpress.

i got it to work, altough, the loadPage function loads a new page from a specific folder on the host.

i inserted the loading function and zooming events into the "gallery-view.php" and made a change to the "img.attr" source as follows:

function loadPage(page, pageElement) {

```
// Create an image element

var img = $('<img />');

img.mousedown(function(e) {
    e.preventDefault();
});

img.load(function() {

    // Set the size
    $(this).css({width: '100%', height: '100%'});

    // Add the image to the page after loaded

    $(this).appendTo(pageElement);

    // Remove the loader indicator

    pageElement.find('.loader').remove();
});

// Load the page


img.attr('src', '<?php echo $image->thumbnailURL ?>'); 

loadRegions(page, pageElement);
```

}

<?php echo $image->thumbnailURL ?> -  is a nextgen's call for the thumb

well, the problem is that it puts only the LAST image i have uploaded ON ALL PAGES.
same with the zoom in function only calling for " $image->imageURL"

please please help me to solve this.

**Comment by blasten** [comment]
This code should not have any PHP. You could create a JavaScript object where the keys are the page numbers to map a page and the image. E.g.  pageImages={1:'image1.jpg'};

**Comment by yovdesign** [comment]
<div class="loader">
<?php $counter = 1; ?>
<?php foreach ($images as $image) : ?>
<div style="display: none;" id="hidden_pid_image_<?php echo $counter
?>"><?php echo $image->imageURL ?></div>
<div style="display: none;" id="hidden_small_image_<?php echo $counter
?>"><?php echo $image->thumbnailURL ?></div>
<?php $counter++; ?>
 <?php endforeach; ?>
</div>

function loadPage(page, pageElement) {

// Create an image element

var img = $('<img />');

img.mousedown(function(e) {
e.preventDefault();
});

img.load(function() {
 // Set the size
$(this).css({width: '100%', height: '100%'});

// Add the image to the page after loaded

$(this).appendTo(pageElement);

// Remove the loader indicator
 pageElement.find('.loader').remove();
});

// Load the page

img.attr('src', $("#hidden_small_image_"+page).html());

//loadRegions(page, pageElement);

}

eventually used a hidden div img, which i call via the counter.

any way, thanx for trying to help man.
cheers

On Wed, Dec 26, 2012 at 3:32 AM, Emmanuel Garcia
notifications@github.comwrote:

> This code shouldnt have any PHP. You could create a JavaScript object
> where the keys are the page numbers to map a page and the image. E.g.
> pageImages={1:image1.jpg`};
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/blasten/turn.js/issues/263#issuecomment-11679537.

##
