### ISSUE TITLE
Magazine sample into Steve Jobs

### ISSUE THREAD

**Issue by victoriakvint** [blasten/turn.js#264]
Hello! We purchased TURNJS4 and we'd love  to incorporate Magazine image based example into Steve-Jobs, where you have a nicer book and a thumbnail scroll. Is it possible to do that? Thank you.

**Comment by blasten** [comment]
Yes, absolutely. Let me know if you have any technical question.

**Comment by sushant357** [comment]
Can you please send me how to do this with thumbnails...
if possible then please give one demo link where i can see like jsfiddle 
Thanks in advance...
