### ISSUE TITLE
nav & arrows

### ISSUE THREAD

**Issue by rimareda** [blasten/turn.js#27]
hi there,

how do i add the nav functionality like you have on your demo site? also the forward and back buttons on either side of the container? i'm not well versed in javascript... i assume you can set up a click event but i'm wondering if you can help me with the syntax?

thank you!

**Comment by blasten** [comment]
It's not part of turn.js, but it's easy to add, just basic css.  I will consider a demo including the navigation for next versions, so far you can use the demo, no problem.
