### ISSUE TITLE
Flipping over page which contains 'iframe' fails

### ISSUE THREAD

**Issue by MarkiyanMatsekh** [blasten/turn.js#272]
When page contains iframe element, flipping over this element has no visual representation, i.e. flipping blocks until you move mouse outside iframe.

http://jsfiddle.net/XSZkb/2/

I coulnd't find any workaround or explanation in documentation.
Please advice some tips on how to handle this.

**Comment by MarkiyanMatsekh** [comment]
found these
https://github.com/blasten/turn.js/issues/77
https://github.com/blasten/turn.js/issues/83

8 months ago you tried fixing them...any success?

**Comment by blasten** [comment]
@MarkiyanMatsekh   Yes! Look at this trick http://jsfiddle.net/XSZkb/3/.  

Now, there aren't any problems with the iframe.  I think this may be an option for turnjs "iframeSupport:true"

**Comment by MarkiyanMatsekh** [comment]
@blasten thanks. but, unfortunately there's no 'end' event in 3rd version.
