### ISSUE TITLE
Works with with all but Windows

### ISSUE THREAD

**Issue by hokrc01** [blasten/turn.js#275]
My site is formatting well in all browsers but IE.  Sometimes is formats OK but most times the next and previous buttons are on different lines  Any help would be appreciated. 

http://consulting247.info/bestjewishbuy/c247magazine.php

ken

The issue seems to have been do to the windows IE comparability setting.  Seems to be working just fine now.  Thank you all.

**Comment by blasten** [comment]
IE 8? Yes, it is missing the compatibility mode. Do you know how to set it up?

**Comment by hokrc01** [comment]
Yes

I was able to get it to work after a while, (a long while) but it seemes 
to be working now.

thank you

ken
