### ISSUE TITLE
thickness on hard pages - have followed all instructions....still not working

### ISSUE THREAD

**Issue by jchamie** [blasten/turn.js#277]
I am having difficulty getting the thickness to appear.  I have read and I understand issue 224. I understand how to use 'depth = 5' etc... and 'p1. side' creates a panel which is rotated -90 degrees to fit in between the gap between the front cover and next page.  
However it does not show.  Instead i can still see the 5 px gap created between the hard pages.
I have purchased 4th edition and the included steve-jobs example does not show correctly.

(Yet strangely the steve-jobs example on turn.js website it DOES show perfectly. Is it different to the one included when you purchase???)

Can anyone help? - i have spent a week trying to figure this out! Could anyone send me an example that works???

**Comment by blasten** [comment]
@jchamie  The idea is to bring to the front the layer that has the front cover (page 1) while adding another div to cover the gap between the front cover and the opposing side. This can be entirely accomplish using CSS3.  If you are applying all the CSS rules and still don't get the thing done, please submit a link.

**Comment by jchamie** [comment]
Thanks blasten - i understand and everything in the code looks like it should work.... but it doesn't.  I have uploaded the steve-jobs book example that came with the turn.js download (I have not changed or added to it in anyway). As you can see it has the 5px gap but nothing covers the gap.  Link -  http://www.fenz.org.nz/test/samples/steve-jobs/
Any ideas why?

**Comment by jchamie** [comment]
The thickness effect was not showing because of overflow: hidden.  
I have altered the turn.js file and now it works.   Instead of this.turn('stop').css({'overflow': 'hidden'});  line 842 now reads    this.turn('stop').css({'overflow': ''});
