### ISSUE TITLE
IE8 support

### ISSUE THREAD

**Issue by GeoffWilkins** [blasten/turn.js#28]
Great software, I'm looking forward to IE9 support (this month?) - any chance of IE8 support, for Windows XP users?

**Comment by blasten** [comment]
Yes, IE8 doesn't have CSS3 transformations. Therefore, it's not possible to bring the same effect to IE8.  However, a simple flip effect in only one direction can replace it for IE8.

**Comment by GeoffWilkins** [comment]
I realise this, but I guess it needs to "degrade gracefully" for IE8, using something like [if IE 8].

**Comment by blasten** [comment]
IE users should just uninstall IE. If they still want to use IE, it's because they don't appreciate good experiences.  However I know there's a public out there, so the way it might work is just by changing `left`, `position` and `display` properties of each page.

**Comment by GeoffWilkins** [comment]
I'll try what you suggest, but it would be great if you could give a bit more guidance.

Is turn.js now working fully OK with IE9?

**Comment by blasten** [comment]
not yet, but I hope to find a virtual machine or PC to try it.

**Comment by rimareda** [comment]
you mentioned trying to change the "left" "position" and "display" properties? to what? i'm also trying to get this to work with IE<9

**Comment by devolved** [comment]
Is there a known method of making turn.js look presentable to ie7/8 users? I realise there's no way to make it the same but I do need to make it look "not wrong".

If it is possible I'll persue it, if not I'll look for an alternative ... but I'd really appreciate knowing (because a solution exists) if it can be done.

**Comment by devolved** [comment]
Update: I've got it looking pretty presentable after ironing out the inevitable ie7/8 css bugs.

After playing with the turn.js settings I've found that by reducing the cornerSize value it's enough to stop the flip initiating (which caused some other display problems) and so ie7/8 won't get this clash.

All you need to do is put cornerSize = 1; in your conditional IE comment and hey presto, ie7/8 get a much calmer experience.

Though, in retrospect <!--[if lt IE 9]>$('.book').turn('disable', true);   is probably a better way of doing it.

**Comment by devolved** [comment]
FOR THE OTHERS ON THIS THREAD: without the page turn you'll of course need to add some navigation links, below is the jQuery for using the arrow keys (make sure you change the selector)

```
// arrow key navigation
$(document).keydown(function(e) {
    if (e.keyCode == 37) { 
       $('.book').turn('previous')
       return false;
    }
    if (e.keyCode == 39) { 
       $('.book').turn('next')
       return false;
    }

});
```

**Comment by blasten** [comment]
Turn.js 4, now supports IE8

**Comment by biolucas** [comment]
Hi. ¿Can I see an url where turnjs4 works fine in IE8?. By now all the examples I've seen of turnjs4, IE8 doesn't work so fine as other browsers.

Thanks you very much, Víctor

**Comment by devolved** [comment]
The ie7/8 fall back version only has a simple page transition (due to lack of css3 support).

So instead of the full page curl effect, you just get a simple left/right animation.

**Comment by biolucas** [comment]
Thank you for your quick reply!

Regards, Víctor
