### ISSUE TITLE
Bug in numeration

### ISSUE THREAD

**Issue by dexion** [blasten/turn.js#291]
$("#flipbook").turn('next');
$("#flipbook").turn('page'); => 2
$("#flipbook").turn('next');
$("#flipbook").turn('page'); => 4
$("#flipbook").turn('next');
$("#flipbook").turn('page'); => 6
$("#flipbook").turn('previous');
$("#flipbook").turn('page'); => 5
$("#flipbook").turn('previous');
$("#flipbook").turn('page'); => 3
$("#flipbook").turn('next');
$("#flipbook").turn('page'); => 4

So, I think this is a bug... It should be:
$("#flipbook").turn('next');
$("#flipbook").turn('page'); => 2
$("#flipbook").turn('next');
$("#flipbook").turn('page'); => 4
$("#flipbook").turn('next');
$("#flipbook").turn('page'); => 6
$("#flipbook").turn('previous');
$("#flipbook").turn('page'); => 4
$("#flipbook").turn('previous');
$("#flipbook").turn('page'); => 2
$("#flipbook").turn('next');
$("#flipbook").turn('page'); => 4

**Comment by blasten** [comment]
@dexion This has been fixed in the next update.
