### ISSUE TITLE
box-shadow

### ISSUE THREAD

**Issue by dexion** [blasten/turn.js#292]
After "turning" script automaticaly add style for page div:

box-shadow: 0 0 20px rgba(0,0,0,20)

**Comment by smashercosmo** [comment]
Actually the style is box-shadow: 0px 0px 20px rgba(0, 0, 0, 0);
But yes it seems to be redundant here.

**Comment by blasten** [comment]
Yes, do you want to remove it?

**Comment by dexion** [comment]
Yes, I want :)

**Comment by blasten** [comment]
You can use `box-shadow: none important!`  FYI: Box-shadow has become obsolete in the next update of turn.js

**Comment by dexion** [comment]
No. important - bad way. And if I cahnge box-shadow in my css like 0px 0px 20px rgba(255, 0, 0, 0);   script will overwrite it to 0px 0px 20px rgba(0, 0, 0, 0); after turning. Bug in turning method

**Comment by blasten** [comment]
Yes, it's probably not the best way, but it will resolve the problem.   box-shadow was tied to the gradient:true option in turn.js 4th release.
