### ISSUE TITLE
Single Page: back of page background

### ISSUE THREAD

**Issue by jpsmith1981** [blasten/turn.js#293]
Hello~  

Is there a way to set a background image to the back of page when set to single.  Thanks

**Comment by jpsmith1981** [comment]
Nevermind, I can not believe I did not see this.  You just set the background image of the turn-page class.

For example:

#flipBoard .turn-page{
    background-image:url(../img/paperBg.png);
    background-repeat: no-repeat;
}

**Comment by blasten** [comment]
Great!

**Comment by phpworld** [comment]
I Need Help ..? In turn js 👍 
i  want each flip page have own back background 
that mean each flip have different different back Background 
--- i use this but its for ALL flips back have single --- background 
#flipBoard .turn-page{
background-image:url(../img/paperBg.png);
background-repeat: no-repeat;
}------------------- 

i need individual background
