### ISSUE TITLE
Class .hard does not work

### ISSUE THREAD

**Issue by kaitoqueiroz** [blasten/turn.js#295]
I want this way:
http://jsfiddle.net/blasten/A9a7E/

See my code in jsfiddle, is the same:
http://jsfiddle.net/re2uc/

**Comment by blasten** [comment]
What version of turn.js are you using?

**Comment by kaitoqueiroz** [comment]
The latest found here:
https://github.com/blasten/turn.js

**Comment by blasten** [comment]
The .hard class is available on turn.js 4th release. You can get this version on turnjs.com
