### ISSUE TITLE
Adding a pop-up window with other javascript functions to the magazine regions

### ISSUE THREAD

**Issue by mbpt** [blasten/turn.js#296]
I'd like to add some pop-up windows to both HTML and video files using the regions in the magazine example. Preferably using the "shadowbox" function from this website: http://www.shadowbox-js.com/ 

I've never worked with ".json" files before, so I'm not sure how it would work. Can extra HTML anchor attributes be added in the ".json" file? Is this all being handled by the javascript? When I've used the "shadowbox" listed in the URL above, I would normally write it in HTML as "&lt;a href="website.html" rel="shadowbox"&gt;...&lt;/a&gt; but the ".json" file is listing the link in the '"data":' and '"url":' script. 

If the regular "&lt;a href ...&gt;" code is being written in the Javascript, is it an all or nothing situation? I'm guessing, but they are all behaving as if they are using a 'target="_blank"' attribute. There may be several of the regions I would like to function as they do now. So I'd want to choose which region pops up and which simply work as is. 

Any help would be appreciated.

**Comment by blasten** [comment]
The json files are used for the regions in a image-based setup.  If you were to use HTML for the content itself, you wouldn't have to use these files; indeed, only HTML.
