### ISSUE TITLE
problem positioning on top of individual picture

### ISSUE THREAD

**Issue by markfdr** [blasten/turn.js#30]
Hi, 
Great work, 

I have a strange problem positioning 'absolute' in the following code :
<code> < div style="background-image:url(pages/11.jpg);">
       < div id="11" >
<code>  < a  href="#" target="_blank">#######</a>
    < /div>
 < /div>   

it somehow doesn't get it 
outside the magazine its working fine. 

it might be something with the script ? any ideas ? 
thnx
/\/\ark

**Comment by blasten** [comment]
where are you adding the absolute? The default position of the element < div style="background-image:url(pages/11.jpg);"> is absolute.

**Comment by markfdr** [comment]
im trying to place inside the div < div style="background-image:url(pages/11.jpg);">  here  < /div> another div with a link  and position it on top of the selected background image. 
the values are in id="11" style
it does not receive any values related to position.

**Comment by markfdr** [comment]
sorry CSS syntax issue, my bad
