### ISSUE TITLE
Corner radius

### ISSUE THREAD

**Issue by bura86** [blasten/turn.js#301]
Hello, I'm experiencing one issue with hover effect on page corners. 
I have google maps in my flipbook, which is located on the top of the page. The gmaps has some buttons on the top left corner which I can't reach because when I hover over the top left corner the flip effect activates.
Is there any solution to reduce the radius for this flip effect or to disable the flip corners only on that one page.

Thanks

**Comment by jchamie** [comment]
Does this help bura86?
Quote from turn.js manual:

For example, if you want to prevent the animation to start when using the corners tl and tr, you can use the start event and prevent its default action:

$("#flipbook").bind("start", function(event, pageObject, corner) {
  if (corner=="tl" || corner=="tr") {
    event.preventDefault();
  }
});

**Comment by bura86** [comment]
It works, thanks a lot.

The only thing is when you click on the corner it doesn't prevent the page turning, so I made some workaround in 'turning' event. 
Problem solved :+1:
