### ISSUE TITLE
Start with Spread

### ISSUE THREAD

**Issue by erichboileau** [blasten/turn.js#303]
Hello!

I'm using turnjs to develop a storybook app, and I'd like to display the book without a "cover," just as an open spread as soon as the page loads. Couldn't figure it out from the documentation. I've tried display: double and using ".odd" or ".even" on the first couple of pages, but it's not working yet.

Does the issue make sense? What's the best way to accomplish this?

Thanks!

**Comment by blasten** [comment]
Check this out #140
