### ISSUE TITLE
Examples don't work on homepage

### ISSUE THREAD

**Issue by abecks** [blasten/turn.js#305]
The homepage says "Click a book or magazine to see turn.js in action" yet none of them do anything. Is this project still alive?

**Comment by blasten** [comment]
Yes, it's.  What browser were you using?

**Comment by abecks** [comment]
Chrome on Windows and Chrome on OS X.

**Comment by blasten** [comment]
I'm using Chrome and it works using 25.x or canary.  Does it report the error in the console? Or what exactly happen?

**Comment by abecks** [comment]
I just verified that it is actually working in Chrome on OS X. However, 
on Windows in Chrome 25 it is not. The hover effects for the books does 
not trigger, and clicking on them does nothing. No console errors.

I am noticing several warnings for "Resource interpreted as Image but 
transferred with MIME type XXXX" for some of your css and JS files, 
however this occurs on both OS X and Windows, and OS X works.

Network tab shows all of the resources are loading without error.  What 
click event are you listening for on the books?

**Comment by blasten** [comment]
I will check this out as soon as possible.  Click, but using event delegation.

**Comment by AlvinNukman** [comment]
Same here. using Chrome 25 in Windows 8, and i tried in my other device running same Chrome 25, exactly do nothing, i can't hover, click and interact. The zoom samples too, if only the interaction can be done just by using left/right keyboard. Tried in Chrome for Android, worked perfectly. In IE10 Windows 8, works perfectly too. Tested in Firefox on my Windows 8 don't work too.

i checked console in chrome, but theres nothing. Please fix, thanks for the great work

**Comment by ZennTNX** [comment]
I just filed a new bug which is probably the same as this one.

**Comment by blasten** [comment]
Same as #315.  Was it a surface or touch-compatible device?   I tried three different builds under Windows 7 and 8, but I wasn't able to replicate this problem.

**Comment by btbxbob** [comment]
Hello, i have this issue too. I've got a touch device.
It works when i use touchscreen, but i can't use mouse on it. I think it's a glitch.

**Comment by wramirez09** [comment]
doesn't seem to work on Firefox windows 7
