### ISSUE TITLE
turn.js not working.

### ISSUE THREAD

**Issue by ChrisCates** [blasten/turn.js#31]
I have the source code, copied directly as you have in the example. However, I changed the javascript sources to my own source. I don't know why this isn't working It just shows Test, Test, Test, Test all under each other... Could you help me?

**Comment by ChrisCates** [comment]
<!doctype html>
<html>
<head>
        <script src="turn.min.js"></script>
        <script src="jquery-1.7.1.js"></script>

<style type="text/css">
body{
    background:#ccc;
}
#magazine{
}
#magazine .turn-page{
    background-color:#ccc;
    background-size:100% 100%;
}
</style>

</head>
<body>

<div id="magazine">
    <div> Test </div>
    <div> Test </div>
    <div> Test </div>
    <div> Test </div>
</div>


<script type="text/javascript">

    $('#magazine').bind('turned', function(e, page) {

        console.log('Current view: ', $('#magazine').turn('view'));

    })

    $('#magazine').turn({width: 1152, height: 752, acceleration: true, shadows: !$.isTouch});


</script>


</body>
</html>

**Comment by ChrisCates** [comment]
Well you get the point. Sorry for that etchy comment.  I was trying to show source code.

**Comment by raoufathar** [comment]
You need to include JQuery also. Download and include Jquery.js

**Comment by blasten** [comment]
Yes, it seems like jQuery was not included.

**Comment by ChrisCates** [comment]
Jquery.min.js was included, but, not Jquery.js, is that the issue?

**Comment by ChrisCates** [comment]
I'm going to test it out now with jQuery.js not Jquery.min

**Comment by ChrisCates** [comment]
Yea, makes no difference. I'm so confused: https://gist.github.com/2170034 Check out this repository, it's my source code that doesn't work, It's very similar to yours. I tested Jquery on it's own, it's working, and, I made sure I typed in turn.min.js correctly.

**Comment by raoufathar** [comment]
I checked it, I renamed your file from "Issue with Turn.js" to "Issue with turn.html" and modified the CSS a little and it works fine. Don't forget to keep jquery.min.js and turn.min.js in the same folder as your html file or use the proper paths while including the js files. Here is what I modified in your css:

#magazine{
    width:800px;
    height:400px;
}

#magazine .turn-page{
    background-color:#ddd;
    background-size:100% 100%;
}

**Comment by vool** [comment]
Hey Chris,

I can't seem to see what the issue is either, here are 2 suggestion as to discover what the issue is, I hope they help.

Use hosted js file, remove/comment out the links to your local files and include these lines: 

```
<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="https://raw.github.com/blasten/turn.js/master/turn.min.js"></script>
```

If this works, then it must be a problem with your local js files or the path to them.

Do you have firebug [ or similar installed ?
i have seen js get upset when calling console.log in a browser with no debugge. try commenting out that line or install firebug
`console.log('Current view: ', $('#magazine').turn('view'));`

**Comment by vool** [comment]
Chris,

I just edited your gist with those suggestions, does that work ?

https://gist.github.com/2174241

**Comment by ChrisCates** [comment]
Those changes did nothing, is it a problem that I'm doing this in a local script? Because FIrebug requires XHR calls. Despite the console.log not appearing.

**Comment by ChrisCates** [comment]
Also, now, instead of showing Test Test Test Test below each other, it shows just Test once. This means that something in turn.min.js is actually hiding the other pages. It may be working, I just don't have the bindings for turns maybe. But I thought it would be like the demo page for turn.js

**Comment by ChrisCates** [comment]
Nevermind, I refreshed the page, it's working now. My bad! Thanks everyone for your help. I appreciate it!

**Comment by blasten** [comment]
Good to know that!

**Comment by eyang414** [comment]
changing from turn.min.js to turn.js worked for me as well
