### ISSUE TITLE
Page turn from corner drag does not animate properly

### ISSUE THREAD

**Issue by BrysonZimmerman** [blasten/turn.js#314]
Clicking and dragging a corner to change the page causes the page flip animation to start over instead of continuing from the location of the corner at the time of mouse release. For example, click and drag bottom-right corner to the left about halfway and release. the page flattens back out then performs the flip animation. It should continue the flip animation from where the corner was on mouse release.

Turn.js 4

**Comment by blasten** [comment]
@gerbilOFdoom This problem has been fixed in the next update of turn.js. Please contact support@turnjs.com to see how it works now.
