### ISSUE TITLE
Chrome (25.*) on windows8 not working at all

### ISSUE THREAD

**Issue by ZennTNX** [blasten/turn.js#315]
Hi

When trying my current Turnjs project on Chrome (version 25.0.1364.172 m) on Windows 8 nothing Turnjs does seems to work. There is no curley corner, pages don't flip. No events seem to arrive anywhere. Also, as reported in issue 81, your own demos don't work. No errors are thrown.

If I send an initial page with the $.turn() function the correct page does appear, but no interaction with the book is possible.

I'm sorry I can't be more specific, and for customer-specific reasons I can't share my project now, but as your own demos won't work I hope you'll be able to resolve this issue asap, or can get back to me with an ETA for a fix. 

Thanks
Senne

**Comment by ZennTNX** [comment]
Just checked chrome on a windows 7 machine and everything works fine, so the issue really is Windows 8.
Cheers
Senne

**Comment by ZennTNX** [comment]
Ok I trace the bug down to Chrome itself. It thinks it's running on a touch device which itsn't. The test for isTouch returns a false positive.

See: http://code.google.com/p/chromium/issues/detail?id=152149

**Comment by ZennTNX** [comment]
Ok solved the issue by replacing line 27 by:
isTouch = ('ontouchstart' in window && (navigator.userAgent.match(/(iPad)|(iPhone)|(iPod)|(android)|(webOS)/i)!=null)),

**Comment by blasten** [comment]
@ZennTNX Thanks. I have tried Chrome 25.0.1364.172 and Chrome 26 on Windows 8 and Windows 7 (Virtual machine) and I haven't detected the problem. Were you using a surface? Perhaps it was a build for the device you are using.

**Comment by ZennTNX** [comment]
It's probably my Wacom Tablet that make windows 8 think it is a touch device...
