### ISSUE TITLE
Destroy not working. 

### ISSUE THREAD

**Issue by jszersze** [blasten/turn.js#319]
Hi, 

When calling $('#book').turn('destroy').remove(); I get an error "Uncaught destroy is an invalid value " on line 1855 in turn.js. 

Is there some other method to destroy the book?

**Comment by blasten** [comment]
what version are you using?

**Comment by jszersze** [comment]
It says 3rd release.

**Comment by blasten** [comment]
Destroy is available from turn.js 4th release.
