### ISSUE TITLE
jquery mobile support

### ISSUE THREAD

**Issue by AdamSurfari** [blasten/turn.js#326]
Hi,

I am having some issues running turn.js with jquery mobile, basically it seems that turn.js adds unwanted elements to the wrapper div. Take a look at http://forum.jquery.com/topic/data-enhance-false-not-escaping-dynamic-divs

with jquery only...

<quote>

<div class="turn-page-wrapper" page="37" style="position: absolute; overflow: hidden; width: 512px; height: 360px; top: 0px; right: 0px; left: auto; bottom: auto; z-index: 56;"><div style="position: absolute; top: 0px; left: 0px; overflow: hidden; z-index: auto; width: 626px; height: 626px;"><div data-enhance="false" class="turn-page p37" style="width: 512px; height: 360px; position: absolute; top: 0px; left: 0px; bottom: auto; right: auto;"><img width="512px" src="filesystem:http://localhost:8080/persistent/LEGO/CATALOGO%202013_037.jpg"></div></div><div style="top: 0px; left: 0px; overflow: hidden; z-index: 1; width: 512px; height: 360px;"></div></div>

</quote>

with jquery mobile:

<quote>

<div class="turn-page-wrapper ui-page ui-body-c" tabindex="0" style="position: absolute; overflow: hidden; width: 512px; height: 360px; top: 0px; right: 0px; left: auto; bottom: auto; z-index: 56;"><div style="position: absolute; top: 0px; left: 0px; overflow: hidden; z-index: auto; width: 626px; height: 626px; -webkit-transform-origin: 0% 100%;"><div class="turn-page p1" style="width: 512px; height: 360px; position: absolute; top: 0px; left: 0px; bottom: auto; right: auto; -webkit-transform-origin: 0% 100%;"><img width="512px" src="filesystem:http://localhost:8080/persistent/LEGO/CATALOGO%202013_001.jpg"></div></div><div style="top: 0px; left: 0px; overflow: hidden; z-index: 1; width: 512px; height: 360px; background-image: -webkit-gradient(linear, 100% 100%, 100% 100%, color-stop(0.8, rgba(0, 0, 0, 0)), to(rgba(0, 0, 0, 0.298039)), to(rgba(0, 0, 0, 0))); display: none;"></div></div>

</quote>

**Comment by alQemist** [comment]
I would look for statements containing   .addClass("ui-page") or addClass("ui-body-c")  somewhere the classes are being added by jQuery mobile I'm thinking.....

**Comment by thenewguy** [comment]
I ran into issues with jqm and turn.js too.  Had to put the flipbook on the backburner so I am interested in how you get this to work.

**Comment by AdamSurfari** [comment]
I think what is wrong is that turn.js is appending attributes instead of replacing them, so they take into account the parent, instead of simply overwriting everything. Now the issue is how do I discard the parent information and simply write the turn.js code.

**Comment by alQemist** [comment]
Seems to me that turn.js is incompatible with jQuery Mobile. Might be easier to go with the code as distributed with plain jQuery and make your tweaks from there.

**Comment by thenewguy** [comment]
Will JQM support be added to turn.js?

**Comment by AdamSurfari** [comment]
After some testing and trying to debug turn.js I was unable to have decent performance, there are multiple issues and I had to go with a different solution.

**Comment by oghenez** [comment]
@AdamSurfari  which solution did you finally use, can you share. I'm having the same issues with JQM

**Comment by davbaron** [comment]
@oghenez :  I use turn.js just fine with JQM.  However, to do so I had to 'turn off' JQM for the 'containing div' that holds all of my content for each page.  That way, JQM does not mess with the page structure and such. The 'flag' within the div looks like this:  data-enhance="false"     Will that work for you?

**Comment by oghenez** [comment]
@AdamSurfari tied that, but it did not work
