### ISSUE TITLE
Trying to implement the hashTag system

### ISSUE THREAD

**Issue by Su4p** [blasten/turn.js#33]
Hello,
I'm looking to use turn.js for a famous magazine in France.
But I'm struggling with the hash tag system.
I use :
window.pages = ['1', '2', '3', '4', '5', '6', '7', '8' .....];
window.bind('hashchange', function() {

```
        var page = checkHash();
        $('#magazine').turn('page', page);

    })
```

And I tought all I needed to do was :

div id="magazine"
        img src="pages/Livre+SP79light-1.jpg" page="1"
        img src="pages/Livre+SP79light-2.jpg" page="2"
        img src="pages/Livre+SP79light-3.jpg" page="3"
        img src="pages/Livre+SP79light-4.jpg" page="4"
        img src="pages/Livre+SP79light-5.jpg" page="5"
        img src="pages/Livre+SP79light-6.jpg" page="6"
        img src="pages/Livre+SP79light-7.jpg" page="7"
        img src="pages/Livre+SP79light-8.jpg" page="8"
div

But it's not working could you give me a hand ?

By the way your plugin is amazing,
Best regard.

**Comment by blasten** [comment]
What does the hash look like?   Is it only the page number? e.g. #1  or are you using a page name like on turnjs.com?

**Comment by Su4p** [comment]
It's only the page number but I think I solved it without understanding why it was causing trouble. I restarted from scratch and now it's working.
I have a suggestion for the new version of turn.js : It will be the zoom, allow users to zoom in by clicking on a page of the magazine and then let the cursor scroll the page automatically until the user click again to disable the zoom. -I'm trying to implement this feature-
If I'm not cleat enough you can go to  the issuu.com pageflip this feature is available, but it's flash.
Thank you for your quick answer.

**Comment by blasten** [comment]
Good to know that, BTW  hash.js could help you next time. 
https://github.com/blasten/hash.js
