### ISSUE TITLE
Turn between pages

### ISSUE THREAD

**Issue by MohamedGaber** [blasten/turn.js#335]
I want to know if it is possible to turn HTML pages (with urls) instead of turning just div elements .... that mainly to turn between ePub format book.

**Comment by alQemist** [comment]
Did you look at the Steve Jobs sample ? It uses HTML pages - but in any case the page content is always loaded into a Div container whether you have images, swf, pdf, or HTML as content pages.

**Comment by MohamedGaber** [comment]
I can't find the source code for the Steve Jobs sample. actually i will load HTML as content pages (ePub book), so could you provide me with any example for reading ePub using turn.js?

Thanks in advance for you help.

**Comment by alQemist** [comment]
Steve Jobs sample is in the turnjs download at turnjs.com - you should buy the license and get the full package

**Comment by blasten** [comment]
The div elements contains the HTML for each page.  

``` html
<div id="flipbook">
  <div> <a href="/page/2"> Here's a link in page 1</a> </div>
  <div> <a href="/page/1"> Here's a link in page 2</a> </div>
</div>
```
