### ISSUE TITLE
Ajax issue with turn.js

### ISSUE THREAD

**Issue by gauravjadhav** [blasten/turn.js#336]
Hi,

  $.ajax({
                    url: '/list-of-products/',
                    type: "POST",
                    data: {cat_id: cat_id},
                    success: function(response) {
                        var list = response.split("====================");
                        console.log(list[1]);
                        $("#themeStoryWrapper").html(list[1]);
                        //alert('ddd');
                        $('.book').turn();
                    }
                });

Above is my ajax request for book. I am getting book html properly and plugin is applying his class to my html .But I am getting following issue and book gets stuck.

Uncaught TypeError: Cannot read property 'disabled' of undefined 
Uncaught TypeError: Cannot read property 'corner' of undefined 

Can you tell me where I am wrong?

**Comment by blasten** [comment]
It's because you haven't initialized turn.js yet.  You must initialize it first.

**Comment by gauravjadhav** [comment]
I already have initialized???

**Comment by blasten** [comment]
You haven't.  You have to call `$('.book').turn();` first.

**Comment by ahmedaaziem** [comment]
Hi blasten,
I am using this plugin and have the same error.
I am using angularJs , the error doesn't appear on first document load , nor a refresh to the page.
It Only occures while load partail html on the page .
Please advise,
Highly apprecite your help.

**Comment by Durga1987** [comment]
```
    jQuery("#flipbook").turn("page", pageno);
        jQuery(".flipbook").turn();
```

not working in ng-click i m calling iti is TypeError: Cannot read property 'disabled' of undefined 
what to do?

**Comment by Durga1987** [comment]
not working

**Comment by ghost** [comment]
initialized:::     $("#flipbook").turn('page',1);
