### ISSUE TITLE
Previous page controls

### ISSUE THREAD

**Issue by chandusmax** [blasten/turn.js#341]
I am using turn.js (ver.4) in a Android Mobile Application.
While I am taping on a page,  back side controls of the previous page are
been selected.
Please suggest me to overcome this problem.

**Comment by blasten** [comment]
The controls should have these css rules:

``` css
-webkit-touch-callout: none;
-webkit-user-select: none;
-khtml-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
```
