### ISSUE TITLE
using hash.js problem

### ISSUE THREAD

**Issue by janslyn** [blasten/turn.js#346]
Hi,
I'm trying to setup a wordpress-driven magazine, us ing a setup similar to the "double-page" example in the download package, except i need the possibility to flip between the pages, using the browser back-button also. 
I've added this:

when: {
                turning: function(event, page, view) {

```
                var book = $(this),
                currentPage = book.turn('page'),
                pages = book.turn('pages');

                // Update the current URI

                Hash.go('page/' + page).update();




            }
```

under events, and the url updates exactly as it's supposed to - the only problem is - the page doesn't flip. 
Maybe someone can point me in the right direction?

**Comment by blasten** [comment]
You probably have to load hash.js `<script src="js/hash.js" type="text/javascript"></script>`
