### ISSUE TITLE
Wait until page images are render

### ISSUE THREAD

**Issue by hanskait** [blasten/turn.js#355]
Hi!, i'm working with a book that works offline, that has only images (png/jpg) as contents.
My problem is when a page is turned, images starts to appear in order. I think the problem is image size. The average per page is 3 MB.
It could be posible to control the images are totally rendered until the page is show?.
Thanks!

**Comment by alQemist** [comment]
I think you should consider downsampling the images to be more suitable for online viewing - we have a rule of thumb no page larger than 500KB for best results.....Hi-res images are overkill for online viewing

**Comment by hanskait** [comment]
hi alQemist, the book only works offline.
Thanks

**Comment by alQemist** [comment]
I said "online" but really its an issue of optimizing for screen display - anything over 72dpi for PC and 96dpi for Mac is overkill for viewing (retina displays being an exception)

**Comment by hanskait** [comment]
Another suggestion?

**Comment by renfufei** [comment]
6*3MB = 18MB,so the memory used maybe 100MB+. You should consider to modify the turn.js for your version fit your app.Such as 4 pages in dom.
