### ISSUE TITLE
Placing Large HTML content dynamically

### ISSUE THREAD

**Issue by abishekrsrikaanth** [blasten/turn.js#379]
I am not sure if this is something that has already been discussed, I tried searching on the list of issues but could not find anything related to it.

I have a large HTML content that I need to bind using turn.js. The problem I have is that,  with turn js, I will have to split the HTML into seperate div tags as pages. Is there a way in turn.js to bind the content on a div and it takes care of automatically wrapping to different pages based on the content that is being bound?

Or is there a way to know how much data needs to be bound to each page to get this scenario working

**Comment by blasten** [comment]
Hi @abishekrsrikaanth 

The next API has this feature. It's called the Fragment API. (sort of css regions) It allows to load chunks of HTML code and dynamically flows content among pages.  Stay tuned!

**Comment by abishekrsrikaanth** [comment]
Cool stuff, will look forward to this.

**Comment by ricccrd** [comment]
@blasten when you expect to be available this Fragment API verision? Thanks.

**Comment by blasten** [comment]
End of Sept.

**Comment by vickygohil** [comment]
Looking forward to the update !

**Comment by abishekrsrikaanth** [comment]
same here.

**Comment by philiphacks** [comment]
Is there an update on this? Is this Fragment functionality already available?

**Comment by ramisback** [comment]
any updates regarding fragment api?
