### ISSUE TITLE
Page shakes when corners hovered

### ISSUE THREAD

**Issue by jeitnier** [blasten/turn.js#39]
Has anyone else encountered this?

I'm using turnjs in a personal project and I've found so far that in FF 11 & IE 9 the page of a hovered corner "shakes" until the corner animation is completed. Basically the shaking is about 1 pixel back and forth to the left or up and down. IE shakes significantly less than FF but it still does.

Any solutions? I love this plugin and wanna keep using it.

**Comment by blasten** [comment]
Yes! There's a problem with that, it's one pixel. I believe it's fixable. I Hope to fix this problem in the next release.

**Comment by FlashJunior** [comment]
+1

**Comment by cipnt** [comment]
+1 though I can live with it :)

**Comment by jolavesen** [comment]
For me, it seems the shaking is minimized if the div containing the background image content is styled with margin:0 and padding:0;

**Comment by blasten** [comment]
@jeitnier  actually there's not shaking when the div only contains a background image,  the problem is with HTML content. It's a browser issue.

**Comment by vgaemagapp** [comment]
Hi guys who have any ideas how fix this issue ?
