### ISSUE TITLE
Resizing the book

### ISSUE THREAD

**Issue by mpcreation** [blasten/turn.js#4]
Hi, I am trying to force the book to resize when I resize the browser window. I have tried changing the width and height of the book container  through jQuery. It didn't worked so I tried to change the dimensions of each page but it messes up the flip animation, any hint would be great ;) Also I am not sure how the turn('resize') works.. some more inside would be cool ;)

**Comment by ghost** [comment]
I'm interested in exactly the same thing

**Comment by blasten** [comment]
Hello, turn.js has a new method and property, it's called `size`.
Check it out here: https://github.com/blasten/turn.js/wiki/Reference.

The constructor also have both width and height parameter.
