### ISSUE TITLE
creating bookmarks & pulling page # info

### ISSUE THREAD

**Issue by joeker630** [blasten/turn.js#40]
I am trying to create a website that using turn.js and allows for users to create bookmarks. I am having trouble implementing the alert($('selector').turn('page')); to have it display on screen the current page # the reader is on. When I try to do something like

document.write($('selector').turn('page')); 

it break the bookflipping aspect and either shows nothing or shows the text in standard paragraph form. 

Where I am supposed to add the alert($('selector').turn('page')); code to display the current page #? Is there a way to grab the page # from the actual CSS when I turn "pagenumbers = true" ? 

Please help!

**Comment by blasten** [comment]
`document.write` called after the document object was closed would definitely create a new empty document, therefore it's not possible to use `document.write` at that point.  If you want to show the current page, I would recommend to use `$('selector').turn('view')`, which is an array, so you have to give a sort of format. You can read that value in one event called `turned` 

 `$('selector).bind('turned', function() { alert($(this).turn('view'));});`, for instance.

**Comment by jedahan** [comment]
You can also use `page` in the turned event, though you may want to massage this number `$('selector').bind('turned', function(e, page) { alert(page); }`
