### ISSUE TITLE
slowing down page turn effect

### ISSUE THREAD

**Issue by rimareda** [blasten/turn.js#41]
hi blasten,

can we change the timing of the page turn? i'm interested in slowing it down very slightly. the minified script is so jumbled that i couldn't figure out where the property is. would you consider making the timing a customizable option?

thank you so much for all your help, and again for your lovely plugin :)

**Comment by brandonHeaslip** [comment]
Its actually very easy to understand and make modifications too. Go to your turn.js file and look for the number 600. It should be on line 45 of the code. Change the 600 to 800 or more to get the effect you are looking for. Hope this helps. 

Oh and by the way Blasten your plugin rocks! 
Thank you for sharing this.

**Comment by rimareda** [comment]
that's exactly what i was looking for, thanks so much!

**Comment by tvanassche** [comment]
There's no need to change the plugin-code for this, turn.js already provides an option to do this when initialising the book. Simply add "duration: xxx" to the init-settings.

For example: <i>$magazine.turn({ width: 800, height: 500, page: 1, duration: 1500 });</i>
