### ISSUE TITLE
Can the next version be submitted this week?

### ISSUE THREAD

**Issue by zhangzhzh** [blasten/turn.js#42]
Hi, blasten.

it seems it's the last day of this week.

Additionally, I think you should refer to the componentone's book widget. The demo is  http://demo.componentone.com/Silverlight/ControlExplorer/#Book/See%20it%20in%20action

**Comment by blasten** [comment]
The new version is available. If you are looking for dynamic pages, there is a sample called Bible.

**Comment by anherdene** [comment]
nice work.
