### ISSUE TITLE
go to page js error data

### ISSUE THREAD

**Issue by steve4891** [blasten/turn.js#423]
I'm using turn.js 3rd and everything works fine but i have a problem with go to page.

i use turn('page',number_of_page) to go to a specific page and randomly it stop to work..

it gives me "TypeError: data is undefined".  on _eventMove

is it a bug or there is something that am i wrong? i'm using sucesfully buttons to turn next and previews pageand it works fine with no problem..

thanks in advance

**Comment by TimOgilvy** [comment]
Are you binding the turn event inside a ready function?  Most times that I've encountered this error I've been calling it out of scope...

**Comment by steve4891** [comment]
thanks for responde..

i create the book inside document ready function... but then when i click the button or change the value in the input field it's an onchange function or click function so it should be already loaded everything..

and the functions call simply $('#flipbook').turn('page', n_page);

am i wrong anything?

**Comment by steve4891** [comment]
found the error if anyone is interested

we got a quick wok around for the problem:
in the function '_end' :

else {
            turnMethods._removeMv.call(turn, opts.pageMv);
            turn.turn('update');
        }

comment off this line:

turnMethods._removeMv.call(turn, opts.pageMv);

This will work :) if you can respond why, that would help a lot.
Thanks!
