### ISSUE TITLE
Turning pages with images - v3

### ISSUE THREAD

**Issue by jonathandey** [blasten/turn.js#43]
The pages within my ebook are just images and when I first load the site and come to turn the page, the page after doesn't seem to have rendered the image, so on the page turn effect there is nothing on the next page until I finish turning and the image is loaded.
Although once I've flipped through the whole book and go back through, everything is rendered and works correctly.

If I use your previous version everything works great! You've done some excellent work and I hope this issue helps you improve future versions.

I probably should add I'm using jQuery to append the images into the div's so they are actually empty at first. I'll go away and try adding them using your new addPage method to see if that fixes it though.

**Comment by blasten** [comment]
Please let me know.

**Comment by jonathandey** [comment]
Is there an 'onready' event?

**Comment by blasten** [comment]
No, however the `ready` state happens after calling the constructor. 

I was testing turn.js with images and it seemed to be working. Actually, if all your pages are in the element you are using for turn.js, all the page images will be downloaded.  I will recommend you to use `addPage` if your ebook contains more than 6 pages.
