### ISSUE TITLE
turnjs.com demo left hand page transition is off.

### ISSUE THREAD

**Issue by rlemon** [blasten/turn.js#44]
In the demo the left side page is appearing approximately 100px higher than the right side page during the transition. 

See the image: http://pi.rlemon.com/image/1d28cd835a4163312d100e54b69a65fc.png

This appears on:
Google Chrome   18.0.1025.142 (Official Build 129054)
OS  Linux
WebKit  535.19 (@111933)
as well as
FireFox 11.0
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:11.0) Gecko/20100101 Firefox/11.0

**Comment by blasten** [comment]
Thank you for let me know about the problem!  It's fixed!

**Comment by jonathandey** [comment]
I'm still getting this problem on your site. However when I go through the whole book then back through it, its fixed!

**Comment by rlemon** [comment]
I can also verify this behavior; On the first rendering of each page I get the position issue. If I flip back and fourth between pages after the page has been viewed at least once it works. Refresh the page and i'm back to square one.

**Comment by blasten** [comment]
Are you still having the same problem? I found the problem, and it was a CSS problem.

**Comment by jonathandey** [comment]
No I didn't manage to get it working, what will I need to do in the CSS?

**Comment by blasten** [comment]
The problem was on turnjs.com, the library is perfectly working.

**Comment by rlemon** [comment]
Fixed for me.

**Comment by blasten** [comment]
:)

**Comment by 20562471** [comment]
I still have this problem, what needs to be changed? Thanks

**Comment by rlemon** [comment]
you mean you still have the problem on the turnjs.com website?

**Comment by 20562471** [comment]
No on the one I am trying to create.

**Comment by rlemon** [comment]
this issue was specific to the website. if you are having issues with your own script this issue is not the place. you can review the website and see what changes were made.

**Comment by 20562471** [comment]
The only thing I have used from the website is the turn.js file :/

**Comment by rlemon** [comment]
You're supposed to use the file from the github repository. In any case **this is not the place to get support for this**.
