### ISSUE TITLE
Show depth on the page edge of the book

### ISSUE THREAD

**Issue by roots-ai** [blasten/turn.js#445]
https://github.com/blasten/turn.js/issues/260
I tried to do the same by keeping the .own-size class on the covers, but the "display" gets set to "none" for the 'cover pages' on navigating through the book. Why is it happening like this?

**Comment by roots-ai** [comment]
I had to class 'fixed' to the covers.

**Comment by weituotian** [comment]
@roots-ai may i ask hot to deal with it?
