### ISSUE TITLE
Start with book opened

### ISSUE THREAD

**Issue by MichaelKubovic** [blasten/turn.js#45]
It would be nice to have an option to start book opened, i.e. http://wp.saryx.sk/ocelove-konstrukcie

For now I hacked this by putting line:
if(opts.next == 1) return null;
after line 1271 and starting book on page 2 instead 1. Of course blank first page has to be created as well.

**Comment by blasten** [comment]
You can set the page in the options when you create your book.  e.g.  `$().turn({page:2});`    Additionally, you can add listeners for the start and turning events and prevent the default action when the page requested is 1.

**Comment by MichaelKubovic** [comment]
better?

``` javascript
$(document).ready(function() {
        $('#book').turn({page: 2});
        $('#book').bind('start', function(e, data, c) {
            if(data.next == 1) {
                e.preventDefault();
            }
        });
        $('.p2').unbind('pressed');
    });
```

**Comment by blasten** [comment]
Looks great!

**Comment by rvernica** [comment]
What is the role of

``` javascript
$('.p2').unbind('pressed');
```

here? Thanks!
