### ISSUE TITLE
turn.js 4.1.0 peel effect doesn't work on chrome, chromium (38), and opera (22) on windows 8.1

### ISSUE THREAD

**Issue by ka7eh** [blasten/turn.js#458]
It works fine on Linux and OS X (Firefox, Chromium, Safari); it also works fine on Firefox, Safari, and IE11 on Windows 8.1, though there's no peeling effect in Chrome (35), Chromium, and Opera on Windows 8.1
The script is loaded correctly, cause the "page" method works, but not the "peel" effect. (a css problem?)

Also, is there anyway to specify the flip effect? Right now it flips in two way, one from corners, the other from sides.

Would appreciate any help.

**Comment by ka7eh** [comment]
I found the problem, my screen was touch and the new Chrome and Opera on Windows disable the mouse events and only allow touch events (?). There's the same situation with the demo page on turnjs.com. I disabled the touch events on my browsers, but i'd like to have both events available simultaneously. I don't know that much about the touch events; I played a little with touch-action property, but had no luck. Any hint?

**Comment by Rollo62** [comment]
Dear ka7eh,

any success with this ?

Rollo

**Comment by ka7eh** [comment]
I finally got back to this issue today. I modified turn.js a bit and now it works for me and I have the peeling effect on both the mouse and touch events.
Here are my mofications:
- line 28:
  <pre class="source">
  mouseEvents = (isTouch) ?
  {
    down: 'touchstart mousedown',
    move: 'touchmove mousemove',
    up: 'touchend mouseup',
    over: 'touchstart mouseover',
    out: 'touchend mouseout'
  }
  :
  {
    down: 'mousedown',
    move: 'mousemove',
    up: 'mouseup',
    over: 'mouseover',
    out: 'mouseout'
  },
  </pre>
- line 2022:
  <pre class="source">
  e = (isTouch && e.originalEvent && e.originalEvent.touches) ? e.originalEvent.touches[0] : e;
  </pre>
- line 2898:
  <pre class="source">
  e = (isTouch && e.originalEvent.touches) ? e.originalEvent.touches : [e];
  </pre>

I just tested it on Chrome under Windows. No idea about other browesrs/devices.

**Comment by Mcloud965** [comment]
Thank you very much Ka7eh, I'm looking to use this for a project and Chrome support was essential, can confirm your fix for chrome v37 on windows 7.

**Comment by JulienReignier** [comment]
@ka7eh : Thanks for this fix man. Nice job !
@Mcloud965 : This fix is not OS-specific, it's to handle both touch and mouse events when you're using a touch screen device with a pointer device (mouse, pen...).

**Comment by corrspt** [comment]
Thanks a lot @ka7eh I also had this problem and your solution works like a charm.

**Comment by jackson13108** [comment]
Thank @ka7eh. Nice job

**Comment by infiniBalki** [comment]
Hi @ka7eh, Thanks for the fix - that work well with the flip function, but the **zoom on double click** on the page and **page movement** got arrested - can I request you to help me out with that.
