### ISSUE TITLE
 To turning right magazine

### ISSUE THREAD

**Issue by niconicora** [blasten/turn.js#466]
I don't understand your question, are you asking how you turn the page right, or how you get language to display RTL instead of LTR?

**Comment by niconicora** [comment]
My version is 4th release

**Comment by natedsaint** [comment]
I don't understand your question, are you asking how you turn the page right, or how you get language to display RTL instead of LTR?

**Comment by niconicora** [comment]
Thank you for reply.

Was self-resolved.

I did not notice the simple things

```
<script type = "text / javascript">
$ ('# magazine'). turn ({
page: 6, ← I write the last page
display: 'double',
acceleration: true,
gradients:!. $ isTouch,
elevation: 50,
when: {
turned: function (e, page) {
/*console.log('Current view: ', $ (this) .turn (' view ')); * /
}
}
});
</ script>
```
