### ISSUE TITLE
Totally messed up

### ISSUE THREAD

**Issue by NaderIkladious** [blasten/turn.js#467]
Its not working as in the demos
the flipping animation is messed up and it crashes and lags 
I dont know what is wrong or what is missing
and even the corner hovers don't work or the dragging thing.
I have added the arrows JS lines to flip using the arrows but it crashes the page every time.

any help ?

**Comment by NaderIkladious** [comment]
anyone ?

**Comment by NaderIkladious** [comment]
i found out that i used a recursive selector to initialize the book
('#book div')

**Comment by natedsaint** [comment]
In the future if you want help with this quickly provide a code example (link to your site, jsbin, codepen, whatever) otherwise we just have to guess what you're doing.
