### ISSUE TITLE
How can i use tabs as in the online demo

### ISSUE THREAD

**Issue by NaderIkladious** [blasten/turn.js#468]
is it possible to use tabs?
i searched the documentation for how to use it ..
and there was nothing about it .,

how can I do it ?

**Comment by natedsaint** [comment]
http://www.turnjs.com/get will get you access to the example code.

**Comment by NaderIkladious** [comment]
@natedsaint  so I have to get a licence to use the tabs ?
sounds weird to me

**Comment by natedsaint** [comment]
The tabs are not part of the api, they're an implementation of it. He made
custom code to wrap the viewer that calls the api methods to turn the
pages. You don't have to pay to do the same thing but if you want the
source to a usable implementation he wrote over an api you are getting for
free, it sounds fair to me to pay him for that work.

**Comment by NaderIkladious** [comment]
ohh I got it 
sounds fair now 

Thanks so much :)
