### ISSUE TITLE
Book closed, snap to center

### ISSUE THREAD

**Issue by 20562471** [blasten/turn.js#47]
Hello on your demo at http://www.turnjs.com/ your book snaps into place when its closed how have you done this? Also you have used arrows that appear to the left and right how have you done this? 

Thanks

**Comment by jedahan** [comment]
view the source, luke!

(css is powerful)

**Comment by blasten** [comment]
I believe it will be necessary an option to center the book in future releases.

**Comment by 20562471** [comment]
I have looked over the css and tryed implementing it however it doesn't work! I have also attempted to snap the book to centre when opened and closed and that doesnt work either.

**Comment by blasten** [comment]
Well, what you can do is to change the margin-left or left property of your magazine, and it will depend on the current page.

**Comment by 20562471** [comment]
I have done this and nothing seems to happen :/ Thanks for the help though.

**Comment by blasten** [comment]
@20562471, the next version will include that function.`
