### ISSUE TITLE
IE9 - corners hard to see

### ISSUE THREAD

**Issue by ghost** [blasten/turn.js#49]
Hi, good work on the new release.

I've noticed that if you hover over a page corner in IE9, and the next page is the same colour as the one you are on, you cannot see the corner fold down (basically it's the same colour as the background it's going over). I've got a quick workaround for now where I add a border to the page, but it's a bit hacky. Do you have any other recommendations?

Here's what I'm using at the moment, it's crude, but makes it bearable:
# book .odd {

```
border: 1px solid #ccc;
border-width: 1px 0 1px 1px;
```

}
# book .even{

```
border: 1px solid #ccc;
border-width: 1px 1px 1px 0;
```

}

**Comment by blasten** [comment]
Thank you.  I'm currently working in a better version for IE.  It's rare that the gradients are not working for IE, because the new release includes support of gradients for all modern browsers including IE.  I hope to fix all the problems very soon.
