### ISSUE TITLE
Chrome 38 and 39 breaking Turn JS and your TurnJS.com website.

### ISSUE THREAD

**Issue by closdesign** [blasten/turn.js#492]
Hey guys, sent you all an email to support@turnjs.com but I did not know the fastest way to get a hold of you.
We have used Turn JS 4 paid version for some projects for the past couple of years.  HOWEVER, I recently updated Chrome to Version 38 and most recently Version 39, but suddenly the Turn JS solutions broke. **Even your website demos are not working**.  I disabled extensions thinking that was an issue, but that is not the case.
Mainly, it seems the Zoom feature specifically when an OnClick Is triggered for the Zoom on the page itself, the page does not zoom.  

I has someone else do a test and the same issue is happening with them with the latest version of Chrome.  

I was wondering if you knew about the break or if there is a solution, can you post it ASAP. We have many Live items using your product and need a fix.  
I tried changing out the version of jQuery from 1.8 to 1.9 and even 1.11, but this still did not fix the issue.  Was wondering if you could take a look and see if there is a fix.

**Comment by RPSource** [comment]
I created a flipbook about 3-4 weeks ago and it seems to be holding up on both OSX and Win in Chrome 38 and 39.

The pages zoom fine, except for some minor graphical glitches it works for me I am curious what page you are trying cause the turnjs website demos work for me too and I'm using both Chrome 39 and Chrome Canary.

**Comment by closdesign** [comment]
@RPSource Hmm. That is odd, I had another developer test on his version of Chrome too. Not sure what the issue is. Turn JS 4?

**Comment by closdesign** [comment]
Can you check out ours on your machine?  Just by chance if you have a minute?  The click on page and zoom feature doesn't work and the corner drag, and the zoomed page drag around does not work.
http://apps.dmns.org/Catalyst/October-November2014/index.html

**Comment by RPSource** [comment]
Ofcourse let me know if you want the video remover but for now have a look at my experience:
http://youtu.be/trZKPkipmNc

**Comment by closdesign** [comment]
@RPSource Did you happen to test it on a PC and got the same thing?  If so, I wonder if my version of Chrome is blocking something.  I just tested on a Mac too with Chrome 39 and it worked.  thanks for doing that screencast. Much appreciated.

**Comment by closdesign** [comment]
Ugg. So I got this to finally work on Chrome 39. Had to uninstall Chrome 3 times.  Probably some caching issue or something. Who know. @RPSource Thanks for checking on this for me.
