### ISSUE TITLE
Is the single page mode cool?

### ISSUE THREAD

**Issue by zhangzhzh** [blasten/turn.js#50]
Nobody talk about the new single page mode, and no demos about it. 

Is the flip effect in the single page mode cool?

**Comment by blasten** [comment]
Thanks for talking about the single page mode!  You right, there's not demo yet.  Try to make one!

**Comment by idlesysop** [comment]
I just tested the single page and there appears to be a bug on touch devices when it gets to the last page.  Once on the last page, you can't turn the page back to the previous page.  Tested on iPad iOS5.  Looks like this also happens in chrome for desktop.  Once you get to the last page, if you hover over the top left corner (do not click) and then hover over the top right corner, the top right corner becomes active (when it shouldn't) and there's js errors thrown referencing line: 1563 of turn.js.

**Comment by jeremangnr** [comment]
hey @blasten! great work with turn.js, i've been using it at work and it looks really slick. i have only one "issue" with single page mode. is there a way to remove the "extra" page that gets added? i mean, could we switch to previous and next pages in the same page, without needing an additional empty page?

**Comment by blasten** [comment]
@jeremangnr The peeling effect needs another page in single mode because all the pages will be in the same location.  But let me know the idea you have.

**Comment by blasten** [comment]
@idlesysop  thanks for your contribution.

**Comment by idlesysop** [comment]
No problem, glad I can help.  Thanks for making this plugin.  If I find any other bugs, I'll fix and create another pull request.  Let me know if I can help with anything else.

**Comment by jeremangnr** [comment]
as a temporary hack (i needed this quickly for work) i just resized the book to half it's size and so that the "extra" page overlaps the actual page... that way you can switch back and forth just like if it was all on the same page.. nasty hack but worked nicely... I read somewhere that you were planning to add a right to left mode too?? i had to do this too and it's not really complicated, if I have time next week i'd love to get in on that

**Comment by zhangzhzh** [comment]
Can't turn from right to left in the single mode? then after turned a page  from left to right, how to turn it back?

**Comment by idlesysop** [comment]
@zhangzhzh try the demo at https://github.com/idlesysop/turn.js/tree/master/demos/magazine_single

If that works for you, grab the turn.js/turn.min.js from that fork.

Please let us know whether or not it works for you.

**Comment by postonoh** [comment]
How do you get the single page to work on the IPAD

**Comment by katsu0bushi** [comment]
The animation when returning is strange.
