### ISSUE TITLE
RTL Book direction

### ISSUE THREAD

**Issue by ShadyNawara** [blasten/turn.js#51]
hi i was just wondering how to make this work in RTL direction
Thank you.

**Comment by blasten** [comment]
that doesn't work yet.  I hope to include that feature very soon.

**Comment by jedahan** [comment]
I've hacked around this by putting the divs in the reverse order, turning to the 'last' page upon page load, and when keeping track of the page, just subtracting from the total number of pages.

**Comment by mohamedali** [comment]
please an example with code thank you

**Comment by blasten** [comment]
@shandoosheri Now turn.js 4th supports RTL direction. Check that out on turnjs.com
