### ISSUE TITLE
using IE9 the flipbook is crashed

### ISSUE THREAD

**Issue by joellesleimen** [blasten/turn.js#515]
please any update on the crashing using IE9

**Comment by alQemist** [comment]
Do you have any more details ? are your tracing your events in the console.log ? can you share that info here ? Without more information I would be surprised if you get any responses.

**Comment by joellesleimen** [comment]
Follow this link and open it in IE9: http://staging.mindfieldsolutions.me/eBook/index.html 

please advise

Regards;

Joelle Sleiman

Digital UI Developper
MindField Digital 
Badaro Street, Buick Corner

Khoury Bldg, 3rd floor

P.O.Box 14-5679 Beirut, Lebanon

Tel:  +961 1 423955 Ext. 112

Mobile:  + 961 71 107845 

Support: +961 71 146463
Email:  mailto:j.sleiman@mindfield.co j.sleiman@mindfield.co
Website:  http://www.mindfield.co/ www.mindfield.co

Follow Us:   http://twitter.com/mind_field    http://www.facebook.com/mindfieldsolutions    http://www.linkedin.com/company/mindfield-solutions-s.a.r.l 
P Protect our planet: do not print this email unless necessary

**Comment by alQemist** [comment]
Don’t have IE - but here are issues that might be related to your problem….displays the cover but nothing else works….

**Comment by joellesleimen** [comment]
There is any solutions for this bug?

Regards;

Joelle Sleiman

Digital UI Developper
MindField Digital 
Badaro Street, Buick Corner

Khoury Bldg, 3rd floor

P.O.Box 14-5679 Beirut, Lebanon

Tel:  +961 1 423955 Ext. 112

Mobile:  + 961 71 107845 

Support: +961 71 146463
Email:  mailto:j.sleiman@mindfield.co j.sleiman@mindfield.co
Website:  http://www.mindfield.co/ www.mindfield.co

Follow Us:   http://twitter.com/mind_field    http://www.facebook.com/mindfieldsolutions    http://www.linkedin.com/company/mindfield-solutions-s.a.r.l 
P Protect our planet: do not print this email unless necessary

**Comment by joellesleimen** [comment]
hii please any help?

**Comment by zishanj** [comment]
@joellesleimen  I have checked your link on my IE 9.0 and it seems to be working fine. Pages can also flip and navigation buttons also working.

**Comment by joellesleimen** [comment]
Yes its true because I fixed the problem.

Thanks anyway

**Comment by imran-withuspothe** [comment]
can you please close this issue or mark as solved? because you are saying you have fixed the problem

**Comment by joellesleimen** [comment]
For sure :)

Regards;

Joelle Sleiman

Digital UI Developper
MindField Digital 
Badaro Street, Buick Corner

Khoury Bldg, 3rd floor

P.O.Box 14-5679 Beirut, Lebanon

Tel:  +961 1 423955 Ext. 112

Mobile:  + 961 71 107845 

Support: +961 71 146463
Email:  mailto:j.sleiman@mindfield.co j.sleiman@mindfield.co
Website:  http://www.mindfield.co/ www.mindfield.co

Follow Us:   http://twitter.com/mind_field    http://www.facebook.com/mindfieldsolutions    http://www.linkedin.com/company/mindfield-solutions-s.a.r.l 
P Protect our planet: do not print this email unless necessary

**Comment by imran-withuspothe** [comment]
thanks.
