### ISSUE TITLE
The steve Job example is not working 

### ISSUE THREAD

**Issue by tameisha** [blasten/turn.js#516]
When I used the offline version of the Steve Job example, the html pages are not working all I am seeing is the loading sign. I change the acceleration to false and it still does not work. I used google chrome and firefox 
Please help

**Comment by tameisha** [comment]
i found the solution by following someone else earlier post. I used xampp

**Comment by yomjaiswal** [comment]
> i found the solution by following someone else earlier post. I used xampp

how did you solve that ?
