### ISSUE TITLE
Compatibility with transform:rotate?

### ISSUE THREAD

**Issue by billsinc** [blasten/turn.js#53]
I'm having a lot of fun with this plugin!

I'm am, however, having an issue with adding a "transform:rotate(XXdeg)" element in my CSS style.  Some of my pictures are rotated a number of degrees (positive and negative) and when this happens images from other pages start coming through and the body background turns blue.

Any thoughts?

**Comment by blasten** [comment]
I have to check that out, are the images inside the page?

**Comment by billsinc** [comment]
Yes, some intentionally cross the spread in the middle though.

**Comment by billsinc** [comment]
This is what my php is generating:
```<img style="-webkit-transform: rotate(6.3025785817042deg);" src="image.jpg" alt="image" width="23.388367891312%">

```
```

**Comment by blasten** [comment]
In which browser are you getting that behavior? I tested it on Chrome/Safari, Firefox, and I didn't get any issues.

**Comment by billsinc** [comment]
Odd. I'm getting it in Chrome. Could it be a function of the size of the images I'm using?  I'm using some pretty large images for performance testing. 

On Apr 16, 2012, at 1:50 PM, "Emmanuel Garcia" reply@reply.github.com wrote:

In which browser are you getting that behavior? I tested it on Chrome/Safari, Firefox, and I didn't get any issues.

---
