### ISSUE TITLE
use edge instead the corner

### ISSUE THREAD

**Issue by agungshiro** [blasten/turn.js#54]
Is that any solution for using the edge ( left or right ) instead the corner to initiate the flip

**Comment by blasten** [comment]
It's not possible yet, the next release will help you!

**Comment by blasten** [comment]
Turn.js 4th release allows you to do this with the new 'peel' method.

**Comment by nelsonvassalo** [comment]
Hi @blasten, how exactly can we do this? I'm using 'all' as the value for corners option, and it still only shows my top and bottom corners as 'flippable'. It is a single view magazine without hard covers

**Comment by nelsonvassalo** [comment]
Could be simple as adding a case for 'r' and 'l', right?

``` javascript
switch (point.corner) {
        case 'l' :

        break;
        case 'r' :


        break;
        case 'tl' :
          point.x = Math.max(point.x, 1);
          compute();
          transform(tr, [1,0,0,1], [100, 0], a);
        break;
        case 'tr' :
          point.x = Math.min(point.x, width-1);
          compute();
          transform(point2D(-tr.x, tr.y), [0,0,0,1], [0, 0], -a);
        break;
        case 'bl' :
          point.x = Math.max(point.x, 1);
          compute();
          transform(point2D(tr.x, -tr.y), [1,1,0,0], [100, 100], -a);
        break;
        case 'br' :
          point.x = Math.min(point.x, width-1);
          compute();
          transform(point2D(-tr.x, -tr.y), [0,1,1,0], [0, 100], a);
        break;
      }

```

**Comment by weituotian** [comment]
@blasten so how to deal with this?

**Comment by weituotian** [comment]
@nelsonvassalo is there an example?

**Comment by weituotian** [comment]
@blasten @nelsonvassalo 
you can check `https://book.yunzhan365.com/kykh/ivps/mobile/index.html` 
it is a book website in china. it can initiate the flip from edge, 
and it is very better than turn.js
@blasten hou could you not  to improve the turn.js?
