### ISSUE TITLE
Request on update for current licensing status in 2016

### ISSUE THREAD

**Issue by tdmalone** [blasten/turn.js#548]
Does anyone know the current licensing status of turn.js? Version 4 appears to be freely available on the website, however there are inconsistencies on whether a license applies for commercial use (for either version 3 or version 4):
- The Download link on the website links to version 4, just above the Github link
- The licensing comment on the website (http://turnjs.com/#licensing) refers to a BSD license and states the project is available on Github, however it also states that the license doesn't cover the version 4 release (the link to the v4 release PDF appears to be broken)
- The version 4 download ZIP contains no licensing information, however it does refer to the 'commercial version' in the API docs contained within
- The Github page states version 3 is available under 'a non-commercial BSD license'
- In this issue - https://github.com/blasten/turn.js/issues/61 - the author states commercial use is ok with an MIT license
- In this issue - https://github.com/blasten/turn.js/issues/342 - the author states commercial use requires purchasing a license

There are a number of open issues covering licensing, these include:
- https://github.com/blasten/turn.js/issues/491
- https://github.com/blasten/turn.js/issues/488
- https://github.com/blasten/turn.js/issues/486
- https://github.com/blasten/turn.js/issues/474
- https://github.com/blasten/turn.js/issues/473
- https://github.com/blasten/turn.js/issues/464
- https://github.com/blasten/turn.js/issues/287

From these, it appears the author is no longer supporting the project nor responding to issues or e-mails; however he is still active on Twitter (https://twitter.com/blasten). He now appears to work for Google.

Last month he asked a Twitter user to contact him by e-mail to enquire about licensing (https://twitter.com/blasten/status/698610530538254336).

I've e-mailed Emmanuel enquiring about licensing for a commercial project and haven't heard back; I've just tweeted him today and will update this issue if I hear back from him.

If anyone else knows what the correct licensing status of this project is, please do share!

_Other relevant links (quite possibly old and no longer in use as they are no longer linked from the home page):_
- Licensing purchase system: http://turnjs.com/get
- Licensing docs on wiki: http://turnjs.com/docs/Licensing

**Comment by sergejkaravajnij** [comment]
I join the request. Also interested in.
Please update if you receive the news.

**Comment by IvoJager** [comment]
Same here - tried contacting author about license confusion a couple of weeks ago, but have not received a reply as of yet.

**Comment by tdmalone** [comment]
Emmanuel hasn't been active on Twitter or Github for the last week, so I'll try to tweet and e-mail him when he's active again, with a link to this issue. Appreciate you guys putting your hands up too!

**Comment by marvindanig** [comment]
Hello guys, just so that you know: this library is likely open source but unmaintained. 

 Mybridge (@Mybridge) tweeted at 7:30pm - 4 Mar 16: 

Turn.JS: Open source #JavaScript library to make a flip book. Courtesy of @blasten #HTML5 bit.ly/1p5QJb1 pic.twitter.com/25s0Wj8jsq (https://twitter.com/Mybridge/status/706596529276981248?s=17) 

Hope it helps.

**Comment by mybridge-monthly** [comment]
Thanks for letting us know Marvin!

**Comment by IvoJager** [comment]
Thanks for that Marvin. Unfortunately "Open Source" does not mean that the code therefore is unencumbered by a license. There are many different licenses that permit you to do different things, depending on how (or even _if_) you intend to use the code.

We just really want/need to know what the our obligations are if we would like to use this code.

**Comment by marvindanig** [comment]
Given that the tweet from @mybridge was only retweeted by @blasten it cannot still be inferred or assumed that the library is open source or available under a suitable license.

**Comment by tdmalone** [comment]
It _is_ open source - given we can see the source now ;) - but the confusion is around the license, especially for commercial use (and perhaps even what defines commercial use).

**Comment by tdmalone** [comment]
Oops sorry, I'm going to have to correct myself there. I've just done some reading through https://opensource.org/ & http://choosealicense.com/. See also https://www.quora.com/What-is-the-best-free-for-non-commercial-use-license-to-use-for-an-open-source-project & http://www.infoworld.com/article/2611422/open-source-software/github-finally-takes-open-source-licenses-seriously.html.

It appears this project is currently _not_ open source but the author has chosen to make it available for non-commercial uses. As far as I'm aware, adding it to Github explicitly gives others the right to fork it (via Github license agreement), but still not neccessarily to use it as open source.

It still remains unclear how to purchase a commercial license, given the purchase link is not actually available from the home page anymore (I would be reluctant to send my money there not knowing if it is working and if the author is responsive).

I'm still keeping an eye on Emmanuel's activity on Github/Twitter and when he's active again (maybe he's away?) I'll try contacting him again - primarily to confirm how to purchase a commercial license, or even perhaps if he's moved on and would be willing to more permissively license the project. I'd consider adding a pull request with an appropriate license if that was the case.

**Comment by tdmalone** [comment]
Further clarification: this project was originally released under the more permissive MIT license, which is open source. It was then modified to be a 'non-commercial BSD license' on 11th May 2012. Compare the changes to readme.md here: https://github.com/blasten/turn.js/commits/master/readme.md

This means that the source of the project up until this date is available, including for commercial use, under the MIT license, as an open source license cannot be withdrawn. The project has been forked with the old MIT license (https://github.com/Youscribe/turn.js - which in turn has had its own forks) for this exact purpose.

So the solution - for now - seems to be to use the code base from before that date, unless and until we are able to contact Emmanuel. This obviously doesn't include turnjs4.

**Comment by tdmalone** [comment]
**I'VE HEARD BACK!**

I'm pleased to confirm that commercial licences for turn.js 4 are still available. Emmanuel has confirmed to me via e-mail (after contacting him on Twitter too) that commercial licenses can indeed still be purchased through http://turnjs.com/get. This also includes the bookshelf as seen on the turnjs.com homepage.

Summary of what I've confirmed thus far:
- For commercial use with the most up-to-date code: http://turnjs.com/get
- For commercial use with older code that is still open source: https://github.com/Youscribe/turn.js
- For non-commercial use, just download the latest from http://turnjs.com/

**Comment by filamananda** [comment]
Nice. Can you paste the actual email from Emmanuel over here?

**Comment by tdmalone** [comment]
Of course. Here's the email trail. No reply to the last message.

**Tim Malone, Mar 23:**

> Hi Emmanuel,
> 
> We'd love to use your turnjs library as seen on http://turnjs.com/ in a web site we're building.
> 
> The licensing set up seems a bit unclear so I just wanted to enquire as to whether we can use turnjs3, turnjs4, the bookshelf etc. and if a development license is required, what the cost of that would be?
> 
> Thanks very much,
> 
> Cheers,
> 
> Tim

**Emmanuel Garcia, Apr 8**

> Hey Tim,
> 
> I saw your tweet. Sorry that I missed your email.
> Yes, you can get a license for $99. It includes turn.js 4 that includes everything you mentioned and you can order it on turnjs.com/get
> 
> Let me know if you have any question
> Thanks

**Tim Malone, Apr 8**

> Thanks so much for your reply Emmanuel. I understand you're a busy guy.
> 
> I'll organise purchasing that license right away.
> 
> There are quite a few people who are confused by the current licensing status of turn.js. I started a GitHub issue about a week ago to bring together all the different information available: https://github.com/blasten/turn.js/issues/548. Your input there would be much valued!
> 
> I think one of the biggest issues is that at first, the project appears to be open source - but isn't, because of the licensing restrictions. That can be confusing, and it's compounded by the fact that the http://turnjs.com/get link isn't available on the current http://turnjs.com website: it means to most observers that the code is available…. but can't legally be used. This is even more true with the download link on the site linking to turn.js 4 (and containing no licensing information), but the link under the 'Licensing' heading itself on the site being broken.
> 
> May I suggest either making the licensing and the purchase flow clearer, or - if you've moved on from the project - considering re-releasing it under an open source license (such as the GPL, to force people to not make it proprietary?)
> 
> Thanks for your consideration, and thanks even more for the great work on this library in the first place. It's a testament to the ongoing value of it that so many are still following it even after active development has ceased.
> 
> (Stil organising a purchase now either way!)
> 
> Cheers,
> 
> Tim

**Comment by IvoJager** [comment]
Thanks for following this up Tim - much appreciated. I too organised a purchase, thanks to your efforts of trying to clearing this up.

**Comment by juancarlosgf02** [comment]
This means that the old code is free?

**Comment by tdmalone** [comment]
@juancarlosgf02 The old code, before the license was changed, is free, yes. The new code, after the license change, requires a paid license for commercial use.
