### ISSUE TITLE
Turn js display empty pages 

### ISSUE THREAD

**Issue by sabirali007** [blasten/turn.js#550]
Hi,

i am trying to load page dynamically but it display empty page and on turn show empty page.

**Comment by janebrandhub** [comment]
i have the same problem.  Have you sorted this out?

**Comment by sabirali007** [comment]
I think its not work with mobileJquery

**Comment by Dr-Dev** [comment]
did you see it?
https://github.com/blasten/turn.js/wiki/Making-pages-dynamically-with-Ajax

**Comment by sabirali007** [comment]
i was trying to use with mobile jquery that was conflict with turn js.
