### ISSUE TITLE
Is there any Turn.js and React integration working?

### ISSUE THREAD

**Issue by death667b** [blasten/turn.js#568]
When ever I put turn.js inside a react component the pages get incorrect css attributes.

For example, if the mouse hovers over the bottom right page the page moves up approx 55% of the element height.  
If the mouse hovers over the top left, the pages moves left 100% of the element's width (off the page).
If the mouse hovers over the bottom left the pages moves up 55% and left 100%.

Works correctly when the mouse hovers over top right.

Turn.js works fine when it is by itself.

I have tried turn.js version 4.1.0 and 5.0.0
I am using Chrome v54 and MS Edge

Because of react I am using ES6 <- Could that be an issue?

**Comment by marvindanig** [comment]
Can we see your project? 

Using a `virtual dom` library to polyfill page turning effect on browsers may not be a correct approach, but I can confirm only after looking at your project. We're currently working on a pure javascript library (no jQuery!) to add the book behavior to DOM, it will have a subset of turn api that's most useful to people. 

https://github.com/marvindanig/flippy.JS 

Feel free to star us or contribute!

**Comment by death667b** [comment]
Turns out all my problems where to do with new jQuery - works fine with React

**Comment by MartianGreed** [comment]
Hey, i'm trying to get this working with React / Webpack. Can't figure out how to import this... Can somebody help?

**Comment by maximusnikulin** [comment]
@death667b  Hi. Could you show me some example of your code.  I have been trying to import turn.js to webpack for several days but I have some errors. Thanks.
