### ISSUE TITLE
Page gets blurry when hovering over corner

### ISSUE THREAD

**Issue by ghost** [blasten/turn.js#57]
Hi, I've noticed that in my implementation (and in the demos you ship with turn.js) that as you hover over the page corner, the page itself becomes blurry. It is particularly noticeable on text pages. 

Do you know why this might be? I notice that it doesn't appear to happen on http://www.turnjs.com. 

Tested in latest Chrome and Firefox.

Thanks.

**Comment by blasten** [comment]
Yes, it's because of the `acceleration` option,  If you set `acceleration:false`, the page never gets blurry.

**Comment by ghost** [comment]
I see, thank you. What does that option do?

**Comment by blasten** [comment]
it's for hardware acceleration

**Comment by michalhudecek** [comment]
Turning off acceleration only helps for Chrome. In Firefox (v 14.01) the text is still blurry.

**Comment by syedhammadali** [comment]
i have 4.1.0 version but i am having same issue fixed in chrome by this acceleration:false but not in Firefox
