### ISSUE TITLE
Mouse wheel scrolling.

### ISSUE THREAD

**Issue by isaact-d** [blasten/turn.js#58]
in my browser you are able to scroll down with the mouse wheel and the book is not centred on the page. Is there a way you can centre the book on all browsers so it is not possible to scroll down and add use mouse wheel to scroll through pages function. I wanted to book to open in jqModal Window  to get a lights out effect.

**Comment by tvanassche** [comment]
You will have to hook into the jqModal events and put something like "overflow: hidden" on the body of the html document. This should disable scrolling.

For the page-turning with the mousewheel, you'll need to use an external plugin I think (quick google search gave me https://github.com/brandonaaron/jquery-mousewheel for example). Turn.js has methods that can be called to turn pages, so you can bind those to the mousewheel up/down events.

**Comment by isaact-d** [comment]
Thanks man that's an awesome help thanks so much
