### ISSUE TITLE
1st page is removed after turn complete

### ISSUE THREAD

**Issue by bytespider** [blasten/turn.js#6]
It looks as though page 1 is removed from the dom after the 2nd and 3rd pages are displayed. I couldn't work out what portion of code was responsible, but the node looks to be removed when doing something with backpages.

I'm using background images on divs.

**Comment by blasten** [comment]
Yes, turn.js temporarily replaces the page location every time the animation is activated.

**Comment by blasten** [comment]
Let me know if you have any problem with background images on divs.

**Comment by bytespider** [comment]
The div holding the image isnt there when i flip back to it.

**Comment by blasten** [comment]
Which browser and version are you using?

**Comment by bytespider** [comment]
I'm using Google Chrome 18.0.1025.33 beta. I just tried your example, magazine that doesn't Do it. I'lll try work out what i did differently

**Comment by blasten** [comment]
Yes, you right. There's a bug in Chrome 17.0.963.56 beta and 18.0.1025.33 beta.  I know where the problem is, I sent an email to the Chrome developer team. I hope they fix it as soon as possible. I'm trying to do the process in a different way to see if it's possible to skip the issue.
