### ISSUE TITLE
Using turn.js for an online magazine

### ISSUE THREAD

**Issue by brandonHeaslip** [blasten/turn.js#61]
I am creating an online skateboard magazine for a client. I really love this plugin because it has every option in it I wanted to implement. Is it possible for me to use this plugin for commercial use? I have been researching the MIT license and can't see a problem using this plugin. Can someone please tell me what exactly I have to include, to be able to use this plugin for commercial use.

**Comment by blasten** [comment]
@brandonHeaslip.  You can use the plugin for commercial purposes provided you include the MIT license as part of your product.
