### ISSUE TITLE
Trouble with responsive design

### ISSUE THREAD

**Issue by magusMartti** [blasten/turn.js#640]
Hello! If this is a duplicate question, I am sorry. This is an awesome plugin, I've had tons of fun with it. But Im having problems with mobile design, I am trying to make flipbook take up the entire screen size with mobile, but no luck so far. If any of you have some tips, that would be awesome.

**Comment by RaffaeleMorganti** [comment]
There is size method to resize. Simply set pages size to full width/height.  `$('#viewer').turn('size', width, height)`
You need to calculate them to fit the page and keep aspect ratio.

**Comment by magusMartti** [comment]
Ty for the info, If its not too much trouble, can you give me an example? with some random heights/widths? Because at the moment, im trying to figure out how to make it display single page when mobile, and that one single page should take up the entire screen width/height
