### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by mrlennartsson** [blasten/turn.js#65]
How do i reset turnjs, turn('stop') does not work..

**Comment by blasten** [comment]
`stop` will stop the current animation.  What do you mean by reset?

**Comment by mrlennartsson** [comment]
Oh i see. I dynamically fill $("#magazine").html("<div>page1</div><div>page2</div>"); etc etc

I want to load a new paper in the same $("#magazine");

**Comment by blasten** [comment]
I would recommend to use `addPage` and `removePage` instead of html(...)
