### ISSUE TITLE
preventDefault hangs turn.js

### ISSUE THREAD

**Issue by kiranp11** [blasten/turn.js#66]
I am using turn.js in 2 page mode, I want to prevent user from flipping to page 1. i.e page 2-3 should be my initial page setup. So I am doing this :

```
when: {
      start: function(e,page){
        if(page.page == 2){
          e.preventDefault();
          return;
        }
      }
    }
```

The problem I am facing is, If i do a mouse click on top left corner with this setup. turn.js hangs and I wont be able to do any more page flips. I can see the start event triggered for top left but hovering over top right or bottom right does not trigger any event.

**Comment by blasten** [comment]
@kiranp11 You must use the `turning` event as well.  `start` prevents the effect from mouse actions.  But there are several ways to turn the page, using the `page` method for instance, so. `turning` fires before changing the current page and allows you to prevent that action.
