### ISSUE TITLE
Change Single/Double page display when orientation change

### ISSUE THREAD

**Issue by wilee88** [blasten/turn.js#69]
I am working on a project for iPad, and need to change the display from Single page to Double page when the orientation change from portrait to landscape, but cannot get it to work.

This is what I did in the body.orientationchange event, but its not working.

if (isIpad() && !rotated()) {
  $('#magazine').turn({display: 'single', width: 600})
} else {
  $('#magazine').turn({display: 'double', width: 1200})
};
$('#magazine').turn('page', pagenum);

Can anyone help?  Thanks.

**Comment by blasten** [comment]
Yes, you can use `$(..).turn('display', 'single')` or  `$(..).turn('display', 'double')`

**Comment by wilee88** [comment]
Hi, I got that to work.  Thank you very much for this wonderful plugin.

**Comment by wilee88** [comment]
Thanks.

**Comment by postonoh** [comment]
can you post your code

**Comment by n0rbs** [comment]
Hi Blasten,

I tried the code switching from double to single display. It doesn't work.
We bought the license for version 4 and it won't work. 

We want to shift to a single page on portrait orientation and double page landscape orientation. Right now, our only solution is reloading the page.

**Comment by joshbuchea** [comment]
Very basic fullscreen, responsive turn.js tablet demo for anyone who comes across this thread seeking a solution: http://codepen.io/joshbuchea/pen/zGdJMR

**Comment by doricardo-zz** [comment]
@joshbuchea Is it going to work on PC browser?
