### ISSUE TITLE
make magazine scale with browser size

### ISSUE THREAD

**Issue by ghost** [blasten/turn.js#70]
I can't seem to make the magazine scale with the browser window, instead it will only change the size once the browser is refreshed. Is this just the way the plugin renders the view or can the magazine actually be set to 100% the parent and then scale with it?

**Comment by blasten** [comment]
Yes. you can use `turn('size', width, height)`

**Comment by carrotcomputer** [comment]
do you set it to 100%, like:

```
$('#magazine').turn('size', '100%', '100%');
```

As that doesn't seem to work for me? obviously without the quotes over the %'s they are just actual pixels

**Comment by una** [comment]
Try a fixed width:

 $('#magazine').turn('size', '100%', '400px');

That worked for me "kind-of" but its extremely buggy because only one of the pages gets smaller. How can I keep the fold centered?

**Comment by blasten** [comment]
Oh, turn.js doesn't allow that format yet.   The width and height must be in pixels and must be numbers.

`$('#magazine').turn('size', 400, 400);`

**Comment by rungsikorn** [comment]
you can use jQuery window 

```
jQuery.event.add(window, "resize", resizeFrame);
                function resizeFrame(){

                    var w = $('#main').width(); // this is div for ref

                    if(w<=320){
                    $('#magazine').turn('size', '220', '287');
                    }else 
                    $('#magazine').turn('size', '480', '626');
                    }
```
