### ISSUE TITLE
Can I make single page Easy to turn ?

### ISSUE THREAD

**Issue by rungsikorn** [blasten/turn.js#74]
I use turn.js in single page mode

and I need to drag so long distance form side to side to turn page

can I make it shorter than ? maybe just drag half page to turn

**Comment by hyrax1** [comment]
+1

**Comment by hyrax1** [comment]
I didn't find the most graceful way to do this, but if I delete the first and last line ( the '}') of the following, it makes any distance cause a flip:

```
    if ((new Date().getTime())-data.time<200 || point.x<0 || point.x>$(this).width()) {
        e.preventDefault();
        data.opts.turn.data().tpage = data.opts.next;
        data.opts.turn.turn('update');
        $(that).flip('turnPage');
    }
```

**Comment by rungsikorn** [comment]
Thank for your advice :D

so I comment an If cause box like these and I can flip in any distance

It very helpful for who want to display Magazine in single page

```
Line 1058
// if ((new Date().getTime())-data.time<200 || point.x<0 || point.x>$(this).width()) {
        e.preventDefault();
        data.opts.turn.data().tpage = data.opts.next;
        data.opts.turn.turn('update');
        $(that).flip('turnPage');
 //   }
```

Thank you again
