### ISSUE TITLE
Using custom HTML for each page

### ISSUE THREAD

**Issue by earlic** [blasten/turn.js#75]
Hello there, firstly, thanks so much for this resource. You are a wonderful person for sharing your work with everyone.

I've just begun playing around with this, and I have a question about using custom HTML for my pages. How do I specify what goes on a page? 

I'm only using plain text, one paragraph within one div tag, and another in a second div tag. The first paragraph goes on the first page, and the second one on the second page, but even though my book is supposed to be 640 x 480, it looks really narrow and the when I hover above the page edges, the book zooms in and out and doesn't flip properly.

Hope that made some sense, and hope you can help me out.

Thanks.

**Comment by blasten** [comment]
CSS ;)
