### ISSUE TITLE
Turn.js inside a query UI dialog

### ISSUE THREAD

**Issue by mouloud** [blasten/turn.js#76]
Hi there,
I use turn.js inside a jqueryui dialog, and when I close the dialog (and destroy it), a lot or js errors are thrown on mouse move :
TypeError: 'undefined' is not an object (evaluating 'this.data().f.opts')  turn.min.js:29
TypeError: 'undefined' is not an object (evaluating 'b.disabled')  turn.min.js:44

I suppose it's because the onmousemove event is not unbounded. I try 
$("#pageflip").turn('disable', true);
before closing, but it doesn't help.

Thanks

**Comment by mouloud** [comment]
I removed the second error with :
$(document).unbind();
But for the first error, i suspect I need to call clearinterval(). So I need to access to the data.effect.handle value...

**Comment by mouloud** [comment]
i removed the second error by making data.effect.handle global. But it's not a clean solution, as I must modify turn.js.
And jqueryui sortable becomes buggy just after that. It may need a more restrictive unbind.

**Comment by blasten** [comment]
@mouloud  that would be a destructor function for turn.js?

**Comment by mouloud** [comment]
Yes, it would be very helpful in my case...
Actually, it still doesn't work. There is always a registered event that cause errors when I click on the window after the dialog is closed. I can't find where it's registered...

**Comment by mouloud** [comment]
A demo of the problem :
http://jsfiddle.net/dztKW/
As you can see, it's not linked to jqueryui at all. You just have to remove the div to start the errors (hover or click on the result pan, and look at your console).
I successfully removed the error with this code :
$(document).unbind("mousemove");
$(document).unbind("mouseup");
clearInterval(handle);
But I had to modify turn.js to make data.effect.handle global.
Any idea how I could access to data.effect.handle without modifying turn.js ?
Thanks.

**Comment by blasten** [comment]
Oh right! it will be included in the next version.

**Comment by teddy888** [comment]
Can you post up how you fixed this issue? I am having similar problems, but have no idea where to start.

Thank you

Teddy

**Comment by mouloud** [comment]
First, you'll have to declare a global in a script tag of your page :
var handle;
And in turn.js (not turn.min.js), after line 1911 "data.effect.handle = setInterval(f, fps);"
Add the line :
handle = data.effect.handle;

And then, after you removed the window, just add those 3 lines :
$(document).unbind("mousemove");
$(document).unbind("mouseup");
clearInterval(handle);

**Comment by teddy888** [comment]
Hello mouloud,

Thank you very much. It worked perfectly fine, but I was wondering, have you ever encountered a problem when you close the dialog and reopen it, you can't move it anymore? Also, when you use the arrow keys to flip the page, it will flip the page twice and skip a page or two. This all happens after the dialog closes and reopens.

Thank you very much

Have a nice day.

Teddy

**Comment by mouloud** [comment]
No, It works fine after reopening it... Are you calling $().turn() again each time ?

**Comment by teddy888** [comment]
Yes I am. So basically, everytime I close it and then reopen with the same div, this code gets executed:

$(window).ready(function() {
    $('#notebook').turn({
        display: 'double',
        acceleration: true,
        elevation:100,
        when: {
            //prints out page number
            turned: function(e, page) {
                console.log('Current view: ', $(this).turn('view'));
            }
        }
    });
});

$(window).bind('keydown', function(e){

```
if (e.keyCode==37)
    $('#notebook').turn('previous');
else if (e.keyCode==39)
    $('#notebook').turn('next');
```

});

This code is included in the file that the dialog opens up, while the code which controls the dialog is included in the main window.

Teddy

**Comment by mouloud** [comment]
Try to put all the code in the main window, and bind the turn() function to the click event that open the dialog...

**Comment by teddy888** [comment]
Do you mean binding like this:

$(document).ready(function(){
    $('.ajaxtrigger').live('click',function(){
        $('#target').dialog('close');
        $(document).unbind("mousemove");
        $(document).unbind("mouseup");
        clearInterval(handle);

```
    var heading = 'MyNotebook - ' + $(this).attr('coursename');

    $('#target').load(this.href, function() {
        setTimeout(function(){
            $( '#target' ).dialog({
                resizable: false,
                modal:false,
                title: heading,
                show: "explode",
                hide: "explode",
                width:"auto",
                height:"auto",
                position:"center"
            });
            return false;
        }, 50);
    });
    return false;
});
$(document).keyup(function(e) {
    if (e.keyCode == 27) {
        $('#target').dialog('close');
    }
});
```

});

If so, I tried your way and still have the same issue. If not, could you please show me how you did it?

Teddy

**Comment by mouloud** [comment]
I'm don't understand where in your code you call turn() ?

**Comment by teddy888** [comment]
On my main page, I'm calling the code above.

In the dialog popup page, I'm calling turn.js as well as the following piece of code that has turn():

$(window).ready(function() {
    $('#notebook').turn({
        display: 'double',
        acceleration: true,
        elevation:100,
        when: {
            turned: function(e, page) {
                console.log('Current view: ', $(this).turn('view'));
            }
        }
    });
});

**Comment by mouloud** [comment]
#notebook is inside the dialog ?
The dialog is opened automatically on parent page load ?
How do you reopen the dialog after closing it ?

**Comment by teddy888** [comment]
#notebook is inside the dialog.

The dialog(#target) opens onclick, passes the page to load into the dialog, and is closed before it opens:

$(document).ready(function(){
 $('.ajaxtrigger').live('click',function(){
        $('#target').dialog('close');
                    ....
$('#target').load(this.href, function() {
            setTimeout(function(){
                $( '#target' ).dialog({
                    resizable: false,
                    modal:false,
                    title: heading,
                    show: "explode",
                    hide: "explode",
                    width:"auto",
                    height:"auto",
                    position:"center",
                    draggable: true
                });
                return false;
            }, 50);
        });
        return false;
    });

The closing is done to act as a 'page reload'(close and then opens dialog) when you click on the same button again.

You can reopen the dialog two ways:
1) As above, you click on the same button(outside the dialog) which closes the current opened dialog and reopens it
2) You click on the button inside the dialog which closes the current dialog and reopens it with new content.
It is when you reopen the that  disables the dragging. I also found that when you open the dialog for the first time and you move the dialog and let go and then try to drag it again, it would not move anymore. This only happens with the dialog that uses turn.js. The other dialog works fine.

**Comment by mouloud** [comment]
Ok, so try to call turn() inside your setTimeOut, just after the dialog call. And remove it from the document loaded inside dialog.

**Comment by teddy888** [comment]
I tried it exactly as you have specified, but no luck. It's weird that when I did not use your fix for those errors, you can drag, release the mouse, and then drag again and it worked fine. But when I used your fix to get rid of those mouse errors, this error pops up. You mentioned that you have it working fine above. Do you have any examples of it working?

Thank you

**Comment by teddy888** [comment]
I'm curious, when you unbounded the mousemove and mouseup, would that have any effect on the ability to drag things?

**Comment by mouloud** [comment]
No, everything is working fine by me.
But when I try to reproduce it on a fiddle, I got the same error as you. So I did several testing, and actually, I find out that unbinding the mouse up event is not necessary, and cause of the error. So I got this working :
http://jsfiddle.net/TQnL5/1/

**Comment by teddy888** [comment]
Hello mouloud,

I finally managed to get it working. It required me to include jquery inside my dialog as well as the main page. Otherwise, it will not let me drag and also, I still need to unbind the mouseup event to get rid of the error. Just as an aside, have you ever tried using TinyMCE with the turn.js inside a dialog?

Thank you very much for you time and help.

Teddy

**Comment by mbades** [comment]
hello guys I too have the same problem, but I can not solve it.

I have a div (isotope container), which contains 5 elements Fancybox, each book contains a browsable Fancybox done with turn.js.

I have this js code in the main file (Fancybox loading with integrated turn.js )

<pre><code>
  /* colonna pubblicazioni */
    $(".fancybox-pubb").attr('rel', 'gallery').fancybox({
        autosize: false,
        loop: 0,
        padding: 0,
        maxWidth: 900,
        maxHeight: 400,
        openEffect: 'fade',
        closeEffect: 'fade',
        prevEffect: 'none',
        nextEffect: 'none',
        afterLoad: function(current, previous) {
            $('#magazine').turn({
                width: 567,
                height: 400,
                display: 'double',
                acceleration: true,
                gradients: !$.isTouch,
                elevation: 50,
                when: {
                    turned: function(e, page) {
                        /*console.log('Current view: ', $(this).turn('view'));*/
                    }
                }
                
                    
            });
            $(window).bind('keydown', function(e) {
                if (e.keyCode === 37)
                    $('#magazine').turn('previous');
                else if (e.keyCode === 39)
                    $('#magazine').turn('next');
            });
            //debugger;
            //var $base = $(".thumbnail");
            //var leftPosition = $base.width() * 0.5;
            /*
             console.info( 'Current: ' + current.href );        
             console.info( 'Previous: ' + (previous ? previous.href : '-') );
             if (previous) {
             alert( 'Navigating: ' + (current.index > previous.index ? 'right' : 'left') );     
             }
             */
        }
    });
</code></pre>

this code inside the index.html of turn.js content

<code><pre>

$(window).ready(function() {
        $('#magazine').turn({
                            display: 'double',
                            acceleration: true,
                            gradients: !$.isTouch,
                            elevation:50,
                            when: {
                                turned: function(e, page) {
                                    /_console.log('Current view: ', $(this).turn('view'));_/
                                }
                            }
                        });
    });

```
$(window).bind('keydown', function(e){

    if (e.keyCode==37)
        $('#magazine').turn('previous');
    else if (e.keyCode==39)
        $('#magazine').turn('next');

});
```

</code></pre>

Finally, the Fancybox loads the div magazine

<code><pre>

<div class="row-fluid">
    <div class="span8pubblication">
        <div style="margin: 0px;" >
             <div id="magazine">
                <div style="background-image:url(pubblication/10_/pages/01.jpg);"></div>

```
            <div style="background-image:url(pubblication/10_/pages/02.jpg);"></div>
            <div style="background-image:url(pubblication/10_/pages/03.jpg);"></div>
            <div style="background-image:url(pubblication/10_/pages/04.jpg);"></div>
            <div style="background-image:url(pubblication/10_/pages/05.jpg);"></div>
            <div style="background-image:url(pubblication/10_/pages/06.jpg);"></div>
         </div>
    </div>
 </div>
```

</code></pre>

I have this code, how can I integrate the solution you found to solve the problem?

**Comment by mbanushi** [comment]
Thank you very much moloud. I was struggling with turn.js code for 3 hours straight, trying to destroy the plugin, so that i could reinitiallize it with new content. Your global handle trick made it possible without a single error thrown. You are my hero!
