### ISSUE TITLE
IFrame Appending

### ISSUE THREAD

**Issue by shankaroninfotech** [blasten/turn.js#77]
While i append iframe into the pages the fip effect will not work inside the iFrame...

Can u solve this.

**Comment by blasten** [comment]
@shankaroninfotech  That's normal.  I don't see why need an iframe, but what I can suggest is just get rid of it.

**Comment by shankaroninfotech** [comment]
ok.. thanks... for reply

u just try to append an iframe on each and every page with some source address like

<div id="divMagazine">
<div><iframe src="a.html"></iframe></div>
<div><iframe src="b.html"></iframe></div>
<div><iframe src="c.html"></iframe></div>
<div><iframe src="d.html"></iframe></div>

</div>


and in script u call $("#divMagazine").turn();

if i append the iframe into the children div Element then the page flipper corner is not went inside the iframe.......

in some browser it will process slowly...

can u explain the problem arise during the appending of iframe to the children DIV element....

Pls.....!
