### ISSUE TITLE
Linking through to pages

### ISSUE THREAD

**Issue by jgadsbypeet** [blasten/turn.js#78]
Hi there guys

Firstly - let me add to the thanks for publishing turn.js - it's absolutely fantastic

I've deployed the most simple version for a magazine layout that i'm testing - as a complete js noob i'm struggling with setting up a navigation bar that will open the magazine to the appropriate page. I tried using anchor tags but this doesn't work...

Any help would be much appreciated!

Thank you

James

**Comment by tvanassche** [comment]
You can easily turn to a specific page with the command _$('selector').turn('page', pageNumber);_

It is also possible to open the magazine on a specific page when initialising it with the command _$('selector').turn({page: pageNumber});_ 

Take a look at the reference for a complete overview of available commands/events/methods: https://github.com/blasten/turn.js/wiki/Reference

**Comment by jgadsbypeet** [comment]
Thanks again for this mate - i'm sorry to ask, but is there any way to give a slightly more detailed use of the specific page turn tool - i'm really struggling with the Jquery side to all this

Thank you!
