### ISSUE TITLE
Custom links

### ISSUE THREAD

**Issue by Raido88** [blasten/turn.js#8]
Is it possible to get custom links outside the flipping area (menu links for example) to flip to specific page? I didn't find anything for this in the references.

Thanks in advance!

Raido

**Comment by blasten** [comment]
Yes, in order to flip to specific page you can use $('selector').turn('page', pagenumber);

**Comment by yaffar666** [comment]
Hola Blasten,
Estoy teniendo un inconveniente con  $('selector').turn('page', pagenumber);
Tengo una implemtación propia de tu código y lo estoy usando contra la base web de chrome, está quedando fantástico, cool tu trabajo.
En fin, el asunto es que tengo un boton para cambiar de pagina ingresando en un textbox el numero de pagina, todo funciona bien excepto cuando coloco el numero 1, es decir ir a la portada; en ese caso va a la portada del libro, pero en el lado izquierdo aparece la última página. No encuentro donde puede estar fallando, estoy trabajando en eso; pero si tienes algun tip que compartir al respecto estaría muy agradecido.

Bolivar Yar (en Ecuador, Bolivar es nombre, no apellido)..:D 

Saludos desde Quito.

**Comment by blasten** [comment]
Hey Bolivar,

Si hay un problema,  cuando uses `turn('page', pagenumber);`  `pagenumber` debe ser un Number, y allí según lo planteas es un String.  Me percaté de ese error en estos días.. así que usa  `$('selector').turn('page', parseInt(page));`

Saludos

**Comment by yaffar666** [comment]
Chevere pana, gracias por tu recomendacin.

On Mon, Feb 27, 2012 at 12:24 AM, Emmanuel Garcia <
reply@reply.github.com

> wrote:
> 
> Hey Bolivar,
> 
> Si hay un problema,  cuando uses `turn('page', page);`  `page` debe
> ser un Number, y alli segun lo planteas es un String.  Me percate de ese
> error en estos ideas.. asi que usa   `$('selector').turn('page',
> parseInt(page));`
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/blasten/turn.js/issues/8#issuecomment-4188204

## 

## 

Bolvar Yar
E-mail: bolivar.yar@gmail.com ; yaffar666@gmail.com
MSN Messenger: yaffar666@msn.com
Home: (593) 02 2401 478
Office:  (593) 02 2239 013
Cell:    (593) 09 5880 827
Quito - Ecuador
