### ISSUE TITLE
How to switch display mode between double to single?

### ISSUE THREAD

**Issue by trauquen** [blasten/turn.js#80]
firstly I have a magazine displays in double, then try it with function below
function singleMode() {
        $('#magazine').turn({
            display: 'single', width: 576
        })
    }

But always throw the error like '"2" is not a page for range', I'm no idea why and how to do that?

**Comment by blasten** [comment]
Was you magazine previously created?  Because if it was, you need to use `$('#magazine').turn('display', 'single');`

**Comment by trauquen** [comment]
<code>$('#magazine').turn('display', 'double').turn('size', newWidth, newHeight);</code>

I'm still testing that until the project complete when I will close this issue.

Many thanks to your tips.
