### ISSUE TITLE
Problem with turn.js and Chrome

### ISSUE THREAD

**Issue by wolyte** [blasten/turn.js#81]
Hello Emmanuel Garcia,

First of all congratulations for the project, really nice, then I'm sorry for my bad ingle, I'm Italian.

I have a problem with turn.js and Chrome!

I create a book of dynamics images created by invoking a PHP program that receives a parameter, so do not use:

style="background-image:url(pages/01.jpg);

but I use:

style="background-image:url(makeImage.php?x=2);

If I use Safari and Firefox no problem, but when I use Chrome and change page the browser redraws the page and reloading images taking a long time!

An example is here:

http://test.egip.it/routines/ztestViewBook.php?id=21

How can I solve this problem?

Help me please to me, your software is very important and continues to develop itbecause it's really nice.

I made ​​a donation.

Thank you.

**Comment by FlashJunior** [comment]
What should we see exactly?
If i go to http://test.egip.it/routines/funMakeImage.php?x=2|21|3| i see the same like http://test.egip.it/routines/funMakeImage.php?x=2|21|9|

And that ist exactly what i see in Chrome 18 and 20 (OSX) @ http://test.egip.it/routines/ztestViewBook.php?id=21

**Comment by wolyte** [comment]
The result is the same, but while Safari and Firefox preparing the images and when you change page, the pages flow smoothly, Chrome every time you change page recreates the images and this produces a big slowdown that makes it unusable.

**Comment by blasten** [comment]
@wolyte Is your PHP program sending the headers the browser needs to stop downloading the pages over and over again?

**Comment by wolyte** [comment]
@blasten I don't know what was the problem, but I solved it emptying the cache memory... Thanks a lot.
