### ISSUE TITLE
Technology test: turn.js + mozilla's pdf.js

### ISSUE THREAD

**Issue by MaximS** [blasten/turn.js#82]
Demo is available here: http://www.maxims6n.bget.ru/pdf_books/demo_21.html
Waiting for a paper- and hard-cover effect...

**Comment by blasten** [comment]
@MaximS  That Looks Amazing!

**Comment by iliae** [comment]
Hello Maxim!
Me interested 
How to contact you?
my skype: ilia0827
Ilia

**Comment by quartopianodesign** [comment]
@MaximS  news about turn.js + pdf.js ??

**Comment by iliae** [comment]
Yes

**Comment by quartopianodesign** [comment]
Good, but more info or demo?

**Comment by iliae** [comment]
I'm interested in the transition to the newest version

On Wed, Jan 28, 2015 at 10:10 PM, qurtopianodesign <notifications@github.com

> wrote:
> 
> Good, but more info or demo?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/blasten/turn.js/issues/82#issuecomment-71906430.

## 

Best Regards,
Ilia Zelansky
izelansky@gmail.com
+972526893939

**Comment by cedtnee** [comment]
Hi all,
 I'm very interested in this turn+pdf fusion !
 Could you please send me the src? 

my mail: cedric.tnee@gmail.com

Regards

**Comment by iliae** [comment]
Hi,
Are you interested to obtain or develop such a system?
Regards
Ilia

On Sat, Feb 21, 2015 at 11:03 PM, cedtnee notifications@github.com wrote:

> Hi all,
> I'm very interested in this turn+pdf fusion !
> Could you please send me the src?
> 
> my mail: cedric.tnee@gmail.com
> 
> Regards
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/blasten/turn.js/issues/82#issuecomment-75392792.

## 

Best Regards,
Ilia Zelansky
izelansky@gmail.com
+972526893939
