### ISSUE TITLE
Using turn.js and tinymce inside textarea of a page broken

### ISSUE THREAD

**Issue by teddy888** [blasten/turn.js#84]
Hello there,

I am trying to add a tinymce editor to a textarea inside my book on each page, but it breaks when you flip away and then back to that page. Also, the textarea becomes unusable and you can no longer type in it. This is all done inside a jquery dialog.

Could anyone please help?

Thank you

Teddy

**Comment by blasten** [comment]
I will check that out.

**Comment by teddy888** [comment]
Did you have any success on implementing tinyMCE on a book page in a dialog?

**Comment by blasten** [comment]
tinymce is using an iframe and that is causing some issues. I hope to fix it.

**Comment by teddy888** [comment]
Did you have any luck? I got none.

**Comment by blasten** [comment]
Could please provide me the HTML code?

**Comment by teddy888** [comment]
Hello again blasten,

Sorry for the late reply, I have been very busy lately. I just wanted to let you know that if you place the tinyMCE editor within an iFrame and place that onto a page, it works fine. I'm just curious, since I've been using turn.js v2/v3 before the new license and v4 release would I need to pay for a license even though I'm using this for an open source project? I just saw this on your updated website.

Thank you very much

Teddy

**Comment by teddy888** [comment]
May we use v4 for open source projects?

**Comment by blasten** [comment]
@teddy888 what is the license of the open source project? You can use v2 for the open source project.  Turn.js 4th release is only available for commercial purposes.

**Comment by teddy888** [comment]
It's for Moodle under the GNU license. What about the 3rd version, may we use that or is it only available for commercial purposes?

Thank you

**Comment by blasten** [comment]
@teddy888 You can use turn.js 3rd release!

**Comment by teddy888** [comment]
Thank you very much! Do you know how one can make 'bookmarks' that can link to certain pages?

**Comment by rap-it** [comment]
Teddy,

did you get the tinyMCE to work in version 3? i have the same problem... 

hopefully you can help me.

**Comment by teddy888** [comment]
Hello rap-it,

What I basically did was applied the tinyMCE to a textarea inside an iframe on every page that uses turn.js. One problem I encountered was that in IE, it breaks and says that I have an error relating to the contentWindow which I have no idea at the moment. 

Hope that helps to get you started

Teddy
