### ISSUE TITLE
Swipe and Zoom on iPad

### ISSUE THREAD

**Issue by karolszafranski** [blasten/turn.js#85]
I want to use turn.js to create online catalog, dedicated for ipad. I want to keep ability to zoom (i left user-scalable attribute with its default value). Swipe gesture to turn pages would be also useful, like on http://www.turnjs.com/ but when you try to zoom, even on official website, pages will turn after pinch gesture. 

I suppose it happens because start of pinch gesture works the same way like swipe - I mean one finger slide. There is condition to turn the page only when touchmove event is made by only one finger (e.originalEvent.touches.length == 1) but I guess before swipe (one finger) becomes pinch (two fingers touches the screen) browser sees first event swipe, next event pinch separately. Same way when somebody take fingers off the screen (it never happens in exactly the same time). 

I tried to change e.originalEvent.touches to e.originalEvent.changedTouches to get count of fingers that were used in event, but it also doesn't work like i want it to.

Any simple idea how to fix it?

**Comment by blasten** [comment]
@karolszafranski Yes, there's a problem with some of the conditions. It's a good idea to count the sequence of events. For example:

touchstart + touchend + touchstart + touchend.  (only one finger) will be for the native zoom.
touchstart + touchmove + touchend  (only one finger, 0-10 degrees)  will be for turning the page.

It's also important to count the time in microseconds when each of these events happened, because the difference among each one could determine whether it's a sequence or not.

The 4th version will include these features.

**Comment by Panda77** [comment]
on IPAD http://www.turnjs.com/ when you try to zoom in example, dont function

**Comment by cwoolum** [comment]
I am trying to get this working on the 4th version. Has the pinch to zoom feature been implemented?

**Comment by rondiege** [comment]
For what it is worth, I got zoom to work with the ipad combining turn.js with  jgestures (http://jgestures.codeplex.com/).

Did something along the line of this: 

```
if ($.isTouch){
 $('.magazine-viewport').bind('pinchopen',function() {
 var currpage = $("#flipbook").turn("page");
 if((currpage%2) && currpage!=1){
var prepage = ($("#flipbook").turn("page"))-1;
 loadLargePage(prepage,$( ".p"+prepage));
 loadLargePage(currpage,$( ".p"+currpage ));
 }else if(currpage!=1){
 var nextpage = ($("#flipbook").turn("page"))+1;
 loadLargePage(currpage,$( ".p"+currpage ));
 loadLargePage(nextpage,$( ".p"+nextpage));
 }else if(currpage=1){
 loadLargePage(currpage,$( ".p"+currpage ));
 }});
}
 else{
 $('.magazine-viewport').bind('zoom.tap', zoomTo);
 }
```

Or to zoom in the same as the zoom icon: 

```
$('.magazine-viewport').bind('pinchopen',function() {
if ($(".zoom-icon").hasClass('zoom-icon-in')){
    $(".zoom-icon").trigger('pinchZoomChange');
    $(".zoom-icon").removeClass('zoom-icon-in');
    $(".zoom-icon").addClass('zoom-icon-out');
}
});

$('.magazine-viewport').bind('pinchclose',function() {
if ($(".zoom-icon").hasClass('zoom-icon-out')){     
    $(".zoom-icon").trigger('pinchZoomChange');
    $(".zoom-icon").removeClass('zoom-icon-out');
    $(".zoom-icon").addClass('zoom-icon-in');
}
});
```

Hope that is helpful. Now I am trying to figure out how to use jgestures to allow the slider to work with touch devices.
