### ISSUE TITLE
Technology test: turn.js + pdf.js. Step 2.

### ISSUE THREAD

**Issue by MaximS** [blasten/turn.js#89]
I've modified the main pdf.js full viewer demo to work with turn.js

http://www.maxims6n.bget.ru/book2/viewer/viewer.html
(Zoom out using "-" button to fit a screen - the pdf is landscape and at 100% is probably too wide)

Table of contents and page thumbnails are available - see a button in a top-left corner.
Cross-page and outer links are working.
HW acceleration mode is activated - in the latest dev-channel Chrome it works almost OK (back-side gradients disappear at some angles when turning a page under WinXP - issue filed for Chrome team).

Still waiting for hard and paper book covers...

**Comment by MyiOffice** [comment]
Very interesting - I could help support this work if it can be applied to create html5 eCommerce catalogs.

**Comment by blasten** [comment]
@MaximS It looks great. I'm also interested in a complete integration pdf.js and turn.js.

**Comment by jedahan** [comment]
Looks neat, but I am worried about having a complete pdf renderer loading with turn.js and never being used (I use html for all my pages). Goes from being a lightweight library to some all-or-nothing framework. I guess I can fork when it comes to that point.

**Comment by Caroline-Elisa** [comment]
Wow, this is great! Would be perfect for a project I am just starting...

**Comment by thshen34** [comment]
Hi Maxim,

Is there anyway you can send that directory with the pdf file to me?

I'd love to continue developing it and possibly add other formats to import into your scripts.

**Comment by blasten** [comment]
@MaximS  what is your email address?

**Comment by thshen34** [comment]
Hi MaximS,

My email address is celticsjno34@yahoo.com. Thanks so much!

**Comment by closdesign** [comment]
Please Please Please do the integration of Turn.js and pdf.js.  I think this is why Flash is still being used ALOT for Flip books.  Because people can upload PDF's and use them in the Flipbooks. Having this marriage would be SOOOO much better.  And would take the market by storm since many of the iToys don't use Flash and everyone sends us PDF's to try to turn into Flip Books.  Please do this.  We can always turn PDF's into images, but of course they lose their quality and harm the readability of the text.

**Comment by MyiOffice** [comment]
Agree please let me know how I can help.

**Comment by nvdnkpr** [comment]
Hello maxim,
could you send me that directory too ? my email is navid@nikpour.com

i would like to develop that further too

**Comment by kaynenh** [comment]
This looks very promising. I'd also be interested in the working source of this integration. My email is kaynenh@gmail.com. Thanks!

**Comment by nandi4um** [comment]
Could you please email me a copy of the folder.. I would also like to develop on that.. (nandana@trikode.com)

**Comment by bshorrosh** [comment]
Great work. 

Could you please email me the source code for further development. 
bshorrosh@yahoo.com.

Thanks.

**Comment by entio** [comment]
Hi, its amazing!
Can i also have one copy sent at inne@entio.pl for developing interactive catalogue, please? I wanna add some features to turnjs and wondering if using pdfjs would be shortcut to achieve my goals.

Thanks

**Comment by Godinall** [comment]
Really brilliant thinking, I was converting a PDF to flip pages but I first have to export pages as image and then use turn.js. Your work just saves so much time.
May I have a copy and see what I can contribute to it?

Thanks.

Ken
god_in_all@hotmail.com

**Comment by ryHollingsworth** [comment]
Going to have to second that, this is a phenomenal idea! So many clients will provide a designer a pdf of their catalogue and say "here make this into a digital magazine" your efforts here are much appreciated :) If you're still up for letting others toy with your innovation I wouldn't mind attempting to tie in your efforts with my responsive design efforts. It may be worthwhile creating a branch or fork of blasten's work to branch out (forgive me if the github terminology is off.. new to it!) Anyways, i can be reached at rmhollingsworthweb@gmail.com and would love to work with you all :)

**Comment by bssbbr** [comment]
I purchased the commercial version 4 of turn.js, I should integrate with pdf.js, I wanted to know if you have any sample scripts turn.js integration between 4 and pdf.js, I have the problem of compatibility with IE and iPhone.

Sorry for English but do not know him well.
can someone help me?

Thanks

Barbara bssbbr@hotmail.com

**Comment by tikam** [comment]
Hi,

Can you please send me the latest js of turn.js and pdf.js for version 4.

It is awesome if it happen.   my mail id is tikamjain@gmail.com

Tikam
tikamjain@gmail.com

**Comment by closdesign** [comment]
@tikam,
I think you have to purchase Turn.js version 4. Have you done that yet?  Doing a simple Google search you can get pdf.js latest from GitHub.

**Comment by chaosterx** [comment]
Hello :)

could you send me that directory too ? my email is mero.rizk@gmail.com

i would like to develop that further too

Omar

**Comment by fragrusti** [comment]
Hi all,
I'm very interested in this turn+pdf fusion !
Could you please send me the src? 

my mail:  shaice@gmail.com

Tnx in adv
bye

**Comment by amitkenny** [comment]
Hi,
Really wanted to use turnjs + pdf js

Can you kindly send me the src?

email :  am71185@gmail.com

Thanks and Regards : Amit

**Comment by ryHollingsworth** [comment]
People are super interested in this! I replied several months ago and haven't received anything, but i did not state that I  have purchased the commercial v4 of the product, which may be a reason. @MaximS may not be following the thread anymore or moved on project wise. Just an FYI incase you're 'putting eggs in this basket'. Super phenomenal idea which deserves props! 

-Cheers

**Comment by amitkenny** [comment]
@ryHollingsworth did u try combining it urself?

**Comment by ryHollingsworth** [comment]
@amitkenny wouldn't mind taking that on but to be brief... no time, no need for it-i'd love to pitch it to my company though... my company has about a dozen digital distribution magazines monthly, but they just switched to a new flash program to handle it so for me personally, moot point... But if i had free time i totally would! Hats off and my respect to whomever does... I'm also very very green in the javascript/jQuery department. Learning, but turn.js is way out of my league :)

**Comment by RezaMaz** [comment]
Hi all,
I'm very interested in this turn+pdf fusion !
Could you please send me the src?

my mail: rmazloom88@gmail.com

Tnx in adv
bye

**Comment by vicary** [comment]
Wow this is hot! It would be lovely to be put on Github.

**Comment by ghost** [comment]
Any updates on this? Using it with v4 of Turn.js and the most recent PDF.js would really be something! Perhaps you could share what you did to make it work with the older versions so others could continue where you left off? Inspecting the code of your example isn't much help since it's outdated and both scripts have been greatly improved since.

**Comment by hardikramwani** [comment]
Hello,

I purchased the commercial version 4 of turn.js.
I have try using turn.js and pdf.js but clearity issues are there and also first page is not visible.
Could you please email me the source code for further development. 
ramwanihardik@hotmail.com

Thanks & Regards
Hardik Ramwani

**Comment by Duque29** [comment]
would appreciate if you can send the code to e andyduque@live.com
thanks man

**Comment by Hygea** [comment]
Would also like to have a go at it! vbw88@hotmail.com!
Cheers

**Comment by likeavirgil** [comment]
it works with IE 7 ? Please send me the code to codaap@gmail.com. Thanks ;)

**Comment by GeorgeChatzigiannis** [comment]
I would like to contribute to the project too.Please send me the source code το hatzigiannis@outlook.com. Thank you :)

**Comment by myphuong** [comment]
could you send me source code? my email is sarahsam@ymail.com. Thanks

**Comment by ghost** [comment]
Has something been done on it yet ? Like a separate project of turn.js integrated with pdf.js ?

**Comment by vanhunghus** [comment]
Hello maxim,
could you send me that directory too ? my email is lehung.hus@gmail.com. Thanks

**Comment by NickMeijer** [comment]
Hello maxim,

Could you send me that directory too? E-mail: nickmeijer@live.nl

**Comment by gastonnina** [comment]
Hi.

could you send me that directory too ? my email is gastonnina@gmail.com

**Comment by DWIJO24** [comment]
Hello maxim,
could you send me source code please? my email is rizkidwijo@gmail.com 
Thanks

**Comment by JorgeAmelunge** [comment]
Hello maxim.
Could you please email me the source code please? my email is tahui01@hotmail.com

**Comment by vsok** [comment]
Hello maxim.
Could you please email me the source code? my email is sok.vuthy@gmail.com

**Comment by mag2014** [comment]
this one really helped me http://flipbook.1024bitslabs.com. The standard version is ok.

**Comment by Duque9410** [comment]
yo uní las dos librerías  pdf.js  y turn.js  cree un flypaper con pdf  sin necesidad de ningun software aqui esta el link del video https://www.youtube.com/watch?v=f6_arCce8Q4&feature=youtu.be

**Comment by ShreetiL** [comment]
hi..
kindly send me the source code plz. My email id shreeti91@gmail.com

**Comment by cedtnee** [comment]
Hi Maxim,
 Could you please send me the source? 

my email: cedric.tnee@gmail.com

Regards

**Comment by mayank23er** [comment]
:+1:  Can you please send me too : 

Email : mayank.capricon@gmail.com

**Comment by olifem** [comment]
03.03.2015, 12:16, "mayank23er" notifications@github.com: Can you please send me too :Email : mayank.capricon@gmail.com—Reply to this email directly or view it on GitHub.?

**Comment by jozephol** [comment]
plzz send it to me,this is my email : youssef.ofattole@gmail.com 
thnks

**Comment by maritoivan** [comment]
Maxim, your work is perfect, means too much for me. Please, I'd love to keep it growing, so if you want you can send it to me: maritoivan@yahoo.com. Thank you very much!!!!

**Comment by dereXeus** [comment]
Hi Maxim, please send the source code to aviral12028@gmail.com. Thanks !!!

**Comment by tristanhall** [comment]
@MaximS Could you send the source code to tristan@tmprod.com? Thanks!

**Comment by drazeni** [comment]
Hi Maxim, you're probably receiving so many requests for the files. I'll take a shot at it too because I'm really trying to implement a project with turn and pdf js.

If you would kindly send to mario@d-base.co.za much appreciated. Well done on the good work.

**Comment by finfin82** [comment]
@MaximS Once again, pls send me a copy. Im very interested in how you managed to combine both benefits ;-). andybernstein82@gmail.com

Thank you so much. Cheers Andy

**Comment by Zalimben** [comment]
@MaximS Hi there. 
Could you send the source code to szalimben93@gmail.com?
Thanks a lot!

**Comment by Drjacky** [comment]
Hi Maxim, Please please send the source code to dr_jacky_2005@yahoo.com . Thanks !!!

**Comment by bhaveshvavdiya** [comment]
Can you please send me too :

Email : bhaveshvavadiya89@gmail.com

**Comment by mcohrs** [comment]
Hi Maxim 

Are you already tired of getting sourcecode requests ?

**Comment by Bucci83** [comment]
Hi Maxim, your demo doesn't work on Chrome 44.0.2403.157 m, although it works on Firefox. In any case, what did you used to make the pdf's hyperlinks (inside the document) available when rendered in the flip book. I just did a project with pdf.js and turn.js and the hyperliks are disabled since the pdf gets rendered as an image. Thanks!

**Comment by sahanDissanayake** [comment]
@MaximS posible zoom level solution
```javascript
$('#viewer').css({'width': $(window).width()});
$('.turn-page-wrapper, .page').css({'width': $(window).width()/2})
```

**Comment by JanaME** [comment]
Hey @MaximS 
Could you please send the source code to je@palasthotel.de

Thanks a lot!

**Comment by marietaGonzales** [comment]
Can you send me the code please? 
maru.mgm@gmail.com

Thanks!

**Comment by dermawaruwu** [comment]
Count me in. Would you send me too ?

My email is derma5455@yahoo.com

**Comment by neiryerit** [comment]
Hi.. great post.. Can you send me the code please? i really need it
neiryerit@yahoo.es

**Comment by pippidy281** [comment]
Hi Maxim S. Great job!
Could you please send me a copy? I've been looking for this for so long and I really need it.
My email address is galaxy28140@gmail.com

Thank you so much.

**Comment by asterix555** [comment]
Hi,
sounds great! pls. send a copy to joky.es@gmail.com

btw: would it be possible to put it on github as a fork of turn.js?

**Comment by SabaRathnam-K** [comment]
Hi Maxim.. Can u please send me a copy to saba.wings@gmail.com

Thank U.

**Comment by thuanthaibao** [comment]
hi Maxin....Can u please send me a copy to thuanthuan0907@gmail.com
Than you.......!!!!!!

**Comment by anilgid** [comment]
Hi Maxim

Can you please share the source code to this mail id anil.gid@gmail.com

Thanks
Anil

**Comment by kawaldeep** [comment]
Hi Maxim

Can you please share the source code to this mail id kawaldeep@storymirror.com

Thanks
Kawaldeep

**Comment by pthphap** [comment]
Hi Maxim

Can you please share the source code to my email pthphap@gmail.com

Thanks

**Comment by Krishna25Vrinsoft** [comment]
Hi Maxim
It's really a very nice combo of Turn.js and Pdf.js. 
Can you please share your source code?
My email: krishna.vrinsofts@gmail.com

**Comment by gildassamuel** [comment]
Hi MaximS
it's very nice please can please share your source code?
My email: samuel.gildas12@gmail.com
thank.

**Comment by thinhpd** [comment]
Hi,
Really wanted to use turnjs + pdf js

Can you kindly send me the src?

email : thinhpdfit@gmail.com

Thanks and Regards

**Comment by EmilSabitov** [comment]
Hello.
Can you send me it too? 
emilsabitov@gmail.com

Thank you!

**Comment by sturo82** [comment]
hello,
great work!
i'm also interested, can you send me the src?
thanks so much!
email:sturo82@gmail.com

**Comment by Ihvanmp** [comment]
amazing!
can you send me the src too please?
email : ihvanmultimedia@gmail.com

Thanks,

**Comment by ammopt** [comment]
Hi Maxim

Great work!
I am also interested in the source code.
email: pjamorim91@gmail.com

Thank you

**Comment by tomascharad** [comment]
Hi @MaximS 

Awesome work!
Could you please send me a copy?
email: tomas.charad@gmail.com

Best regards!

**Comment by lostinmyworld** [comment]
Is there a tutorial or something like that to implement this? I am a beginner at JS so it will help a lot!

Thank you!!

**Comment by EmanMo7amed** [comment]
@MaximS 
if you don't have any problem with sharing your source code, could you please share it with us on some thing like github or my mail " eman2013.emmy@gmail.com " ..
if you prefere not sharing I understand. thanx :)

**Comment by sk-seo** [comment]
Hi Maxim,
that really looks great! I also would be interested in the source code. email: k.schroedl@gmail.com
Thanks a lot!

**Comment by crebuh** [comment]
Hi Maxim! Your approach looks great!!

I am also interested in the source code.
email: christofer.huber@gmail.com

Thank you

**Comment by anased** [comment]
Hi Maxim!, Your way of integrating the two plugins is what I want exactly so can you please send the source code to me at anased25@gmail.com

**Comment by hendrawidjaja** [comment]
HI Maxim, is it possible to have the example ?
hendrawidjaja@live.de

**Comment by white-beard** [comment]
Привет! у тебя ещё не осталось исходников? пришли пожалуйста на [maximsen@gmail.com](url). Заранее благодарю;)

**Comment by white-beard** [comment]
Привет! Присоединяюсь к комментарию выше
[maximsen@gmail.com](url)

**Comment by erayakartuna** [comment]
Hi guys.That is an example: https://github.com/erayakartuna/pdf-flipbook

**Comment by iberan** [comment]
Hi folks, this is another one: https://github.com/iberan/pdfjs-flipbook

**Comment by joffrey71** [comment]
HI Maxim, is it possible to have the example ?
Can you send me your example to cousin.joffrey@gmail.com

Thanks

**Comment by FelixRufus** [comment]
Great work.

Could you please email me the source code for further development.
felixnadar123@gmail.com

Thanks.

**Comment by icemancapo** [comment]
Hello, I think your work is very good, I would like to study it, please if possible pass me the src of the code to study it and see what I can cooperate for your attention, thank you very much, my email is icemancapo69@gmail.com, I hope we can support

**Comment by anhon** [comment]
Awesome work.
Can you send me the src too please?

vinet.antho@gmail.com

Thanks,

**Comment by odahcam** [comment]
Publish in GitHub once for all.

**Comment by surendrarathore** [comment]
@MaximS  i like your idea. could u send me your source code. please
singhrathoresumit9@gmail.com

thanks

**Comment by PravinkumarA** [comment]
Please send it for me too, i'm waiting for this feature from long time.
My email id is pkumar.a1211@gmail.com

**Comment by SanjayJaiswa** [comment]
Really wanted to use turnjs + pdf js

Can you kindly send me the src?

email : sanjay.j@latitudetechnolabs.com

**Comment by BrunoAssis12** [comment]
Please send it for me too, i'm have been try this for a long time.

Can you kindly send me the src?

e-mail: bruno.assis.14@hotmail.com

**Comment by suryakumar-sekar** [comment]
hi MaximS,

Can you please send the src code to "suriya1039@gmail.com"

**Comment by giangsaker1102** [comment]
hi MaximS,

Can you please send the src code to "pcgiang93@gmail.com"

**Comment by onlinekedar** [comment]
hi MaximS,
Can you also send me the src on this to "kunwar182@gmail.com". I have been looking into this type of project. I hope i can further add to it and share it with you again.

Thanks in Advance.

**Comment by FouziDa** [comment]
Please anyone send the code to me
[aboalfouz3@gmail.com](url)
thank you

**Comment by FouziDa** [comment]
Please ... Anyone send the code
[aboalfouz3@gmail.com](mail)

Thank you

**Comment by iberan** [comment]
Visit this:

[https://github.com/iamapinan/pdf-html5-page-flip](https://github.com/iamapinan/pdf-html5-page-flip)
