### ISSUE TITLE
Width of 721px in Chrome

### ISSUE THREAD

**Issue by donflopez** [blasten/turn.js#9]
In Chrome (i haven't tried with other), with the example, I use a width of 400px per page and the third page have 721px. Perhaps I don't know use correctly, but I have put the example.

Sorry about my english.

**Comment by blasten** [comment]
If you are using CSS:

#magazine{
    width:800px;
    height:400px;
}
#magazine .turn-page{
    width:400px;
    height:400px;
    background-color:#ccc;
}

Directly by options:

{width:800, height:400}

All the pages should have the same width, in case of double page this has to be twice the width of a single page.
