### ISSUE TITLE
Question to turn.js Script

### ISSUE THREAD

**Issue by Surfer81** [blasten/turn.js#90]
Hi.

I have a question about turn.js Script. I just need an App for iPad like this: http://www.youtube.com/watch?v=m9D-nD5v83c

What do I need to do everything? Is it enough if I take this https://github.com/blasten/turn.js/tree/master/demos/magazine? Or do I have to change what?

For your help I would be very grateful!

Thanks!

Best regards,
Juri 

PS: Excuse me for my English, but I am not good in English.

**Comment by blasten** [comment]
You would need some coding but the next version will include more complete samples.

**Comment by Surfer81** [comment]
And when will the next version?

-------- Original-Nachricht --------

> Datum: Thu, 31 May 2012 21:04:29 -0700
> Von: Emmanuel Garcia reply@reply.github.com
> An: Surfer81 swoj@gmx.net
> Betreff: Re: [turn.js] Question to turn.js Script (#90)
> 
> You would need some coding but the next version will include more complete
> samples.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/blasten/turn.js/issues/90#issuecomment-6053121

## 

Empfehlen Sie GMX DSL Ihren Freunden und Bekannten und wir
belohnen Sie mit bis zu 50,- Euro! https://freundschaftswerbung.gmx.de

**Comment by blasten** [comment]
@Surfer81 It's available right now on www.turnjs.com
