### ISSUE TITLE
Strange glitch for pages loaded the first time

### ISSUE THREAD

**Issue by bbence84** [blasten/turn.js#91]
Hi,

I have the following issue: when the next page is not yet loaded, the turning effect has a strange glitch on the top. See for example: http://domainname/valleyofsorrow/main.html, where domainname is meltingpot.hu (so replace domainname with meltingpot.hu), I just don't want this url to come up in google. :)
Anyway, on the above example you can see what I mean, especially if you try to turn the page with the top flip.

Any ideas? :)

Thanks!
Bence

**Comment by blasten** [comment]
Well, yes. there's is a problem with the layout. You can fix it by adding the rule `float: left;` to `#book .turn-page`   It seems like the reason is the paragraphs and the margin top/bottom that they have. I'll make some test and probably add that rule directly to turn.js

**Comment by bbence84** [comment]
Awesome, thanks! :)
The solution works like a charm!
