### ISSUE TITLE
 Is it possible to add audio when the page is turned?

### ISSUE THREAD

**Issue by brunotvaz** [blasten/turn.js#93]
Hello:

Congratulations on your amazing script. You rock big time !
I tried to open a new "pull request" but was unable to do it, so i've decided to post here.
I want to know if its possible to add audio when the page is turned.
Thanks in advance.

**Comment by brunotvaz** [comment]
Found this audio sample:

http://www.freesound.org/people/Koops/sounds/20258/

**Comment by blasten** [comment]
Yes you can, using the event `turning`.  You can play the audio using the web audio api or a JS library for that.

**Comment by jurgen-74** [comment]
Hi there

This is a real great script. I'm trying to get the sound working but without success. Would it be possible for you to post an example page with sound implemented?

Kind regrads,
Jurgen

**Comment by jurgen-74** [comment]
This is my solution:

In the head sector:
script>
var html5_audiotypes={ //define list of audio file extensions
"mp3": "audio/mpeg",
"ogg": "audio/ogg",
"wav": "audio/wav",
}
function createsoundbite(sound){
var html5audio=document.createElement('audio')
if (html5audio.canPlayType){ //check support for HTML5 audio
    for (var i=0; i<arguments.length; i++){
        var sourceel=document.createElement('source')
        sourceel.setAttribute('src', arguments[i])
        if (arguments[i].match(/.(\w+)$/i))
            sourceel.setAttribute('type', html5_audiotypes[RegExp.$1])
        html5audio.appendChild(sourceel)
    }
    html5audio.load()
    html5audio.playclip=function(){
        html5audio.pause()
        html5audio.currentTime=0
        html5audio.play()
    }
    return html5audio
}
else{
    return {playclip:function(){throw new Error("Your browser doesn't support HTML5 audio unfortunately")}}
    }
}
//Initialize sound clips with 1 fallback file each:
var flip=createsoundbite("YOURSOUND.ogg", "YOURSOUND.mp3","YOURSOUND.wav")
</script

And finally in the script:
$('#magazine').turn(
    {
    when:{
    turning:function(){flip.playclip();
    }}
    }   );

**Comment by 404pnf** [comment]
@jurgen-74 

Would you please post a working example as a gist?

I want to know how it works.  I am making a book with mp3 audios for some of the page.

1.jpg, 1.mp3
2.jpg,
3.jpg, 3.mp3

I want to turn to a page, and the mp3 starts to play automatically.   

Can figure out how to do it.  Since the whole page is loaded at once.

**Comment by jurgen-74** [comment]
@404pnf 

Yes, sure.
If you go to this page:
http://www.apologeet.nl/3vmbo/introductie#flipbook-3vmbo
You'll see my solution, which works great for me.
Note that I did not go through the hassle of making it work under IE8 and lower. I've made a short message to notify people how they can download a good browser (it is in Dutch).

Please let us know if you have any problems,
Jurgen

**Comment by 404pnf** [comment]
@jurgen-74 

Sorry.  I didn't make words clear enough. And now I see I mis-read the whole thread.

I was thinking each page has a unique audio file, it's an audibook with text.

Now I see the issue is about add page-turning sound effects.

Sorry.

I have to find my solution some other way. 

Thank you for the quick response.  The site looks craftly made.

**Comment by jurgen-74** [comment]
No worries,
sounds like an interesting project.
Good luck

**Comment by gugulethu03** [comment]
@jurgen-74 i visited the link http://www.apologeet.nl/3vmbo/introductie#flipbook-3vmbo however i still didnt get page flip sounds, and i am working on chrome.
