### ISSUE TITLE
Can I "free" the swipe function on first and last pages?

### ISSUE THREAD

**Issue by perdittmann** [blasten/turn.js#95]
Hi everyone,

I am working on a project for an iPad app. The app has a built-in swipe functionality to change between pages. One of the pages will be a webview window with a turn.js-magazine in it (as a multi-paged ad).

It appears that turn.js prevents the app's swipe function from kicking in on the last page (which would be what I'd want), so the reader can't leave the ad (since swiping would be the only possible way out).

Is there a way to disable the turn.js-"swipe block" for both ends of the magazine?
It appears to me that turn.js says "There can't be any right-to-left swipe on the last page and I will actively assign a non-function to any that occur", would it be possible to make that "I don't care about any right-to-left-swipes on the last page, but go ahead if you think that helps you"? (The same thing for left-to-right swipes on the first page.)

Any advice on this would be greatly appreciated!
Many thanks!
Per

**Comment by blasten** [comment]
It seems like you can use the event `start` to prevent the touch/mouse events you need. for example:

``` javascript
$('flipbook').bind('start', function(event, pageObj, corner) {
    if(pageObj.page==1 && coner=='br'){
        event.preventDefault();
    }
 });
```

**Comment by perdittmann** [comment]
Hi blasten, thanks for your reply.

Just to make sure - would the solution you propose prevent the events from being handled by turn.js (that would be what I need), or would it prevent them from being handled at all?

Or a different approach: would it be possible to have the touch events completely handled by another script and just have them call $('#magazine').turn('next'); ? 
Or has turn.js to be actively stopped from handling the touch events? If so, could the code you kindly posted above be expanded to work for all areas on all pages?

Many thanks for your kind support!
