### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by floydchengmailcom** [blasten/turn.js#96]
I love this plugin, and I have some suggestions
first, could you add hard page style, covers of many book are hard
second, transparent page,such as some toy books of kids
third, the effective of tear down a page

**Comment by blasten** [comment]
Hey, hard pages are the most important feature of the new version.  and you can add transparent pages by putting the background in rgba format. eg.  rgba(255,0,0,0.5) to the page you want.  
For example:

#flipbook .p5{
background-color:rgba(255,0,0,0.5);
}

**Comment by ofdevelopment** [comment]
The ability to tear out a page would be amazing. Make the page tear off and have an event triggered like the ability to share that page or email it. Oh the possibilities!
