### ISSUE TITLE
Problem using page method

### ISSUE THREAD

**Issue by karlcampbell** [blasten/turn.js#98]
Hi, there. I'm having a problem when using the page method to turn pages. It doesn't happen all the time which is the most frustrating thing. When I call it, sometimes the page will turn sideways and the whole thing breaks. I then get a JS error 'data is undefined' on line 1798 of turn.js. It's hard to describe, so here's a link to the site:

http://dev.bitpowered.ca/encorp/report

I find it most often happens if I use the menu right off the page load. If I turn a page normally then use the menu (which calls the page method), it rarely seems to happen.

I've tried everything I can think of. I've removed all other javascript on the site to minimize conflicts and still nothing. Is this a bug, or am I doing something wrong? 

Thanks

**Comment by yaffar666** [comment]
Hello blasten, Iam having the same issue that karlc is talking about, it is very difficult to reproduce and cannot get the exact conditions to reproduce it.
It happens in this site: http://eco-guia.com.ec/neotropic/client/init.html

I've trying to figure out what could happen with no positive results.

Thanks for your help.

**Comment by eneyed** [comment]
the steps you can reproduce:
1. Hover on to a page corner, wait for the curl to appear.
2. Now move the mouse out of the corner and wait for the curl to disappear.
3. Now try jumping to another page (the other page has to be a distant one ie, if you are in page 2, jump to 6 or 10 or 20)

**Comment by eneyed** [comment]
we got a quick wok around for the problem:
in the function '_end' :

<pre>
else {
            turnMethods._removeMv.call(turn, opts.pageMv);
            turn.turn('update');
        }
</pre>


comment off this line:

<pre>
turnMethods._removeMv.call(turn, opts.pageMv);
</pre>


This will work :) if you can respond why, that would help a lot.
Thanks!

**Comment by karlcampbell** [comment]
I can confirm, those steps reproduced the issue for me as well. Commenting out that line also seemed to fix the problem. Thanks eneyed for figuring that out!

**Comment by blasten** [comment]
This issue is fixed in the 4th release.  I hope to update this repo soon.
