### ISSUE TITLE
Page Turn Threshold on Single View

### ISSUE THREAD

**Issue by Annodyne** [blasten/turn.js#99]
I noticed that in the single view option the drag effect triggers a flip when the release occurs past the boundaries of the content.

I was hoping to modify things slightly to trigger the flip when the release occurs halfway past the content, like it does in double view.  

My brain however was not built for trigonometry...

Does anyone have any ideas or possible fixes for this?

Many thanks!

**Comment by blasten** [comment]
All you need to change is a single line of code:
https://github.com/blasten/turn.js/blob/master/turn.js#L1071

**Comment by Annodyne** [comment]
That's great, thanks.  I was digging too deep.  And thanks for the software.  I bought a commercial license last week.
